image: alpine/latest
packages:
        - texinfo
sources:
        - https://git.sr.ht/~dsemy/vcomplete
tasks:
        - build: |
                cd vcomplete
                make
artifacts:
        - vcomplete/vcomplete-2.0.tar
