#+title: Contributing | Gnosis
#+author: Thanos Apollo


* Sources
+ [[https://git.thanosapollo.org/gnosis][Upstream]]

* How To Contribute
Before starting to work on any big feature, that is not mentioned on
the [[Task List][Task List]], I recommend you to send me an email first.

** How to submit a PR?
Feel free to send me a patch, here's how to create one:

#+begin_src bash
$ git clone https://git.thanosapollo.com/<repo>.git && cd <repo>
$ emacs something
$ git add something
$ git commit -m "Fix something"
$ git format-patch HEAD^1
0001-Fix-something.patch
#+end_src

/You can find my email on the git log/


* Tasks
** TODO Add Dashboard
+ Create a dashboard to view all notes created, user can edit &
  suspend notes. Use tabulated-list-mode, preferably.

** TODO Algorithm: changes for ef increase/decrease factors
+ After 3 successful in a row reviews increase ef increase factor by 5% & vice versa

** DONE Refactor =completing-read= UI choices
CLOSED: [2024-02-17 Sat 21:59]
/DONE on version 0.1.7/

=completing-read= is not an ideal solution as a UI. If user has not
enabled a completion system, such as vertico, this would make gnosis
unusable.

One possible solution is to create defcustom =gnosis-completing-read-function=
that has ido-completing-read by default if vertico/ivy/helm is not
enabled

*** Fix

Implemented =gnosis-completing-read-function=

** DONE Use vc instead git shell commands
CLOSED: [2024-02-17 Sat 21:59]

/DONE on version 0.1.7/

Implemented =gnosis-git-*= functions to handle git commands.

