#!/bin/sh

# Pass XMPP URIs to jabber.el.  See `(jabber)XMPP URIs'.

if [ ! $# -eq 1 ]; then
  echo "Usage: $0 xmpp:romeo@montague.net"; exit 1
fi

emacsclient -e '(jabber-handle-uri (pop server-eval-args-left))' "$1"
