(require 'esxml)
(require 'ert)

;; (esxml-trim-ws)
;; (esxml-validate-form)

(ert-deftest esxml-to-xml ()
  (should (equal (esxml-to-xml "foo") "foo"))
  (should (equal (esxml-to-xml '(foo nil)) "<foo/>"))
  (should (equal (esxml-to-xml '(foo nil "bar")) "<foo>bar</foo>"))
  (should (equal (esxml-to-xml '(foo nil (bar nil) (baz nil)))
                 "<foo><bar/><baz/></foo>"))
  (should (equal (esxml-to-xml '(foo nil (bar nil "baz")))
                 "<foo><bar>baz</bar></foo>"))
  (should (equal (esxml-to-xml '(foo ((key . "val")) "bar"))
                 "<foo key=\"val\">bar</foo>"))
  (should (equal (esxml-to-xml '(foo ((key . "val") (key2 . "val2")) "bar"))
                 "<foo key=\"val\" key2=\"val2\">bar</foo>")))
  (should (equal (esxml-to-xml '(foo nil "text" (comment "hidden") "more text"))
                 "<foo>text<!-- hidden -->more text</foo>"))
  (should (equal (esxml-to-xml '(comment nil "old comment syntax still works"))
                 "<!-- old comment syntax still works -->"))

;; (sxml-to-esxml)
;; (xml-to-esxml)
;; ;; (esxml-get-by-key)
;; ;; (esxml-get-tags)
;; ;; (esxml-destructuring-mapcar)

(ert-deftest esxml-raw-string ()
  (should (equal (esxml-to-xml "foo") "foo"))
  (should (equal (esxml-to-xml "<br>") "&lt;br&gt;"))
  (should (equal (esxml-to-xml '(raw-string "<br>")) "<br>"))
  (should (equal (esxml-to-xml '(p nil "<br>")) "<p>&lt;br&gt;</p>"))
  (should (equal (esxml-to-xml '(p nil (raw-string "<br>"))) "<p><br></p>")))
