* fedi.el

A library to make writing clients for APIs easier.

It uses code from my [[https://codeberg.org/martianh/mastodon.el][mastodon.el]] to make it easy to write endpoint-hitting
functions for JSON APIs.

The example macro =fedi-request= allows you to quickly create HTTP request
commands to API endpoints, with parameters automatically constructed and sent
as form data or JSON payloads (for POST, PUT, DELETE, and probably PATCH). You should write your own similar macro in your package. See my =lem.el= for an working example. That way you can handle package-specific parameters such as authentication.

Responses are checked with =fedi-http--triage=, and processed with
=fedi-http--process-response=. If a response returns HTML (i.e. for a 404), it
is rendered with =shr=, otherwise the JSON is parsed and returned.

Because of how =mastodon.el= works, there is also code for handling link headers
in responses. Mastodon uses these for pagination in some cases. If your
service also does, you can handle them too.

For an example of using this library, see my [[https://codeberg.org/martianh/lem][lem]] repo.
