#+html: <p align=right>
#+html: <a href="http://elpa.nongnu.org/nongnu/geiser-chicken.html"><img alt="NonGNU Elpa" src="http://elpa.nongnu.org/nongnu/geiser-chicken.svg"/> </a>
#+html: <a href="http://elpa.nongnu.org/nongnu-devel/geiser-chicken.html"><img alt="NonGNU Devel Elpa" src="http://elpa.nongnu.org/nongnu-devel/geiser-chicken.svg"/></a>
#+html: <a href="https://melpa.org/#/geiser-chicken"><img alt="MELPA" src="https://melpa.org/packages/geiser-chicken-badge.svg"/></a>
#+html: </p>

* Chicken and Geiser talk to each other

  Geiser is a generic Emacs/Scheme interaction mode, featuring an
  enhanced REPL and a set of minor modes improving Emacs' basic scheme
  major mode. This package add support for Chicken in Geiser.

*** Installation

    The easiest way is to use MELPA, and just type
    =M-x package-install RET geiser-chicken= inside emacs.

    Geiser-chicken can be used either directly from its uninstalled
    source tree: just add it to your load path and require
    ~geiser-chicken~ in your initialisation files.

    Then install the required Chicken eggs:

    #+BEGIN_EXAMPLE
    $ chicken-install -s chicken-doc apropos
    #+END_EXAMPLE

    Then follow the instructions on the Chicken Wiki to install the documentation
    package for your Chicken version:

    https://api.call-cc.org/6/doc/chicken-doc#sec:Pre-built_packages

    Packages for Chicken 4, 5, and 6 are currently available.

*** Troubleshooting

    If "nothing works", the most likely reason is the missing documentation
    package, causing the Geiser bootstrap code not to load. To verify, start ~csi~
    and try to import ~chicken-doc~.

    #+begin_example
      ____,     CHICKEN
     /   ^ >    (c) 2008 The CHICKEN Team
    /| ____     (c) 2000-2007 Felix L. Winkelmann
    ||/    \\   macosx-unix-clang-arm64 [ 64bit dload ptables ]
    ||     ||
     \\____/ . 0 . 1pre1 (rev 3a7cb36d)
    Type ,? for help.
    #;1> (import chicken-doc)
    #;2> (verify-repository)
    #<chicken-doc#chicken-doc-repository>
    #;3> (search-only 'car)
    (scheme base car)  (car pair)
    #+end_example

    If you see errors instead, verify your documentation package installation.

* Contributing
*** Generative AI (LLMs)

  Use of generative AI (LLMs, diffusion models and similar technology) is not
  acceptable for contributions to or interactions with this project.

  This includes words, images and code, as well as bug reports, commit
  messages, email (mailing list or private) and IRC messages.
