* fedi.el

A library to make writing clients for APIs easier.

This is a WIP, with code being pulled over from my [[https://codeberg.org/martianh/mastodon.el][mastodon.el]] to make it easy
to write endpoint-hitting functions for JSON APIs. It will be cleaned up more,
but it's already useable.

The macro =fedi-request= allows you to quickly create HTTP request commands to
API endpoints, with parameters automatically constructed and sent as form data or
JSON payloads (for POST, PUT, DELETE, and probably PATCH).

Responses are checked with =fedi-http--triage=, and processed with
=fedi-http--process-response=. If a response returns HTML, it is rendered
with =shr=, otherwise the JSON is parsed and returned.

Because of how =mastodon.el= works, there is also code for handling link headers
in responses. Mastodon uses these for pagination in some cases. If your
service also does, you can handle them too.

If you want to incorporate your service's authentication methods, you may find
it easier to wrap the macro in another inside your own package and incorporate
the auth work there, so you don't need to include it in every request.

For an example of using this library, see my [[https://codeberg.org/martianh/lem][lem]] repo.
