#+title: TODO's for Gnosis
#+author: Thanos Apollo

* Gnosis TODO's

** DONE Add Dashboard
CLOSED: [2024-02-20 Tue 13:33]
+ Create a dashboard to view all notes created, user can edit &
  suspend notes. Use tabulated-list-mode, preferably.
*** Notes after completion
+ Dashboard added using tabulated-list-mode. Performance is not ideal
  when 20K > notes, values should be cached

** TODO Dashboard: Improve Performance
** TODO Dashboard: Add filtering/search

** TODO Algorithm: changes for ef increase/decrease factors
+ After 3 successful in a row reviews increase ef increase factor by 5% & vice versa


** DONE Refactor =completing-read= UI choices
CLOSED: [2024-02-17 Sat 21:59]
/DONE on version 0.1.7/

=completing-read= is not an ideal solution as a UI. If user has not
enabled a completion system, such as vertico, this would make gnosis
unusable.

One possible solution is to create defcustom =gnosis-completing-read-function=
that has ido-completing-read by default if vertico/ivy/helm is not
enabled

*** Notes

Implemented =gnosis-completing-read-function=


** DONE Use vc instead git shell commands
CLOSED: [2024-02-17 Sat 21:59]

/DONE on version 0.1.7/

Implemented =gnosis-git-*= functions to handle git commands.

