#+title: TODO's for Gnosis
#+author: Thanos Apollo
#+startup: content

* Dashboard
** DONE Add Dashboard
CLOSED: [2024-02-20 Tue 13:33]
+ Create a dashboard to view all notes created, user can edit &
  suspend notes. Use tabulated-list-mode, preferably.
** TODO Dashboard: Improve Performance :priorityLow:
+ emacsql is quite fast, but the current tabulated-list implementation
  can be quite slow when having >30K notes. This should be improved upon in the feature
** TODO Dashboard: Add filtering/search 
Search by tags, deck or LIKE question.

* Algorithm
** TODO Algorithm: changes for ef increase/decrease values :priorityHigh:
+ Create a =gnosis-algorithm-ef-increase=, which will be used to
  increase ef increase value upon X consecutive successful reviews  
* Misc  
** DONE Refactor =completing-read= UI choices
CLOSED: [2024-02-17 Sat 21:59]
/DONE on version 0.1.7/

=completing-read= is not an ideal solution as a UI. If user has not
enabled a completion system, such as vertico, this would make gnosis
unusable.

One possible solution is to create defcustom =gnosis-completing-read-function=
that has ido-completing-read by default if vertico/ivy/helm is not
enabled

*** Notes
Implemented =gnosis-completing-read-function=

** TODO Use vc instead to stage & commit :priorityLow:
** DONE Use vc instead git shell commands to push/pull
CLOSED: [2024-02-17 Sat 21:59]

/DONE on version 0.1.7/

Implemented =gnosis-git-*= functions to handle git commands.



