;;; hermes-tool-setup-tests.el --- Tool setup tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'hermes-tool-setup)

(ert-deftest hermes-tool-setup-schema-readiness ()
  (let* ((cfg '((providers . (((name . "Future") (status . "needs_auth")
                              (is_active . t) (env_vars . nil))
                             ((name . "Other") (status . "future_state"))))))
         (rows (hermes-tool-setup--rows cfg)))
    (should (equal (mapcar #'car rows) '("Future" "Other")))
    (should (equal (aref (cadar rows) 2) "needs_auth"))
    (should (equal (aref (cadr (cadr rows)) 2) "future_state"))))

(ert-deftest hermes-tool-setup-secret-save-and-readback ()
  (with-temp-buffer
    (hermes-tool-setup-mode)
    (setq hermes-tool-setup--name "future/tool"
          hermes-tool-setup--profile "second"
          hermes-tool-setup--config
          '((providers . (((name . "Future")
                           (env_vars . (((key . "FUTURE_KEY")))))))))
    (let (request refreshed)
      (cl-letf (((symbol-function 'hermes-tool-setup--provider)
                 (lambda () (car (hermes-transport--get hermes-tool-setup--config 'providers))))
                ((symbol-function 'read-passwd) (lambda (&rest _) "private-value"))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                ((symbol-function 'hermes-browser--run-on-client)
                 (lambda (make success &optional _error)
                   (funcall make 'client)
                   (funcall success '((ok . t)))))
                ((symbol-function 'hermes-dashboard-transport-api-request-async)
                 (lambda (&rest args) (setq request args)))
                ((symbol-function 'hermes-tool-setup-refresh)
                 (lambda (&rest _) (setq refreshed t))))
        (hermes-tool-setup-save-credentials)
        (should (equal (cadr request) "/api/tools/toolsets/future%2Ftool/env"))
        (should (equal (plist-get (cddr request) :query) '((profile . "second"))))
        (should (equal (plist-get (cddr request) :secrets) '("private-value")))
        (should refreshed)
        (should-not (string-match-p "private-value" (buffer-string)))))))


(ert-deftest hermes-tool-setup-failure-and-stale-settlement ()
  (dolist (replacement '(generation instance profile mode killed))
    (let ((buffer (generate-new-buffer " *setup-test*")) success failure changed notices)
      (unwind-protect
          (with-current-buffer buffer
            (hermes-tool-setup-mode)
            (setq hermes-tool-setup--name "future")
            (cl-letf (((symbol-function 'hermes-browser--run-on-client)
                       (lambda (_make ok &optional bad) (setq success ok failure bad)))
                      ((symbol-function 'message)
                       (lambda (&rest args) (push args notices))))
              (hermes-tool-setup--request "GET" "/config" (lambda (_) (setq changed t)))
              (pcase replacement
                ('generation (hermes-browser--next-request-generation))
                ('instance (setq hermes-instance 'other))
                ('profile (setq hermes-tool-setup--profile "other"))
                ('mode (fundamental-mode))
                ('killed (kill-buffer buffer)))
              (funcall success '((ok . t)))
              (funcall failure "secret-from-backend")
              (should-not changed)
              (should-not notices)))
        (when (buffer-live-p buffer) (kill-buffer buffer))))))

(ert-deftest hermes-tool-setup-refusal-rejection-and-prompt-race ()
  (dolist (outcome '(refused rejected declined changed))
    (with-temp-buffer
      (hermes-tool-setup-mode)
      (setq hermes-tool-setup--name "future")
      (let (refreshed dispatched notices)
        (cl-letf (((symbol-function 'yes-or-no-p)
                   (lambda (&rest _)
                     (when (eq outcome 'changed) (hermes-browser--next-request-generation))
                     (not (eq outcome 'declined))))
                  ((symbol-function 'hermes-browser--run-on-client)
                   (lambda (_make ok &optional bad)
                     (setq dispatched t)
                     (if (eq outcome 'rejected) (funcall bad "private-value")
                       (funcall ok '((ok . :false))))))
                  ((symbol-function 'hermes-tool-setup-refresh)
                   (lambda (&rest _) (setq refreshed t)))
                  ((symbol-function 'message) (lambda (&rest args) (push args notices))))
          (if (eq outcome 'changed)
              (should-error (hermes-tool-setup--change "/provider" nil "Change? ") :type 'user-error)
            (hermes-tool-setup--change "/provider" nil "Change? "))
          (should-not refreshed)
          (should-not hermes-tool-setup--busy)
          (when (memq outcome '(changed declined)) (should-not dispatched))
          (should-not (string-match-p "private-value" (format "%S" notices))))))))

(ert-deftest hermes-tool-setup-model-catalog-and-capability-routing ()
  (with-temp-buffer
    (hermes-tool-setup-mode)
    (setq hermes-tool-setup--name "future" hermes-tool-setup--profile "second")
    (let (requests changes)
      (cl-letf (((symbol-function 'hermes-tool-setup--provider)
                 (lambda () '((name . "Future") (capabilities . ("search" "extract")))) )
                ((symbol-function 'completing-read)
                 (lambda (_prompt choices &rest _) (if (consp (car choices)) (caar choices) (car choices))))
                ((symbol-function 'hermes-tool-setup--change)
                 (lambda (&rest args) (push args changes)))
                ((symbol-function 'hermes-browser--run-on-client)
                 (lambda (make ok &optional _bad)
                   (funcall make 'second-client)
                   (funcall ok '((has_models . t) (current . "m")
                                 (models . (((id . "m") (display . "Future Model"))))))))
                ((symbol-function 'hermes-dashboard-transport-api-request-async)
                 (lambda (&rest args) (push args requests))))
        (hermes-tool-setup-select-provider)
        (should (equal (cadar changes) '((provider . "Future") (capability . "search"))))
        (hermes-tool-setup-select-model)
        (should (equal (cadar changes) '((provider . "Future") (model . "m"))))
        (should (equal (plist-get (cddar requests) :query)
                       '((provider . "Future") (profile . "second"))))
        (should (eq (plist-get (cddar requests) :client) 'second-client))))))

(ert-deftest hermes-tool-setup-post-status-is-not-readiness ()
  (with-temp-buffer
    (hermes-tool-setup-mode)
    (setq hermes-tool-setup--name "future")
    (let (request refreshed)
      (cl-letf (((symbol-function 'hermes-browser--run-on-client)
                 (lambda (make ok &optional _bad)
                   (funcall make 'client)
                   (funcall ok '((running . :false) (exit_code . 1)))))
                ((symbol-function 'hermes-dashboard-transport-api-request-async)
                 (lambda (&rest args) (setq request args)))
                ((symbol-function 'hermes-tool-setup-refresh)
                 (lambda (&rest _) (setq refreshed t))))
        (hermes-tool-setup-post-setup-status)
        (should (equal (cadr request) "/api/actions/tools-post-setup/status"))
        (should (equal hermes-tool-setup--post-status "exited 1"))
        (should refreshed)
        (should-not hermes-tool-setup--config)))))


(ert-deftest hermes-tool-setup-public-open-keeps-instance-and-profile ()
  (let ((instance '("second" . "http://second.invalid")) buffer request)
    (unwind-protect
        (cl-letf (((symbol-function 'hermes-instance-resolve) (lambda () instance))
                  ((symbol-function 'pop-to-buffer) (lambda (value &rest _) (setq buffer value)))
                  ((symbol-function 'hermes-browser--run-on-client)
                   (lambda (make ok &optional _bad)
                     (should (equal hermes-instance instance))
                     (funcall make 'second-client)
                     (funcall ok '((has_category . t)
                                   (providers . (((name . "Future") (status . "needs_setup"))))))))
                  ((symbol-function 'hermes-dashboard-transport-api-request-async)
                   (lambda (&rest args) (setq request args))))
          (hermes-tool-setup "future" "second-profile")
          (should (equal (plist-get (cddr request) :query) '((profile . "second-profile"))))
          (with-current-buffer buffer
            (should (equal hermes-instance instance))
            (should (string-match-p "Future" (buffer-string)))
            (should (string-match-p "needs_setup" (buffer-string)))
            (should (string-match-p "second-profile" header-line-format))
            (should (eq (key-binding (kbd "k")) #'hermes-tool-setup-save-credentials))))
      (when (buffer-live-p buffer) (kill-buffer buffer)))))

(ert-deftest hermes-tool-setup-model-readback-detects-mismatch ()
  (with-temp-buffer
    (hermes-tool-setup-mode)
    (setq hermes-tool-setup--name "future" hermes-tool-setup--profile "second")
    (let (notice request refreshed)
      (cl-letf (((symbol-function 'hermes-browser--run-on-client)
                 (lambda (make ok &optional _bad)
                   (funcall make 'client)
                   (funcall ok '((current . "different")))))
                ((symbol-function 'hermes-dashboard-transport-api-request-async)
                 (lambda (&rest args) (setq request args)))
                ((symbol-function 'hermes-tool-setup-refresh) (lambda (&rest _) (setq refreshed t)))
                ((symbol-function 'message) (lambda (fmt &rest args) (setq notice (apply #'format fmt args)))))
        (hermes-tool-setup--verify-model "Future" "wanted")
        (should (equal (cadr request) "/api/tools/toolsets/future/models"))
        (should (equal (plist-get (cddr request) :query)
                       '((provider . "Future") (profile . "second"))))
        (should refreshed)
        (should (string-match-p "not confirmed" notice))))))

(ert-deftest hermes-tool-setup-install-requires-explicit-named-profile ()
  ;; Default on a named dashboard inherits its home; nil on a root dashboard
  ;; can reread a changed active_profile.  Neither is an exact install scope.
  (dolist (profile '("default" nil "current" " DEFAULT " "" "second"))
    (with-temp-buffer
      (hermes-tool-setup-mode)
      (setq hermes-tool-setup--name "future"
            hermes-tool-setup--profile profile)
      (let (request confirmed)
        (cl-letf (((symbol-function 'hermes-tool-setup--provider)
                   (lambda () '((name . "Future") (post_setup . "future-install"))))
                  ((symbol-function 'yes-or-no-p)
                   (lambda (&rest _) (setq confirmed t)))
                  ((symbol-function 'hermes-browser--run-on-client)
                   (lambda (make &rest _) (funcall make 'client)))
                  ((symbol-function 'hermes-dashboard-transport-api-request-async)
                   (lambda (&rest args) (setq request args))))
          (if (equal profile "second")
              (progn
                (hermes-tool-setup-run-post-setup)
                (should confirmed)
                (should (equal (car request) "POST"))
                (should (equal (cadr request) "/api/tools/toolsets/future/post-setup"))
                (should (equal (plist-get (cddr request) :query) '((profile . "second"))))
                (should (equal (plist-get (cddr request) :body) '((key . "future-install")))))
            (should-error (hermes-tool-setup-run-post-setup) :type 'user-error)
            (should-not request)
            (should-not confirmed)
            (should-not hermes-tool-setup--busy)))))))

(ert-deftest hermes-tool-setup-install-limitation-visible-in-panel ()
  (dolist (profile '(nil "default" "second"))
    (with-temp-buffer
      (hermes-tool-setup-mode)
      (setq hermes-tool-setup--name "future"
            hermes-tool-setup--profile profile)
      (cl-letf (((symbol-function 'hermes-browser--run-on-client)
                 (lambda (_make success &rest _) (funcall success nil))))
        (hermes-tool-setup-refresh)
        (should (eq (not (null (string-match-p "Install unavailable" header-line-format)))
                    (not (equal profile "second"))))))))

(provide 'hermes-tool-setup-tests)
;;; hermes-tool-setup-tests.el ends here
