;;; hermes-mcp-tests.el --- mcp tests for hermes-el  -*- lexical-binding: t; -*-

;;; Code:

(require 'hermes-mcp)

(ert-deftest hermes-mcp-operation-start-delayed-auth-is-owned ()
  (dolist (kind '(oauth install))
    (dolist (retire '(cancel kill mode instance client))
      (with-temp-buffer
        (hermes-mcp-mode)
        (setq hermes-instance (list :id "test" :name "test" :url "http://example.test"))
        (let ((auth (hermes--promise-make))
              (client (make-hermes-dashboard-transport-client :base-url "http://example.test"))
              (released 0) writes)
          (cl-letf (((symbol-function 'hermes-browser--with-client)
                     (lambda (fn) (funcall fn client (lambda () (cl-incf released)))))
                    ((symbol-function 'hermes-dashboard-transport-api-auth-async)
                     (lambda (&rest _) auth))
                    ((symbol-function 'hermes-dashboard-transport--http-json-request-async)
                     (lambda (request)
                       (push request writes)
                       (hermes--promise-resolved '(:body (:ok t))))))
            (hermes-mcp--start-operation kind "test" nil)
            (should-not writes)
            (pcase retire
              ('cancel (hermes-mcp-cancel))
              ('kill (kill-buffer (current-buffer)))
              ('mode (fundamental-mode))
              ('instance (setq hermes-instance (copy-tree hermes-instance)))
              ('client (cl-incf (hermes-dashboard-transport-client-generation client))))
            (hermes--promise-resolve auth '(:base-url "http://example.test"))
            (should-not writes)
            (should (= released 1))))))))

(ert-deftest hermes-mcp-mutation-delayed-auth-owner-fence ()
  (dolist (retire '(live kill mode instance instance-value generation client endpoint))
    (with-temp-buffer
      (hermes-mcp-mode)
      (setq hermes-instance (list :id "test" :name "test" :url "http://example.test"))
      (let ((auth (hermes--promise-make))
            (client (make-hermes-dashboard-transport-client :base-url "http://example.test"))
            (released 0) writes)
        (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                  ((symbol-function 'hermes-browser--with-client)
                   (lambda (fn) (funcall fn client (lambda () (cl-incf released)))))
                  ((symbol-function 'hermes-dashboard-transport-api-auth-async)
                   (lambda (&rest _) auth))
                  ((symbol-function 'hermes-dashboard-transport--http-json-request-async)
                   (lambda (request)
                     (unless (equal (plist-get request :method) "GET")
                       (push request writes))
                     (hermes--promise-resolved '(:body (:ok t)))))
                  ((symbol-function 'hermes-mcp--name-at-point) (lambda () "test"))
                    ((symbol-function 'hermes-mcp--revert) #'ignore))
          (hermes-mcp-remove)
          (should-not writes)
          (pcase retire
            ('kill (kill-buffer (current-buffer)))
            ('mode (fundamental-mode))
            ('instance (setq hermes-instance (copy-tree hermes-instance)))
            ('instance-value (setf (plist-get hermes-instance :url) "http://other.test"))
            ('generation (hermes-browser--next-request-generation))
            ('client (cl-incf (hermes-dashboard-transport-client-generation client)))
            ('endpoint (setf (hermes-dashboard-transport-client-base-url client)
                             "http://other.test")))
          (hermes--promise-resolve auth '(:base-url "http://example.test"))
          (should (= (length writes) (if (eq retire 'live) 1 0)))
          (should (= released 1)))))))

(ert-deftest hermes-mcp-oauth-url-validation ()
  (should (hermes-mcp--authorization-url-p "https://auth.example/authorize?state=x"))
  (dolist (url '("javascript:alert(1)" "https://user:pass@example/a"
                 "http://example/a" "https://example/a\nInjected"))
    (should-not (hermes-mcp--authorization-url-p url))))

(ert-deftest hermes-mcp-create-closed-transport-contract ()
  (should (equal (hermes-mcp--create-body "srv" "http" "https://mcp.example" nil nil "oauth" nil)
                 '((name . "srv") (url . "https://mcp.example") (auth . "oauth"))))
  (should-error (hermes-mcp--create-body "" "http" "https://mcp.example" nil nil "none" nil))
  (should-error (hermes-mcp--create-body "srv" "stdio" "node" nil nil "oauth" nil))
  (should-error (hermes-mcp--create-body "srv" "http" "https://mcp.example" nil nil "header" "")))


(require 'ert)
(require 'hermes-test-helpers)

(ert-deftest hermes-mcp-rows-parse-read-only-server-response ()
  "MCP rows show backend name, type, enabled state, status, and tool count."
  (let ((rows (hermes-mcp--rows
               '((servers . (((name . "ctx") (transport . "stdio")
                              (enabled . t) (tool_count . 7))
                             ((name . "http-srv") (type . "http")
                              (enabled . nil) (tools . ("a" "b")))
                             ((name . "unknown") (status . "connecting"))))))))
    (should (equal (mapcar #'car rows) '("ctx" "http-srv" "unknown")))
    (should (equal (aref (cadr (car rows)) 1) "stdio"))
    (should (equal (aref (cadr (car rows)) 2) "on"))
    (should (equal (aref (cadr (car rows)) 3) "configured"))
    (should (equal (aref (cadr (car rows)) 4) "7"))
    (should (equal (aref (cadr (nth 1 rows)) 1) "http"))
    (should (equal (aref (cadr (nth 1 rows)) 2) "off"))
    (should (equal (aref (cadr (nth 1 rows)) 3) "disabled"))
    (should (equal (aref (cadr (nth 1 rows)) 4) "2"))
    (should (equal (aref (cadr (nth 2 rows)) 2) "?"))
    (should (equal (aref (cadr (nth 2 rows)) 3) "connecting"))))

(ert-deftest hermes-mcp-rows-face-every-column ()
  "MCP rows give every column its own face."
  (let* ((row (car (hermes-mcp--rows
                    '((servers . (((name . "ctx") (transport . "stdio")
                                    (enabled . t)
                                    (status . "connecting")
                                    (tool_count . 7))))))))
         (entry (cadr row)))
    (should (eq (get-text-property 0 'face (aref entry 0))
                'hermes-browser-name))
    (should (eq (get-text-property 0 'face (aref entry 1))
                'hermes-browser-type))
    (should (equal (get-text-property 0 'face (aref entry 2))
                   '(hermes-browser-success hermes-browser-enabled)))
    (should (equal (get-text-property 0 'face (aref entry 3))
                   '(hermes-browser-pending hermes-browser-status)))
    (should (eq (get-text-property 0 'face (aref entry 4))
                'hermes-browser-tool-count))))

(ert-deftest hermes-mcp-rows-redact-secret-shaped-display-values ()
  "MCP row display cells do not leak secret-shaped backend values."
  (let* ((secret "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
         (rows (hermes-mcp--rows
                `((servers . (((name . ,(concat "srv-" secret))
                               (transport . "stdio")
                               (enabled . t)
                               (status . ,(concat "failed token=" secret))
                               (tool_count . 1)))))))
         (entry (cadr (car rows)))
         (display (string-join (mapcar (lambda (cell) (format "%s" cell))
                                       (append entry nil))
                               " ")))
    (should-not (string-match-p (regexp-quote secret) display))
    (should (string-match-p "<redacted>" display))))

(ert-deftest hermes-mcp-redacts-whitespace-secret-flags ()
  "MCP display redaction covers token flags whose value follows whitespace."
  (dolist (flag '("--token" "--api-key"))
    (let* ((secret "short-secret-value")
           (redacted (hermes-mcp--redact-display
                      (format "failed: %s %s" flag secret))))
      (should-not (string-match-p (regexp-quote secret) redacted))
      (should (string-match-p (concat (regexp-quote flag) " <redacted>")
                              redacted)))))

(ert-deftest hermes-mcp-revert-refreshes-without-display ()
  "Reverting the MCP list refreshes rows in place; the command displays."
  (let (displayed)
    (cl-letf (((symbol-function 'hermes-browser--run-on-client)
               (lambda (make-promise &optional on-success _on-error)
                 (let ((p (funcall make-promise 'fake-client)))
                   (if on-success (hermes--promise-then p on-success) p))))
              ((symbol-function 'hermes-mcp--api)
               (lambda (&rest _)
                 (hermes--promise-resolved
                  '((servers . (((name . "ctx") (transport . "stdio")
                                 (enabled . t) (tool_count . 0))))))))
              ((symbol-function 'pop-to-buffer)
               (lambda (&rest _) (setq displayed t))))
      (unwind-protect
          (progn
            (with-current-buffer (get-buffer-create hermes-mcp-buffer-name)
              (hermes-mcp-mode)
              (hermes-mcp--revert))
            (should-not displayed)
            (with-current-buffer hermes-mcp-buffer-name
              (should (equal (mapcar #'car tabulated-list-entries) '("ctx"))))
            (hermes-list-mcp)
            (should displayed))
        (when (get-buffer hermes-mcp-buffer-name)
          (kill-buffer hermes-mcp-buffer-name))))))

(ert-deftest hermes-mcp-list-pins-resolved-instance ()
  "The MCP browser owns the instance selected for its initial fetch."
  (let ((instance '("remote" . "https://hermes.example.test")))
    (cl-letf (((symbol-function 'hermes-instance-resolve)
               (lambda () instance))
              ((symbol-function 'hermes-browser--run-on-client)
               (lambda (make-promise &optional on-success _on-error)
                 (hermes--promise-then
                  (funcall make-promise 'fake-client) on-success)))
              ((symbol-function 'hermes-mcp--api)
               (lambda (&rest _)
                 (hermes--promise-resolved '((servers . nil))))))
      (unwind-protect
          (progn
            (hermes-list-mcp)
            (with-current-buffer hermes-mcp-buffer-name
              (should (equal hermes-instance instance))))
        (when (get-buffer hermes-mcp-buffer-name)
          (kill-buffer hermes-mcp-buffer-name))))))

(ert-deftest hermes-mcp-revert-does-not-resurrect-killed-buffer ()
  "A late MCP refresh does not recreate its killed buffer."
  (let ((promise (hermes--promise-make)))
    (cl-letf (((symbol-function 'hermes-browser--run-on-client)
               (lambda (make-promise &optional on-success _on-error)
                 (hermes--promise-then (funcall make-promise 'fake-client)
                                       on-success)))
              ((symbol-function 'hermes-mcp--api) (lambda (&rest _) promise)))
      (with-current-buffer (get-buffer-create hermes-mcp-buffer-name)
        (hermes-mcp-mode)
        (hermes-mcp--revert))
      (kill-buffer hermes-mcp-buffer-name)
      (hermes--promise-resolve promise '((servers . nil)))
      (should-not (get-buffer hermes-mcp-buffer-name)))))

(ert-deftest hermes-mcp-revert-keeps-newest-result ()
  "An older MCP refresh cannot overwrite a newer result."
  (let ((first (hermes--promise-make))
        (second (hermes--promise-make))
        (requests 0))
    (cl-letf (((symbol-function 'hermes-browser--run-on-client)
               (lambda (make-promise &optional on-success _on-error)
                 (hermes--promise-then (funcall make-promise 'fake-client)
                                       on-success)))
              ((symbol-function 'hermes-mcp--api)
               (lambda (&rest _)
                 (setq requests (1+ requests))
                 (if (= requests 1) first second))))
      (unwind-protect
          (progn
            (with-current-buffer (get-buffer-create hermes-mcp-buffer-name)
              (hermes-mcp-mode)
              (hermes-mcp--revert)
              (hermes-mcp--revert))
            (hermes--promise-resolve
             second '((servers . (((name . "new") (enabled . t))))))
            (hermes--promise-resolve
             first '((servers . (((name . "old") (enabled . t))))))
            (with-current-buffer hermes-mcp-buffer-name
              (should (equal (mapcar #'car tabulated-list-entries) '("new")))))
        (when (get-buffer hermes-mcp-buffer-name)
          (kill-buffer hermes-mcp-buffer-name))))))

(ert-deftest hermes-mcp-test-and-toggle-dispatch-rest-actions ()
  "Testing and toggling dispatch to MCP dashboard REST endpoints."
  (let (calls messages)
    (cl-letf (((symbol-function 'hermes-browser--run-on-client)
               (lambda (make-promise &optional on-success _on-error)
                 (let ((p (funcall make-promise 'fake-client)))
                   (if on-success (hermes--promise-then p on-success) p))))
              ((symbol-function 'hermes-mcp--api)
               (lambda (method path &optional body query &rest _args)
                 (push (list method path body query) calls)
                 (hermes--promise-resolved (cond
					    ((equal path "/servers")
					     '((servers . (((name . "ctx") (transport . "stdio")
							    (enabled . t) (tool_count . 0))))))
					    ((equal path "/servers/ctx/test")
					     '((ok . t) (tools . (((name . "read")
								   (description . "Read"))))))
					    ((equal path "/servers/ctx/enabled")
					     (should (equal body '((enabled . :false))))
					     '((ok . t) (name . "ctx") (enabled . nil)))
					    (t (error "unexpected MCP API call %S" path))))))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (push (apply #'format format-string args) messages))))
      (unwind-protect
          (progn
            (hermes-list-mcp)
            (with-current-buffer "*Hermes MCP Servers*"
              (should (derived-mode-p 'hermes-mcp-mode))
              (should (eq (keymap-lookup hermes-mcp-mode-map "RET")
                          #'hermes-mcp-test))
              (should (eq (keymap-lookup hermes-mcp-mode-map "e")
                          #'hermes-mcp-toggle))
              (should (equal (caar tabulated-list-entries) "ctx"))
              (goto-char (point-min))
              (hermes-mcp-test)
              (should (equal (hermes-mcp--test-tool-count "ctx") "1"))
              (should (equal (aref (cadr (car tabulated-list-entries)) 3)
                             "ok"))
              (should (equal (aref (cadr (car tabulated-list-entries)) 4)
                             "1"))
              (goto-char (point-min))
              (hermes-mcp-toggle))
            (should (member '("POST" "/servers/ctx/test" nil nil) calls))
            (should (member '("PUT" "/servers/ctx/enabled"
                              ((enabled . :false)) nil)
                            calls))
            (should (= (cl-count-if (lambda (call)
                                      (equal (cadr call) "/servers"))
                                    calls)
                       3))
            (should (cl-some (lambda (message)
                               (string-match-p "ctx has 1 MCP tool" message))
                             messages))
            (should (cl-some (lambda (message)
                               (string-match-p "disabled ctx" message))
                             messages)))
        (when (get-buffer "*Hermes MCP Servers*")
          (kill-buffer "*Hermes MCP Servers*"))))))

(ert-deftest hermes-mcp-toggle-refreshes-after-newer-read ()
  "A completed MCP toggle starts a fresh authoritative read."
  (let ((put (hermes--promise-make)) refreshed)
    (cl-letf (((symbol-function 'hermes-browser--run-on-client)
               (lambda (make-promise &optional on-success _on-error)
                 (hermes--promise-then (funcall make-promise 'client) on-success)))
              ((symbol-function 'hermes-mcp--api)
               (lambda (method _path &rest _)
                 (if (equal method "PUT")
                     put
                   (error "The stale mutation chain must not own the refresh"))))
              ((symbol-function 'hermes-mcp--revert)
               (lambda (&rest _) (setq refreshed (current-buffer))))
              ((symbol-function 'message) #'ignore))
      (with-temp-buffer
        (hermes-mcp-mode)
        (hermes-mcp--ensure-state)
        (puthash "ctx" '((name . "ctx") (enabled . t)) hermes-mcp--servers)
        (setq tabulated-list-entries '(("ctx" ["ctx" "stdio" "on" "ok" "1"])))
        (tabulated-list-print)
        (goto-char (point-min))
        (let ((origin (current-buffer)))
          (hermes-mcp-toggle)
          (hermes--promise-resolve put '((ok . t)))
          (should (eq refreshed origin)))))))

(ert-deftest hermes-mcp-toggle-stale-success-does-not-report-or-refresh ()
  "A late MCP toggle cannot report success or refresh a retargeted buffer."
  (let ((put (hermes--promise-make)) messages refreshed)
    (cl-letf (((symbol-function 'hermes-browser--run-on-client)
               (lambda (make-promise &optional on-success _on-error)
                 (hermes--promise-then (funcall make-promise 'client) on-success)))
              ((symbol-function 'hermes-mcp--api)
               (lambda (method _path &rest _)
                 (if (equal method "PUT")
                     put
                   (error "A stale toggle must not start a new API read"))))
              ((symbol-function 'hermes-mcp--revert)
               (lambda (&rest _) (setq refreshed t)))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (push (apply #'format format-string args) messages))))
      (with-temp-buffer
        (hermes-mcp-mode)
        (hermes-mcp--ensure-state)
        (puthash "ctx" '((name . "ctx") (enabled . t)) hermes-mcp--servers)
        (setq tabulated-list-entries '(("ctx" ["ctx" "stdio" "on" "ok" "1"])))
        (tabulated-list-print)
        (goto-char (point-min))
        (hermes-mcp-toggle)
        (hermes-browser--next-request-generation)
        (hermes--promise-resolve put '((ok . t)))
        (should-not refreshed)
        (should-not (cl-find-if (lambda (text)
                                  (string-match-p "enabled\\|disabled" text))
                                messages))))))

(ert-deftest hermes-mcp-test-failure-message-redacts-secret ()
  "MCP test failure messages redact secret-shaped backend errors."
  (let ((secret "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
        messages)
    (cl-letf (((symbol-function 'hermes-browser--run-on-client)
               (lambda (make-promise &optional on-success _on-error)
                 (let ((p (funcall make-promise 'fake-client)))
                   (if on-success (hermes--promise-then p on-success) p))))
              ((symbol-function 'hermes-mcp--api)
               (lambda (_method path &optional _body _query &rest _args)
                 (hermes--promise-resolved (cond
					    ((equal path "/servers")
					     '((servers . (((name . "ctx") (transport . "stdio")
							    (enabled . t))))))
					    ((equal path "/servers/ctx/test")
					     `((ok . nil) (error . ,(concat "failed token=" secret))
					       (tools . nil)))
					    (t (error "unexpected MCP API call %S" path))))))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (push (apply #'format format-string args) messages))))
      (unwind-protect
          (progn
            (hermes-list-mcp)
            (with-current-buffer "*Hermes MCP Servers*"
              (goto-char (point-min))
              (hermes-mcp-test))
            (let ((joined (string-join messages "\n")))
              (should-not (string-match-p (regexp-quote secret) joined))
              (should (string-match-p "test failed" joined))
              (should (string-match-p "<redacted>" joined))))
        (when (get-buffer "*Hermes MCP Servers*")
          (kill-buffer "*Hermes MCP Servers*"))))))

(ert-deftest hermes-mcp-action-reports-unsupported-backend ()
  "MCP actions surface unsupported REST backends as a Hermes message."
  (let (called messages)
    (cl-letf (((symbol-function 'hermes-browser--run-on-client)
               (lambda (make-promise &optional on-success _on-error)
                 (hermes--promise-catch
                  (hermes--promise-then (funcall make-promise 'fake-client)
                                        on-success)
                  (lambda (m) (message "Hermes: %s" m)))))
              ((symbol-function 'hermes-dashboard-transport-api-request-async)
               (lambda (method path &rest _args)
                 (setq called (list method path))
                 (hermes--promise-rejected
                  "Hermes dashboard request failed at /api/mcp/servers/ctx/test (HTTP 404)")))
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (push (apply #'format format-string args) messages))))
      (unwind-protect
          (progn
            (hermes-mcp--render
             '((servers . (((name . "ctx") (transport . "stdio")
                            (enabled . t))))))
            (with-current-buffer "*Hermes MCP Servers*"
              (goto-char (point-min))
              (hermes-mcp-test))
            (should (equal called '("POST" "/api/mcp/servers/ctx/test")))
            (should (cl-some (lambda (m)
                               (string-match-p "MCP REST API is unavailable" m))
                             messages)))
        (when (get-buffer "*Hermes MCP Servers*")
          (kill-buffer "*Hermes MCP Servers*"))))))

(ert-deftest hermes-mcp-api-uses-live-client-session-token ()
  "MCP REST requests use a live dashboard client's session token when present."
  (let ((client (make-hermes-dashboard-transport-client
                 :host "127.0.0.1" :port 32123 :token "session-token"))
        seen-url seen-method seen-headers seen-secrets result)
    (cl-letf (((symbol-function 'hermes-dashboard-transport--http-json-async)
               (cl-function
                (lambda (url &key method headers body secrets)
                  (ignore body)
                  (setq seen-url url
                        seen-method method
                        seen-headers headers
                        seen-secrets secrets)
                  (hermes--promise-resolved '(:body ((servers . nil))))))))
      (hermes--promise-then
       (hermes-mcp--api "GET" "/servers" nil '((profile . "work")) :client client)
       (lambda (body) (setq result body)))
      (should (equal result '((servers . nil))))
      (should (equal seen-method "GET"))
      (should (string-match-p (regexp-quote "/api/mcp/servers?profile=work")
                              seen-url))
      (should (equal (cdr (assoc "X-Hermes-Session-Token" seen-headers))
                     "session-token"))
      (should (member "session-token" seen-secrets)))))

(ert-deftest hermes-mcp-api-redacts-secret-shaped-errors ()
  "MCP API errors do not leak token, ticket, internal, or env secrets."
  (let ((secret "sk-test-secret") reason)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-api-request-async)
               (lambda (_method _path &rest args)
                 (hermes--promise-rejected
                  (hermes-dashboard-transport--redact-secret
                   (format "bad token=%s env SECRET=%s" secret secret)
                   (plist-get args :secrets))))))
      (hermes--promise-catch
       (hermes-mcp--api "GET" "/servers" nil nil :secrets (list secret))
       (lambda (r) (setq reason r)))
      (should reason)
      (should-not (string-match-p (regexp-quote secret) reason))
      (should (string-match-p "<redacted>" reason)))))

(ert-deftest hermes-mcp-api-reports-unsupported-backend ()
  "A missing MCP REST endpoint is reported as an unsupported backend."
  (let (reason)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-api-request-async)
               (lambda (&rest _)
                 (hermes--promise-rejected
                  "Hermes dashboard request failed at /api/mcp/servers (HTTP 404)"))))
      (hermes--promise-catch
       (hermes-mcp--api "GET" "/servers")
       (lambda (r) (setq reason r)))
      (should (string-match-p "MCP REST API is unavailable" reason)))))

(defmacro hermes-mcp-test--operation (&rest body)
  "Run BODY with isolated operation resources and captured async requests."
  (declare (indent 0))
  `(let (requests timers cancelled opened messages (released 0) (refreshed 0))
     (cl-letf (((symbol-function 'hermes-browser--with-client)
                (lambda (fn) (funcall fn 'exact-client (lambda () (cl-incf released)))))
               ((symbol-function 'hermes-mcp--api)
                (lambda (method path &optional payload query &rest keys)
                  (let ((promise (hermes--promise-make)))
                    (push (list method path payload query keys promise) requests)
                    promise)))
               ((symbol-function 'run-at-time)
                (lambda (&rest args) (let ((timer (copy-sequence args)))
                                      (push timer timers) timer)))
               ((symbol-function 'cancel-timer) (lambda (timer) (push timer cancelled)))
               ((symbol-function 'browse-url) (lambda (url &rest _) (push url opened)))
               ((symbol-function 'message)
                (lambda (fmt &rest args) (push (apply #'format fmt args) messages)))
               ((symbol-function 'hermes-mcp--revert) (lambda (&rest _) (cl-incf refreshed))))
       (with-temp-buffer
         (hermes-mcp-mode)
         (setq-local hermes-instance '("test" . "https://backend.example"))
         ,@body))))

(defun hermes-mcp-test--resolve (request body)
  "Resolve captured REQUEST with BODY."
  (hermes--promise-resolve (nth 5 request) body))

(ert-deftest hermes-mcp-oauth-browser-poll-and-completion ()
  (hermes-mcp-test--operation
    (hermes-mcp--start-operation 'oauth "srv" nil)
    (let ((operation hermes-mcp--operation))
      (should (equal (cadr (car requests)) "/servers/srv/auth"))
      (should (eq (plist-get (nth 4 (car requests)) :client) 'exact-client))
      (hermes-mcp-test--resolve
       (car requests) '((flow_id . "flow-1") (server_name . "srv")
                        (status . "authorization_required")
                        (authorization_url . "https://auth.example/authorize?state=secret")))
      (should (= (length opened) 1))
      (should (= released 0))
      (hermes-mcp--poll operation)
      (should (equal (cadr (car requests)) "/oauth/flows/flow-1"))
      (hermes-mcp-test--resolve
       (car requests) '((flow_id . "flow-1") (server_name . "srv") (status . "approved")))
      (should-not hermes-mcp--operation)
      (should (= released 1))
      (should (= refreshed 1))
      (should (= (length cancelled) 2))
      (should-not (string-match-p "secret" (format "%s" messages))))))

(ert-deftest hermes-mcp-oauth-cancel-before-start-cleans-late-flow ()
  (hermes-mcp-test--operation
    (hermes-mcp--start-operation 'oauth "srv" nil)
    (let ((request (car requests)))
      (hermes-mcp-cancel)
      (should (= released 1))
      (hermes-mcp-test--resolve
       request '((flow_id . "late-flow") (server_name . "srv")
                 (status . "authorization_required")
                 (authorization_url . "https://auth.example/authorize?state=secret")))
      (should (equal (cl-subseq (car requests) 0 2) '("DELETE" "/oauth/flows/late-flow")))
      (should (eq (plist-get (nth 4 (car requests)) :client) 'exact-client))
      (should-not opened)
      (should (= released 1))
      (should (= refreshed 0)))))

(ert-deftest hermes-mcp-oauth-mode-exit-and-stale-poll ()
  (hermes-mcp-test--operation
    (hermes-mcp--start-operation 'oauth "srv" nil)
    (let ((operation hermes-mcp--operation))
      (hermes-mcp-test--resolve
       (car requests) '((flow_id . "flow") (server_name . "srv") (status . "starting")))
      (hermes-mcp--poll operation)
      (let ((poll (car requests)))
        (fundamental-mode)
        (should (= released 1))
        (should (equal (cl-subseq (car requests) 0 2) '("DELETE" "/oauth/flows/flow")))
        (hermes-mcp-test--resolve
         poll '((flow_id . "flow") (server_name . "srv") (status . "approved")))
        (should (= refreshed 0))
        (should-not opened)
        (should (= released 1))))))

(ert-deftest hermes-mcp-oauth-rejects-mismatch-and-browser-failure ()
  (dolist (failure '(identity browser url rejection timeout))
    (hermes-mcp-test--operation
      (hermes-mcp--start-operation 'oauth "srv" nil)
      (let ((operation hermes-mcp--operation))
        (cond
         ((eq failure 'rejection)
          (hermes--promise-reject (nth 5 (car requests)) "password-is-short"))
         ((eq failure 'timeout) (hermes-mcp--operation-failed operation))
         (t
          (cl-letf (((symbol-function 'browse-url)
                     (lambda (&rest _) (error "password-is-short"))))
            (hermes-mcp-test--resolve
             (car requests)
             `((flow_id . "flow") (server_name . ,(if (eq failure 'identity) "other" "srv"))
               (status . "authorization_required")
               (authorization_url . ,(if (eq failure 'url) "file:///secret"
                                      "https://auth.example/authorize?state=x")))))))
        (should-not hermes-mcp--operation)
        (should (= released 1))
        (should (= refreshed 0))
        (should-not (string-match-p "password-is-short" (format "%s" messages)))))))

(ert-deftest hermes-mcp-instance-change-invalidates-operation ()
  (hermes-mcp-test--operation
    (hermes-mcp--start-operation 'oauth "srv" nil)
    (setq-local hermes-instance '("other" . "https://other.example"))
    (hermes-mcp-test--resolve
     (car requests) '((flow_id . "flow") (server_name . "srv") (status . "approved")))
    (should-not opened)
    (should (= refreshed 0))
    (should (equal (cl-subseq (car requests) 0 2) '("DELETE" "/oauth/flows/flow")))))

(ert-deftest hermes-mcp-install-background-is-not-completion ()
  (hermes-mcp-test--operation
    (hermes-mcp--start-operation 'install "catalog" '(("API_KEY" . "short-secret")))
    (let ((operation hermes-mcp--operation) status-request)
      (should (equal (nth 2 (car requests))
                     '((name . "catalog") (enable . t) (env . (("API_KEY" . "short-secret"))))))
      (should (equal (plist-get (nth 4 (car requests)) :secrets) '("short-secret")))
      (hermes-mcp-test--resolve
       (car requests) '((ok . t) (background . t) (action . "mcp-install-catalog-123")))
      (should (= refreshed 0))
      (cl-letf (((symbol-function 'hermes-dashboard-transport-api-request-async)
                 (lambda (method path &rest keys)
                   (should (equal method "GET"))
                   (should (equal path "/api/actions/mcp-install-catalog-123/status"))
                   (should (eq (plist-get keys :client) 'exact-client))
                   (setq status-request (hermes--promise-make)))))
        (hermes-mcp--poll operation)
        (hermes--promise-resolve status-request '((running . t) (exit_code . nil)))
        (should (= refreshed 0))
        (hermes-mcp--poll operation)
        (hermes--promise-resolve status-request '((running . :false) (exit_code . 0)))
        (should (string-match-p "entry action succeeded.*shared handle" (car messages)))
        (should (= refreshed 1))
        (should (= released 1))))))

(ert-deftest hermes-mcp-catalog-credentials-closed-and-required ()
  (let ((entry '((required_env . (((name . "DECLARED") (required . t)))))))
    (cl-letf (((symbol-function 'read-passwd) (lambda (&rest _) "secret")))
      (should (equal (hermes-mcp--catalog-env entry) '(("DECLARED" . "secret")))))
    (cl-letf (((symbol-function 'read-passwd) (lambda (&rest _) "")))
      (should-error (hermes-mcp--catalog-env entry)))))

(ert-deftest hermes-mcp-remove-confirmation-and-stale-owner ()
  (dolist (answer '(nil t switch))
    (let (calls)
      (cl-letf (((symbol-function 'hermes-mcp--name-at-point) (lambda () "name with spaces"))
                 ((symbol-function 'yes-or-no-p)
                  (lambda (&rest _)
                    (when (eq answer 'switch) (setq-local hermes-instance '("new" . "https://new.example")))
                    answer))
                 ((symbol-function 'hermes-mcp--request)
                  (lambda (_context request _success) (funcall request 'exact-client)))
                 ((symbol-function 'hermes-mcp--api)
                  (lambda (&rest args) (push args calls))))
        (with-temp-buffer
          (hermes-mcp-mode)
          (setq-local hermes-instance '("old" . "https://old.example"))
          (hermes-mcp-remove)
          (if (eq answer t)
              (should (equal (cl-subseq (car calls) 0 2) '("DELETE" "/servers/name%20with%20spaces")))
            (should-not calls)))))))

(ert-deftest hermes-mcp-stale-test-cannot-start-followup-read ()
  (let ((promise (hermes--promise-make)) calls)
    (cl-letf (((symbol-function 'hermes-browser--run-on-client)
               (lambda (request success &optional failure)
                 (hermes--promise-catch (hermes--promise-then (funcall request 'client) success) failure)))
              ((symbol-function 'hermes-mcp--api)
               (lambda (&rest args) (push args calls) promise))
              ((symbol-function 'hermes-mcp--name-at-point) (lambda () "srv")))
      (with-temp-buffer
        (hermes-mcp-mode)
        (hermes-mcp-test)
        (hermes-browser--next-request-generation)
        (hermes--promise-resolve promise '((ok . t) (tools . nil)))
        (should (= (length calls) 1))
        (should (= (hash-table-count hermes-mcp--test-results) 0))))))

(ert-deftest hermes-mcp-management-keymap-is-native ()
  (dolist (pair '(("a" . hermes-mcp-add) ("d" . hermes-mcp-remove)
                  ("c" . hermes-mcp-catalog) ("o" . hermes-mcp-authenticate)
                  ("k" . hermes-mcp-cancel)))
    (should (eq (keymap-lookup hermes-mcp-mode-map (car pair)) (cdr pair)))))

(ert-deftest hermes-mcp-add-http-secret-request-and-readback ()
  (let ((texts '("new" "https://mcp.example/mcp"))
        (choices '("http" "header")) calls (refreshed 0))
    (cl-letf (((symbol-function 'read-string) (lambda (&rest _) (pop texts)))
              ((symbol-function 'completing-read) (lambda (&rest _) (pop choices)))
              ((symbol-function 'read-passwd) (lambda (&rest _) "short-secret"))
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
              ((symbol-function 'hermes-browser--with-client)
               (lambda (fn) (funcall fn 'exact-client #'ignore)))
              ((symbol-function 'hermes-mcp--api)
               (lambda (&rest args)
                 (push args calls) (hermes--promise-resolved '((name . "new")))))
              ((symbol-function 'hermes-mcp--revert) (lambda (&rest _) (cl-incf refreshed))))
      (with-temp-buffer
        (hermes-mcp-mode)
        (hermes-mcp-add)
        (should (equal (cl-subseq (car calls) 0 3)
                       '("POST" "/servers" ((name . "new") (url . "https://mcp.example/mcp")
                                             (auth . "header") (bearer_token . "short-secret")))))
        (should (equal (plist-get (nthcdr 4 (car calls)) :secrets) '("short-secret")))
        (should (= refreshed 1))))))

(ert-deftest hermes-mcp-catalog-journey-reviews-before-install ()
  (let ((entry '((name . "catalog") (source . "official")
                 (command . "node") (args . ("server.js"))
                 (install_url) (bootstrap)))
        reviewed installed)
    (cl-letf (((symbol-function 'hermes-browser--with-client)
               (lambda (fn) (funcall fn 'exact-client #'ignore)))
              ((symbol-function 'hermes-mcp--api)
               (lambda (method path &rest _)
                 (should (equal (list method path) '("GET" "/catalog")))
                 (hermes--promise-resolved `((entries . (,entry))))))
              ((symbol-function 'completing-read) (lambda (&rest _) "catalog"))
              ((symbol-function 'hermes-mcp--catalog-review)
               (lambda (value) (setq reviewed value)))
              ((symbol-function 'yes-or-no-p)
               (lambda (&rest _) (should (equal reviewed entry)) t))
              ((symbol-function 'hermes-mcp--start-operation)
               (lambda (kind name env) (setq installed (list kind name env)))))
      (with-temp-buffer
        (hermes-mcp-mode)
        (hermes-mcp-catalog)
        (should (equal installed '(install "catalog" nil)))))))

(ert-deftest hermes-mcp-catalog-blocks-unproven-bootstrap-before-secrets ()
  "Root dashboard with different sticky profile must never dispatch bootstrap.
The released catalog response exposes no child profile-preservation proof;
named dashboards are indistinguishable here and must also fail closed."
  (dolist (install-fields '(((install_url . "https://example/repo") (bootstrap . ("build")))
                            ((install_url . "https://example/repo") (bootstrap))
                            ((bootstrap . ("build")))
                            nil))
    (hermes-mcp-test--operation
      (let ((entry (append '((name . "catalog")
                            (required_env . (((name . "API_KEY") (required . t)))))
                          install-fields))
            prompted)
        (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "catalog"))
                  ((symbol-function 'hermes-mcp--catalog-review) #'ignore)
                  ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                  ((symbol-function 'read-passwd)
                   (lambda (&rest _) (setq prompted t) "short-secret")))
          (hermes-mcp-catalog)
          (hermes-mcp-test--resolve (car requests) `((entries . (,entry))))
          (should-not prompted)
          (should (= (length requests) 1))
          (should (equal (cl-subseq (car requests) 0 2) '("GET" "/catalog")))
          (should-not hermes-mcp--operation)
          (should (string-match-p "profile.*cannot be guaranteed" (format "%s" messages))))))))

(ert-deftest hermes-mcp-catalog-nonbootstrap-keeps-dashboard-scope ()
  "In-process catalog installs retain dashboard authority and declared secrets."
  (hermes-mcp-test--operation
    (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "catalog"))
              ((symbol-function 'hermes-mcp--catalog-review) #'ignore)
              ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
              ((symbol-function 'read-passwd) (lambda (&rest _) "short-secret")))
      (hermes-mcp-catalog)
      (hermes-mcp-test--resolve
       (car requests) '((entries . (((name . "catalog") (install_url) (bootstrap)
                                    (required_env . (((name . "API_KEY") (required . t)))))))))
      (should (= (length requests) 2))
      (should (equal (cl-subseq (car requests) 0 4)
                     '("POST" "/catalog/install"
                       ((name . "catalog") (enable . t) (env . (("API_KEY" . "short-secret")))) nil)))
      (should (eq (plist-get (nth 4 (car requests)) :client) 'exact-client))
      (hermes-mcp-test--resolve (car requests) '((ok . t) (background . :false)))
      (should (= refreshed 1))
      (should-not hermes-mcp--operation))))

(ert-deftest hermes-mcp-catalog-review-displays-execution-details ()
  (let ((before (buffer-list)))
    (unwind-protect
        (save-window-excursion
          (hermes-mcp--catalog-review
           '((name . "catalog") (command . "node") (args . ("server.js"))
             (install_url . "https://example/repo") (bootstrap . ("build"))))
          (let ((buffer (cl-find-if (lambda (b) (not (memq b before))) (buffer-list))))
            (should buffer)
            (with-current-buffer buffer
              (should (derived-mode-p 'help-mode))
              (should (string-match-p "server.js" (buffer-string)))
              (should (string-match-p "build" (buffer-string))))))
      (dolist (buffer (buffer-list))
        (unless (memq buffer before) (kill-buffer buffer))))))

(ert-deftest hermes-mcp-request-rejection-is-quiet-when-stale ()
  (let ((promise (hermes--promise-make)) messages)
    (cl-letf (((symbol-function 'hermes-browser--with-client)
               (lambda (fn) (funcall fn 'exact-client #'ignore)))
              ((symbol-function 'message)
               (lambda (fmt &rest args) (push (apply #'format fmt args) messages))))
      (with-temp-buffer
        (hermes-mcp-mode)
        (hermes-mcp--request (hermes-mcp--context) (lambda (_client) promise) #'ignore)
        (hermes-browser--next-request-generation)
        (hermes--promise-reject promise "arbitrary short secret")
        (should-not messages)))))

(ert-deftest hermes-mcp-client-acquisition-cannot-transfer-authority ()
  (let ((released 0) calls)
    (cl-letf (((symbol-function 'hermes-browser--with-client)
               (lambda (fn)
                 (hermes-browser--next-request-generation)
                 (funcall fn 'client (lambda () (cl-incf released)))))
              ((symbol-function 'hermes-mcp--api)
               (lambda (&rest _) (setq calls t))))
      (with-temp-buffer
        (hermes-mcp-mode)
        (hermes-mcp--start-operation 'oauth "srv" nil)
        (should-not calls)
        (should-not hermes-mcp--operation)
        (should (= released 1))))))

(provide 'hermes-mcp-tests)
;;; hermes-mcp-tests.el ends here
