;;; hermes-files-tests.el --- Managed file browser tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'hermes-test-helpers)
(require 'hermes-files)

(ert-deftest hermes-files-public-command ()
  (should (commandp 'hermes-files))
  (should (eq (lookup-key hermes-dashboard-mode-map (kbd "O")) 'hermes-files)))

(defmacro hermes-files-test--with-api (&rest body)
  (declare (indent 0))
  `(let* ((instance '("Files test" . "http://files.invalid"))
          (hermes-instances (list instance))
          (hermes-instance instance)
          (hermes-dashboard-transport--clients (make-hash-table :test #'equal))
          (hermes-dashboard-transport-idle-close-delay 0)
          (client (make-hermes-dashboard-transport-client
                   :base-url (cdr instance)))
          (release (symbol-function 'hermes-dashboard-transport-release))
          (releases 0) calls buffers)
     (save-window-excursion
       (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
                  (lambda (&rest _) client))
                 ((symbol-function 'hermes-dashboard-transport-release)
                  (lambda (owner) (cl-incf releases) (funcall release owner)))
                 ((symbol-function 'hermes-dashboard-transport-api-request-async)
                  (lambda (method path &rest args)
                    (let ((promise (hermes--promise-make)))
                      (push (list method path args promise) calls)
                      promise))))
         (unwind-protect (progn ,@body)
           (dolist (buffer buffers)
             (when (buffer-live-p buffer) (kill-buffer buffer))))))))

(defun hermes-files-test--routing-during-request (legacy)
  "Check event delivery across a public Files request, using LEGACY routing."
  (hermes-files-test--with-api
    (let (events)
      (if legacy
          (setf (hermes-dashboard-transport-client-callback client)
                (lambda (event) (push event events)))
        (hermes-dashboard-transport-subscribe
         client (lambda (event) (push event events))))
      (cl-flet ((dispatch (phase)
                  (hermes-dashboard-transport--dispatch-event
                   client (if legacy
                              (list :type 'status :status phase)
                            (list :type 'delta :session-id "new-session"
                                  :content phase)))))
        (dispatch "before")
        (call-interactively #'hermes-files)
        (push (current-buffer) buffers)
        (should (equal (cadar calls) "/api/files"))
        (should (equal hermes-files--status "Loading"))
        (dispatch "during")
        (hermes--promise-resolve (nth 3 (car calls))
                                (hermes-files-test--listing))
        (should (equal hermes-files--status "Ready"))
        (should-not hermes-files--subscription)
        (dispatch "after")
        (should (equal (mapcar (lambda (event)
                                (plist-get event (if legacy :status :content)))
                              (reverse events))
                       '("before" "during" "after")))))))

(ert-deftest hermes-files-observation-preserves-bootstrap-routing ()
  (hermes-files-test--routing-during-request nil))

(ert-deftest hermes-files-observation-preserves-legacy-routing ()
  (hermes-files-test--routing-during-request t))

(ert-deftest hermes-files-observation-has-no-session-ownership ()
  (hermes-files-test--with-api
    (let* (events
           (token (hermes-dashboard-transport-subscribe
                   client (lambda (event) (push event events)))))
      (hermes-dashboard-transport-subscribe-session client token "chat")
      (call-interactively #'hermes-files)
      (push (current-buffer) buffers)
      (should-error (hermes-dashboard-transport-subscribe-session
                     client hermes-files--subscription "chat"))
      (dolist (event '((:type status :status "Ready")
                       (:type delta :session-id "chat" :content "reply")))
        (hermes-dashboard-transport--dispatch-event client event))
      (should (= 2 (length events)))
      (hermes-dashboard-transport-set-subscriber-fn client token nil)
      (should-not (gethash "chat" (hermes-dashboard-transport-client-session-index
                                 client)))
      (should-not (hermes-dashboard-transport--event-subscribers client))
      (setf (hermes-dashboard-transport-client-callback client)
            (lambda (event) (push event events)))
      (hermes-dashboard-transport--dispatch-event
       client '(:type delta :session-id "chat" :content "legacy"))
      (should (= 3 (length events))))))

(ert-deftest hermes-files-navigation-and-stale-refresh ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (should (equal (caar calls) "GET"))
    (should (equal (cadar calls) "/api/files"))
    (hermes--promise-resolve (nth 3 (car calls))
                            '(:path "/remote" :parent "/" :entries
                              ((:name "child" :path "/remote/a & b" :is_directory t))))
    (goto-char (point-min))
    (call-interactively (key-binding (kbd "RET")))
    (should (equal (plist-get (nth 2 (car calls)) :query)
                   '((path . "/remote/a & b"))))
    (let ((old (nth 3 (car calls))))
      (call-interactively (key-binding (kbd "g")))
      (hermes--promise-resolve (nth 3 (car calls))
                              '(:path "/remote/a & b" :parent "/remote" :entries nil))
      (hermes--promise-resolve old '(:path "/wrong" :entries nil))
      (should (equal hermes-files--path "/remote/a & b"))
      (call-interactively (key-binding (kbd "^")))
      (should (equal (plist-get (nth 2 (car calls)) :query)
                     '((path . "/remote")))))))

(defun hermes-files-test--listing (&optional count)
  (list :path "/remote" :parent nil :entries
        (cl-loop for i below (or count 1) collect
                 (list :name (format "file%d.el" i)
                       :path (format "/remote/file%d.el" i)
                       :is_directory :false :size 3))))

(defun hermes-files-test--read ()
  '(:path "/remote/file0.el" :size 3 :data_url "data:application/octet-stream;base64,AP9B"))

(ert-deftest hermes-files-read-is-inert-and-does-not-steal-focus ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
    (goto-char (point-min))
    (call-interactively (key-binding (kbd "RET")))
    (push (current-buffer) buffers)
    (let ((viewer (current-buffer)) (request (nth 3 (car calls)))
          (other (generate-new-buffer " *typing*")))
      (push other buffers)
      (switch-to-buffer other)
      (hermes-chat-mode)
      (goto-char (point-max))
      (insert "unsent draft")
      (let ((position (point)) (window (selected-window)))
        (hermes--promise-resolve request (hermes-files-test--read))
        (should (eq (selected-window) window))
        (should (eq (current-buffer) other))
        (should (= (point) position))
        (should (equal (buffer-substring-no-properties
                        hermes-chat--input-marker (point-max)) "unsent draft")))
      (with-current-buffer viewer
        (should (eq major-mode 'hermes-file-view-mode))
        (should buffer-read-only)
        (should-not buffer-file-name)
        (should (string-match-p "Binary" header-line-format))
        (should-not (string-match-p "\0" (buffer-string)))
        (should (equal hermes-files--bytes (unibyte-string 0 255 65)))))))

(ert-deftest hermes-files-read-retired-owners-never-complete ()
  (dolist (retire '(refresh cancel viewer-cancel viewer-kill browser-kill
                           instance connection mode))
    (hermes-files-test--with-api
      (hermes-files)
      (push (current-buffer) buffers)
      (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
      (goto-char (point-min))
      (let ((browser (current-buffer)))
        (hermes-files-open)
        (push (current-buffer) buffers)
        (let ((viewer (current-buffer)) (request (nth 3 (car calls))))
          (pcase retire
            ('viewer-cancel (call-interactively (key-binding (kbd "C-g"))))
            ('viewer-kill (kill-buffer viewer))
            ('browser-kill (kill-buffer browser))
            (_ (with-current-buffer browser
                 (pcase retire
                   ('refresh (hermes-files-refresh))
                   ('cancel (hermes-files-cancel))
                   ('instance (setq hermes-instance '("other" . "http://other.test")))
                   ('connection (cl-incf (hermes-dashboard-transport-client-generation client)))
                   ('mode (fundamental-mode))))))
          (hermes--promise-resolve request (hermes-files-test--read))
          (when (buffer-live-p viewer)
            (with-current-buffer viewer
              (should-not hermes-files--bytes)
              (should (string-empty-p (buffer-string))))))))))

(ert-deftest hermes-files-refresh-preserves-real-windows-and-typing ()
  (dolist (visibility '(selected unselected hidden))
    (hermes-files-test--with-api
      (hermes-files)
      (push (current-buffer) buffers)
      (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing 100))
      (goto-char (point-min))
      (forward-line 40)
      (let* ((browser (current-buffer))
             (first (selected-window))
             (second (split-window-below))
             (other (generate-new-buffer " *typing*")))
        (push other buffers)
        (set-window-buffer second browser)
        (set-window-start first (save-excursion (forward-line -10) (point)) t)
        (set-window-start second (save-excursion (forward-line -20) (point)) t)
        (set-window-point second (save-excursion (forward-line 5) (point)))
        (hermes-files-refresh)
        (pcase visibility
          ('unselected (select-window second) (switch-to-buffer other))
          ('hidden (set-window-buffer first other)
                   (select-window second) (switch-to-buffer other)))
        (when (eq (current-buffer) other) (insert "draft stays"))
        (let ((window (selected-window)) (buffer (current-buffer)) (position (point))
              (starts (mapcar (lambda (w) (list w (window-start w) (window-point w)))
                              (get-buffer-window-list browser nil t))))
          (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing 100))
          (should (eq window (selected-window)))
          (should (eq buffer (current-buffer)))
          (should (= position (point)))
          (pcase-dolist (`(,w ,start ,point) starts)
            (should (= start (window-start w)))
            (should (= point (window-point w)))))))))

(ert-deftest hermes-files-save-exact-bytes-and-refuse-unsafe-destinations ()
  (let ((directory (make-temp-file "hermes-files-" t))
        (bytes (unibyte-string 0 255 65 13 10)))
    (unwind-protect
        (with-temp-buffer
          (hermes-file-view-mode)
          (setq hermes-files--bytes bytes)
          (let ((path (expand-file-name "literal.gz" directory)))
            (hermes-file-save path)
            (with-temp-buffer
              (set-buffer-multibyte nil)
              (insert-file-contents-literally path)
              (should (equal (buffer-string) bytes)))
            (should-error (hermes-file-save path) :type 'user-error))
          (make-symbolic-link directory (expand-file-name "link" directory))
          (should-error (hermes-file-save (expand-file-name "link/new" directory))
                        :type 'user-error)
          (make-symbolic-link "absent" (expand-file-name "dangling" directory))
          (should-error (hermes-file-save (expand-file-name "dangling" directory))
                        :type 'user-error)
          (should-error (hermes-file-save "/ssh:remote:/new") :type 'user-error)
          (cl-letf (((symbol-function 'read-file-name)
                     (lambda (&rest _) (setq hermes-files--bytes "replacement")
                       (expand-file-name "changed" directory))))
            (should-error (call-interactively #'hermes-file-save) :type 'user-error)
            (should-not (file-exists-p (expand-file-name "changed" directory)))))
      (delete-directory directory t))))

(ert-deftest hermes-files-decode-validates-size-path-cap-and-base64 ()
  (should (equal (hermes-files--decode (hermes-files-test--read) "/remote/file0.el")
                 (unibyte-string 0 255 65)))
  (dolist (result '((:path "/other" :size 3 :data_url "data:x;base64,AP9B")
                    (:path "/remote/file0.el" :size 2 :data_url "data:x;base64,AP9B")
                    (:path "/remote/file0.el" :size 4194305 :data_url "data:x;base64,")
                    (:path "/remote/file0.el" :size 0 :data_url "file:/tmp/evil")
                    (:path "/remote/file0.el" :size 1 :data_url "data:x;base64,QQ===")
                    (:path "/remote/file0.el" :size 1 :data_url "data:x;base64,Q@==")))
    (should-error (hermes-files--decode result "/remote/file0.el"))))

(ert-deftest hermes-files-query-is-encoded-at-shared-api-boundary ()
  (should (equal (hermes-dashboard-transport--query-string
                  '((path . "/remote/a & b?#é")))
                 "?path=%2Fremote%2Fa%20%26%20b%3F%23%C3%A9")))

(ert-deftest hermes-files-listing-cap-error-and-empty-states ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (hermes--promise-reject (nth 3 (car calls)) "private error data")
    (should (string-match-p "failed" hermes-files--status))
    (should-not (string-match-p "private" (buffer-string)))
    (hermes-files-refresh)
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing 2001))
    (should (= (length tabulated-list-entries) 2000))
    (should (string-match-p "limited" (hermes-files--context)))
    (hermes-files-refresh)
    (hermes--promise-resolve (nth 3 (car calls)) '(:path "/remote" :parent nil :entries nil))
    (should-not tabulated-list-entries)
    (should (string-match-p "0 rows" (hermes-files--context)))
    (should (equal hermes-files--status "Ready"))
    (should-error (hermes-files-up) :type 'user-error)))

(ert-deftest hermes-files-refresh-follows-row-after-insertion ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing 30))
    (goto-char (point-min))
    (forward-line 12)
    (let ((identity (hermes-transport--get (tabulated-list-get-id) 'path)))
      (hermes-files-refresh)
      (let ((result (hermes-files-test--listing 30)))
        (push '(:name "new" :path "/remote/new" :size 0) (plist-get result :entries))
        (hermes--promise-resolve (nth 3 (car calls)) result))
      (should (equal identity (hermes-transport--get (tabulated-list-get-id) 'path))))))

(ert-deftest hermes-files-content-never-selects-mode-or-local-variables ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
    (goto-char (point-min))
    (hermes-files-open)
    (push (current-buffer) buffers)
    (let* ((content ";;; -*- mode: emacs-lisp; eval: (error \"unsafe\"); -*-\n(message \"not executed\")")
           (result (list :path "/remote/file0.el" :size (length content)
                         :data_url (concat "data:text/plain;base64,"
                                           (base64-encode-string content t)))))
      (cl-letf (((symbol-function 'set-auto-mode) (lambda (&rest _) (ert-fail "auto mode")))
                ((symbol-function 'hack-local-variables) (lambda (&rest _) (ert-fail "local variables"))))
        (hermes--promise-resolve (nth 3 (car calls)) result))
      (should (equal (buffer-string) content))
      (should (eq major-mode 'hermes-file-view-mode))
      (should buffer-read-only))))

(ert-deftest hermes-files-kill-releases-retained-client-once ()
  (hermes-files-test--with-api
    (call-interactively #'hermes-files)
    (push (current-buffer) buffers)
    (should (= 1 (hermes-dashboard-transport-client-refcount client)))
    (fundamental-mode)
    (should (= 0 (hermes-dashboard-transport-client-refcount client)))
    (should (hermes-dashboard-transport-client-stopping-p client))
    (kill-buffer (current-buffer))
    (should (= 0 (hermes-dashboard-transport-client-refcount client)))
    (should (= releases 1))))

(defconst hermes-files-test--png
  (base64-decode-string
   "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGP4z8AAAAMBAQDJ/pLvAAAAAElFTkSuQmCC"))

(ert-deftest hermes-files-preview-unicode-and-save-original ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
    (goto-char (point-min))
    (hermes-files-open)
    (push (current-buffer) buffers)
    (let* ((text "Καλημέρα — café 世界\r\n")
           (bytes (encode-coding-string text 'utf-8-unix))
           (directory (make-temp-file "hermes-preview-" t))
           (path (expand-file-name "original" directory)))
      (unwind-protect
          (progn
            (hermes--promise-resolve
             (nth 3 (car calls))
             (list :path "/remote/file0.el" :size (length bytes)
                   :data_url (concat "data:application/octet-stream;base64,"
                                     (base64-encode-string bytes t))))
            (should (equal (buffer-string) text))
            (should (string-match-p "UTF-8 text" header-line-format))
            (should (string-match-p "/remote/file0.el" header-line-format))
            (should (equal (secure-hash 'sha256 hermes-files--bytes)
                           (secure-hash 'sha256 bytes)))
            (hermes-file-save path)
            (with-temp-buffer
              (set-buffer-multibyte nil)
              (insert-file-contents-literally path)
              (should (equal (buffer-string) bytes))))
        (delete-directory directory t)))))

(ert-deftest hermes-files-preview-raster-and-fallback ()
  (with-temp-buffer
    (hermes-file-view-mode)
    (setq hermes-instance '("Test" . "http://test.invalid"))
    (hermes-files--view hermes-files-test--png "/remote/picture.png")
    (if (and (display-images-p) (image-type-available-p 'png))
        (should (eq (car (get-text-property (point-min) 'display)) 'image))
      (should (string-match-p "unavailable" (buffer-string))))))

(ert-deftest hermes-files-preview-classification-is-explicit ()
  (should (eq (car (hermes-files--preview hermes-files-test--png)) 'png))
  (should (eq (car (hermes-files--preview (unibyte-string 255 216 255 0))) 'jpeg))
  (should (eq (car (hermes-files--preview "GIF89a\0")) 'gif))
  (dolist (bytes (list (unibyte-string 255) (unibyte-string 192 175)
                       (unibyte-string 0 65) (unibyte-string 27 91 109)))
    (should (eq (car (hermes-files--preview bytes)) 'binary)))
  (should (eq (car (hermes-files--preview "<svg onload='evil()'/ >")) 'text)))

(ert-deftest hermes-files-preview-image-failure-keeps-save ()
  (with-temp-buffer
    (hermes-file-view-mode)
    (setq hermes-instance '("Test" . "http://test.invalid"))
    (cl-letf (((symbol-function 'display-images-p) (lambda (&rest _) t))
              ((symbol-function 'image-type-available-p) (lambda (type) (eq type 'png)))
              ((symbol-function 'create-image) (lambda (&rest _) (error "Bad image"))))
      (hermes-files--view hermes-files-test--png "/remote/image"))
    (should (string-match-p "unavailable" (buffer-string)))
    (should (equal hermes-files--bytes hermes-files-test--png))
    (should (eq (key-binding "s") 'hermes-file-save))))

(ert-deftest hermes-files-visible-request-states ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
    (hermes-files--navigate "/remote/new")
    (should (string-match-p "/remote/new" (hermes-files--context)))
    (should (equal hermes-files--status "Loading"))
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
    (goto-char (point-min))
    (hermes-files-open)
    (push (current-buffer) buffers)
    (should mode-line-process)
    (should (equal hermes-files--status "Loading"))
    (hermes-files-cancel)
    (should (equal hermes-files--status "Cancelled"))
    (should-not (string-match-p "Loading" header-line-format))
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--read))
    (should-not hermes-files--bytes)))

(ert-deftest hermes-files-preview-native-png-spec ()
  (skip-unless (image-type-available-p 'png))
  (with-temp-buffer
    (hermes-file-view-mode)
    (setq hermes-instance '("Test" . "http://test.invalid"))
    ;; Batch frames cannot display images; exercise real native creation and
    ;; insertion, stubbing only the frame capability, not the image functions.
    (cl-letf (((symbol-function 'display-images-p) (lambda (&rest _) t)))
      (hermes-files--view hermes-files-test--png "/remote/picture.png"))
    (let ((image (get-text-property (point-min) 'display)))
      (should (eq (car image) 'image))
      (should (eq (plist-get (cdr image) :type) 'png))
      (should (equal (plist-get (cdr image) :data) hermes-files-test--png)))
    (should (equal hermes-files--bytes hermes-files-test--png))))

(ert-deftest hermes-files-visible-failure-state ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
    (goto-char (point-min))
    (let ((browser (current-buffer)))
      (hermes-files-open)
      (push (current-buffer) buffers)
      (hermes--promise-reject (nth 3 (car calls)) "private body")
      (should mode-line-process)
      (should (equal hermes-files--status "Failed"))
      (should (string-match-p "failed" header-line-format))
      (should-not hermes-files--bytes)
      (with-current-buffer browser
        (should mode-line-process)
        (should (string-match-p "failed" hermes-files--status))))))

(ert-deftest hermes-files-explicit-directory-recovers-initial-failure ()
  (hermes-files-test--with-api
    (call-interactively #'hermes-files)
    (push (current-buffer) buffers)
    (should-not (plist-get (nth 2 (car calls)) :query))
    (hermes--promise-reject (nth 3 (car calls)) "Unavailable")
    (should (string-match-p "failed" hermes-files--status))
    (should mode-line-process)
    (should (eq (key-binding "d") 'hermes-files-directory))
    (should (seq-some
             (lambda (group)
               (seq-some (lambda (entry) (equal (plist-get entry :key) "d"))
                         (plist-get group :entries)))
             (car (keymap-popup--meta hermes-files-mode-map 'descriptions))))
    (cl-letf (((symbol-function 'read-string) (lambda (&rest _) "~/a & b?#é"))
              ((symbol-function 'read-file-name) (lambda (&rest _) (ert-fail "Local completion"))))
      (call-interactively (key-binding "d")))
    (should (equal (plist-get (nth 2 (car calls)) :query)
                   '((path . "~/a & b?#é"))))
    (should (string-match-p "~/a & b" (hermes-files--context)))
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
    (goto-char (point-min))
    (call-interactively (key-binding (kbd "RET")))
    (push (current-buffer) buffers)
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--read))
    (let* ((directory (make-temp-file "hermes-recovery-" t))
           (file (expand-file-name "saved" directory)))
      (unwind-protect
          (progn
            (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) file)))
              (call-interactively (key-binding "s")))
            (with-temp-buffer
              (set-buffer-multibyte nil)
              (insert-file-contents-literally file)
              (should (equal (buffer-string) (unibyte-string 0 255 65)))))
        (delete-directory directory t)))))

(ert-deftest hermes-files-retains-existing-chat-client ()
  (dolist (teardown '(kill mode))
    (hermes-files-test--with-api
      (let ((chat (generate-new-buffer " *files chat*")))
        (push chat buffers)
        (switch-to-buffer chat)
        (hermes-chat-mode)
        (setq-local hermes-instance instance hermes-chat--dashboard-client client)
        (setf (hermes-dashboard-transport-client-websocket client) 'test-socket
              (hermes-dashboard-transport-client-refcount client) 1)
        (call-interactively #'hermes-files)
        (push (current-buffer) buffers)
        (let ((browser (current-buffer)))
          (should (eq hermes-files--client client))
          (should (= 2 (hermes-dashboard-transport-client-refcount client)))
          (with-current-buffer chat (setq hermes-chat--dashboard-client nil))
          (hermes-dashboard-transport-release client)
          (should (= 1 (hermes-dashboard-transport-client-refcount client)))
          (should-not (hermes-dashboard-transport-client-stopping-p client))
          (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
          (goto-char (point-min))
          (call-interactively (key-binding (kbd "RET")))
          (push (current-buffer) buffers)
          (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--read))
          (should hermes-files--bytes)
          (with-current-buffer browser
            (if (eq teardown 'kill) (kill-buffer browser) (fundamental-mode)))
          (should (= 0 (hermes-dashboard-transport-client-refcount client)))
          (should (hermes-dashboard-transport-client-stopping-p client))
          (when (buffer-live-p browser) (kill-buffer browser))
          (should (= 0 (hermes-dashboard-transport-client-refcount client)))
          (should (= releases 2)))))))

(ert-deftest hermes-files-retirement-settles-exact-viewer-synchronously ()
  (dolist (retire '(refresh cancel second-open kill mode))
    (dolist (completion '(resolve reject))
      (hermes-files-test--with-api
        (call-interactively #'hermes-files)
        (push (current-buffer) buffers)
        (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
        (goto-char (point-min))
        (let ((browser (current-buffer)))
          (call-interactively (key-binding (kbd "RET")))
          (push (current-buffer) buffers)
          (let ((viewer (current-buffer)) (request (nth 3 (car calls))))
            (switch-to-buffer browser)
            (pcase retire
              ('refresh (call-interactively (key-binding "g")))
              ('cancel (call-interactively (key-binding (kbd "C-g"))))
              ('second-open (call-interactively (key-binding (kbd "RET")))
                            (push (current-buffer) buffers))
              ('kill (kill-buffer browser))
              ('mode (fundamental-mode)))
            (let ((window (selected-window)) (buffer (current-buffer))
                  (position (point))
                  (snapshot (with-current-buffer viewer
                              (should (equal hermes-files--status "Cancelled"))
                              (should (string-match-p "cancelled" header-line-format))
                              (list (buffer-string) header-line-format mode-line-process))))
              (if (eq completion 'resolve)
                  (hermes--promise-resolve request (hermes-files-test--read))
                (hermes--promise-reject request "Late private rejection"))
              (should (eq window (selected-window)))
              (should (eq buffer (current-buffer)))
              (should (= position (point)))
              (with-current-buffer viewer
                (should-not hermes-files--bytes)
                (should (equal snapshot
                               (list (buffer-string) header-line-format mode-line-process)))))
            (when (eq retire 'second-open)
              (should (equal hermes-files--status "Loading"))
              (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--read))
              (should hermes-files--bytes))))))))

(ert-deftest hermes-files-retirement-preserves-settled-and-replaced-viewers ()
  (dolist (state '(ready failed replaced))
    (hermes-files-test--with-api
      (call-interactively #'hermes-files)
      (push (current-buffer) buffers)
      (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
      (goto-char (point-min))
      (let ((browser (current-buffer)))
        (call-interactively (key-binding (kbd "RET")))
        (push (current-buffer) buffers)
        (let ((viewer (current-buffer)) (request (nth 3 (car calls))))
          (pcase state
            ('ready (hermes--promise-resolve request (hermes-files-test--read)))
            ('failed (hermes--promise-reject request "Unavailable"))
            ('replaced (hermes-file-view-mode)
                       (setq header-line-format "New owner")))
          (let ((snapshot (list hermes-files--status header-line-format hermes-files--bytes)))
            (with-current-buffer browser (call-interactively #'hermes-files-refresh))
            (hermes--promise-resolve request (hermes-files-test--read))
            (should (eq (current-buffer) viewer))
            (should (equal snapshot
                           (list hermes-files--status header-line-format hermes-files--bytes)))))))))

(ert-deftest hermes-files-transport-retirement-settles-public-open ()
  (dolist (retire '(stop process-exit reconnect))
    (dolist (completion '(resolve reject))
      (hermes-files-test--with-api
        (call-interactively #'hermes-files)
        (push (current-buffer) buffers)
        (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
        (should-not hermes-files--subscription)
        (goto-char (point-min))
        (let ((browser (current-buffer)))
          (call-interactively (key-binding (kbd "RET")))
          (push (current-buffer) buffers)
          (let* ((viewer (current-buffer)) (request (nth 3 (car calls)))
                 (observer (plist-get
                            (gethash (buffer-local-value 'hermes-files--subscription browser)
                                     (hermes-dashboard-transport-client-subscribers client)) :retire))
                 (typing (generate-new-buffer " *transport retirement draft*"))
                 successor)
            (push typing buffers)
            (switch-to-buffer typing)
            (hermes-chat-mode)
            (buffer-enable-undo)
            (goto-char (point-max))
            (insert "unsent exact draft")
            (let ((window (selected-window)) (position (point))
                  (undo (copy-tree buffer-undo-list)) (text (buffer-string)))
              (message "Transport retirement: %s / %s" retire completion)
              (pcase retire
                ('stop (hermes-dashboard-transport-stop client "Disconnected"))
                ('process-exit
                 (let ((process (make-pipe-process :name "files-exit-test" :noquery t)))
                   (setf (hermes-dashboard-transport-client-process client) process)
                   (delete-process process)
                   (hermes-dashboard-transport--handle-process-exit
                    client process (hermes-dashboard-transport-client-process-generation client))))
                ('reconnect
                 (cl-letf (((symbol-function 'hermes-dashboard-transport--arm-ready-timeout) #'ignore)
                           ((symbol-function 'hermes-dashboard-transport--reconnect-attempt) #'ignore))
                   (hermes-dashboard-transport-reconnect client))))
              ;; Settlement must precede either HTTP completion and must not
              ;; move the reader while retiring the unselected file views.
              (should (eq window (selected-window)))
              (should (eq typing (current-buffer)))
              (should (= position (point)))
              (should (equal undo buffer-undo-list))
              (should (equal text (buffer-string)))
              (with-current-buffer viewer
                (should (equal hermes-files--status "Cancelled"))
                (should (string-match-p "cancelled" header-line-format))
                (should-not hermes-files--bytes))
              (with-current-buffer browser
                (should (equal hermes-files--status "Cancelled"))
                (should (equal (eval (cadr mode-line-process)) " Cancelled"))
                (should-not hermes-files--pending-viewer)
                (should-not hermes-files--subscription)
                ;; A successor request on the current generation owns its own
                ;; viewer; old event delivery must not cancel either.
                (call-interactively #'hermes-files-open)
                (setq successor (current-buffer)))
              (progn
                (push successor buffers)
                (select-window window)
                (switch-to-buffer typing)
                (funcall observer)
                (if (eq completion 'resolve)
                    (hermes--promise-resolve request (hermes-files-test--read))
                  (hermes--promise-reject request "Late private body"))
                (with-current-buffer successor
                  (should (equal hermes-files--status "Loading"))
                  (should-not hermes-files--bytes))
                (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--read))
                (with-current-buffer successor
                  (should (equal hermes-files--status "Ready"))
                  (should hermes-files--bytes)))
              (should (eq window (selected-window)))
              (should (eq typing (current-buffer)))
              (should (= position (point)))
              (should (equal undo buffer-undo-list))
              (should (equal text (buffer-string)))
              (with-current-buffer viewer
                (should (equal hermes-files--status "Cancelled"))
                (should-not hermes-files--bytes)))))))))

(ert-deftest hermes-files-transport-stop-settles-initial-listing ()
  (hermes-files-test--with-api
    (call-interactively #'hermes-files)
    (push (current-buffer) buffers)
    (let ((request (nth 3 (car calls))))
      (hermes-dashboard-transport-stop client)
      (should (equal hermes-files--status "Cancelled"))
      (should-not hermes-files--subscription)
      (hermes--promise-resolve request (hermes-files-test--listing))
      (should (equal hermes-files--status "Cancelled"))
      (should-not hermes-files--rows))))

(ert-deftest hermes-files-popup-exact-dismiss-cancel-and-quit ()
  ;; Exercise the transient wrapper, not just the ordinary mode map.
  (dolist (keys '("? q" "? <escape>" "? C-g" "C-g" "q"))
    (hermes-files-test--with-api
      (hermes-files)
      (push (current-buffer) buffers)
      (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
      (goto-char (point-min))
      (let ((browser (current-buffer)))
        (hermes-files-open)
        (push (current-buffer) buffers)
        (let ((viewer (current-buffer)) (request (nth 3 (car calls))))
          (switch-to-buffer browser)
          (unwind-protect
              (progn
                (when (string-prefix-p "?" keys)
                  (execute-kbd-macro (kbd "?"))
                  (with-current-buffer keymap-popup--buffer-name
                    (dolist (label '("Dismiss menu" "Cancel read" "Quit view"))
                      (should (string-match-p label (buffer-string))))))
                (execute-kbd-macro
                 (kbd (if (string-prefix-p "? " keys) (substring keys 2) keys)))
                (should-not (get-buffer-window keymap-popup--buffer-name))
                (if (equal keys "? <escape>")
                    (progn
                      (should (eq (current-buffer) browser))
                      (should (equal hermes-files--status "Loading"))
                      (should hermes-files--pending-viewer)
                      (hermes--promise-resolve request (hermes-files-test--read))
                      (should (buffer-local-value 'hermes-files--bytes viewer)))
                  (if (string-suffix-p "q" keys)
                      (should-not (eq (window-buffer) browser))
                    (should (eq (current-buffer) browser))))
                (unless (equal keys "? <escape>")
                  (with-current-buffer browser
                    (should (equal hermes-files--status "Cancelled"))
                    (should-not hermes-files--pending-viewer))
                  (with-current-buffer viewer
                    (should (equal hermes-files--status "Cancelled")))
                  (hermes--promise-resolve request (hermes-files-test--read))
                  (should-not (buffer-local-value 'hermes-files--bytes viewer))))
            (keymap-popup-dismiss)))))))

(ert-deftest hermes-files-native-columns-survive-async-render-and-resize ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing 100))
    (let ((header (format "%s" header-line-format)))
      (dolist (label '("Name" "Kind" "Bytes"))
        (should (string-match-p label header))))
    (let* ((browser (current-buffer))
           (wide (selected-window))
           (original-width (cadar (append tabulated-list-format nil)))
           (narrow (split-window-right))
           (typing (generate-new-buffer " *files resize draft*")))
      (push typing buffers)
      (set-window-buffer narrow browser)
      (goto-char (point-min))
      (forward-line 40)
      (move-to-column 3)
      (set-window-start wide (save-excursion (forward-line -10) (point)) t)
      (set-window-start narrow (save-excursion (forward-line -20) (point)) t)
      (set-window-point narrow (save-excursion (forward-line 5) (point)))
      (let ((anchors (mapcar
                      (lambda (w) (list w (hermes-files--position (window-start w))
                                        (hermes-files--position (window-point w))))
                      (list wide narrow)))
            (position (hermes-files--position (point))))
        (hermes-files-refresh)
        (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing 100))
        (should (< (cadar (append tabulated-list-format nil)) original-width))
        (should (equal (seq-take position 3)
                       (seq-take (hermes-files--position (point)) 3)))
        (pcase-dolist (`(,window ,start ,point) anchors)
          (should (equal (seq-take start 3)
                         (seq-take (hermes-files--position (window-start window)) 3)))
          (should (equal (seq-take point 3)
                         (seq-take (hermes-files--position (window-point window)) 3)))))
      (select-window narrow)
      (switch-to-buffer typing)
      (hermes-chat-mode)
      (buffer-enable-undo)
      (goto-char (point-max))
      (insert "Unsent exact draft")
      (let ((text (buffer-string)) (position (point)) (undo (copy-tree buffer-undo-list))
            (start (window-start wide)) (browser-point (window-point wide))
            (start-row (with-current-buffer browser
                         (seq-take (hermes-files--position (window-start wide)) 3)))
            (point-row (with-current-buffer browser
                         (seq-take (hermes-files--position (window-point wide)) 3))))
        (delete-window wide)
        (setq wide (split-window-below))
        (set-window-buffer wide browser)
        (set-window-start wide start t)
        (set-window-point wide browser-point)
        ;; Batch redisplay does not deliver configuration hooks.  Call the
        ;; installed local hook with the same window context as real redisplay.
        (with-current-buffer browser
          (run-hooks 'window-configuration-change-hook))
        (should (eq (current-buffer) typing))
        (should (= position (point)))
        (should (equal text (buffer-string)))
        (should (equal undo buffer-undo-list))
        (with-current-buffer browser
          (should (equal start-row
                         (seq-take (hermes-files--position (window-start wide)) 3)))
          (should (equal point-row
                         (seq-take (hermes-files--position (window-point wide)) 3))))
        (with-current-buffer browser
          (should (= (cadar (append tabulated-list-format nil)) original-width))
          (dolist (label '("Name" "Kind" "Bytes"))
            (should (string-match-p label (format "%s" header-line-format)))))))))

(ert-deftest hermes-file-view-popup-save-and-back ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
    (goto-char (point-min))
    (let ((browser (current-buffer)) (directory (make-temp-file "hermes-menu-save-" t)))
      (unwind-protect
          (progn
            (hermes-files-open)
            (push (current-buffer) buffers)
            (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--read))
            (let ((viewer (current-buffer)) (file (expand-file-name "literal.gz" directory)))
              (execute-kbd-macro (kbd "?"))
              (with-current-buffer keymap-popup--buffer-name
                (dolist (label '("Save NEW local file" "Back" "Dismiss menu"))
                  (should (string-match-p label (buffer-string)))))
              (cl-letf (((symbol-function 'read-file-name) (lambda (&rest _) file)))
                (execute-kbd-macro (kbd "s")))
              (with-temp-buffer
                (set-buffer-multibyte nil)
                (insert-file-contents-literally file)
                (should (equal (buffer-string) (unibyte-string 0 255 65))))
              (execute-kbd-macro (kbd "? q"))
              (should (eq (current-buffer) browser))
              (should (equal (buffer-local-value 'hermes-files--bytes viewer)
                             (unibyte-string 0 255 65)))))
        (keymap-popup-dismiss)
        (delete-directory directory t)))))

(ert-deftest hermes-files-name-and-context-retain-full-text ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (let* ((name (concat (make-string 46 ?n) ".txt"))
           (path (concat "/remote/" name))
           (result (list :path "/remote" :parent nil :entries
                         (list (list :name name :path path :size 3)))))
      (hermes--promise-resolve (nth 3 (car calls)) result)
      (goto-char (point-min))
      (should (> (cadr (aref tabulated-list-format 0)) 45))
      (should (string-match-p (regexp-quote name) (buffer-string)))
      (let ((header (car (last header-line-format))))
        (should (string-match-p (regexp-quote (hermes-files--label name))
                                (get-text-property (point) 'help-echo)))
        (should (equal (get-text-property (string-match "Name" header)
                                          'tabulated-list-column-name header) "Name")))
      (let ((context (hermes-files--context)))
        (dolist (text '("Files test" "/remote" "1 rows" "? Help"))
          (should (string-match-p (regexp-quote text) context))))
      (setq hermes-files--path (concat "/remote/" (make-string 100 ?x) "%b"))
      (let ((context (hermes-files--context)))
        (should (< (string-width context) (window-body-width)))
        (should (string-match-p (regexp-quote hermes-files--path)
                                (get-text-property 0 'help-echo context))))
      ;; Even after display shortening, open dispatch keeps the exact row path.
      (call-interactively #'hermes-files-open)
      (push (current-buffer) buffers)
      (should (equal (plist-get (nth 2 (car calls)) :query) (list (cons 'path path)))))))

(ert-deftest hermes-file-view-pending-popup-dismiss-cancel-and-back ()
  (dolist (key '("<escape>" "C-g" "q"))
    (hermes-files-test--with-api
      (hermes-files)
      (push (current-buffer) buffers)
      (hermes--promise-resolve (nth 3 (car calls)) (hermes-files-test--listing))
      (goto-char (point-min))
      (let ((browser (current-buffer)))
        (hermes-files-open)
        (push (current-buffer) buffers)
        (let ((viewer (current-buffer)) (request (nth 3 (car calls))))
          (unwind-protect
              (progn
                (execute-kbd-macro (kbd "?"))
                (cl-letf (((symbol-function 'read-file-name)
                           (lambda (&rest _) (ert-fail "Pending viewer offered save"))))
                  (execute-kbd-macro (kbd "s")))
                (should (get-buffer-window keymap-popup--buffer-name))
                (should (equal hermes-files--status "Loading"))
                (execute-kbd-macro (kbd key))
                (should-not (get-buffer-window keymap-popup--buffer-name))
                (should (eq (current-buffer) (if (equal key "q") browser viewer)))
                (with-current-buffer viewer
                  (should (equal hermes-files--status
                                 (if (equal key "<escape>") "Loading" "Cancelled"))))
                (hermes--promise-resolve request (hermes-files-test--read))
                (should (eq (not (buffer-local-value 'hermes-files--bytes viewer))
                            (not (equal key "<escape>")))))
            (keymap-popup-dismiss)))))))

(ert-deftest hermes-files-window-metrics-respect-gutters-and-face-width ()
  (hermes-files-test--with-api
    (hermes-files)
    (push (current-buffer) buffers)
    (let* ((browser (current-buffer))
           (first (selected-window)) (second (split-window-right)))
      (set-window-buffer second browser)
      ;; Controlled metrics distinguish frame columns from remapped text
      ;; pixels; actual window selection and caller-point restoration are real.
      (cl-letf (((symbol-function 'window-body-width)
                 (lambda (_window &optional pixelwise) (if pixelwise 800 80)))
                ((symbol-function 'window-font-width)
                 (lambda (&optional window _face) (if (eq window first) 10 20)))
                ((symbol-function 'frame-char-width)
                 (lambda (&rest _) (ert-fail "Frame font used for text viewport")))
                ((symbol-function 'line-number-display-width)
                 (lambda (&optional _pixelwise)
                   (should display-line-numbers)
                   (if (eq (selected-window) first) 20 80))))
        (let ((display-line-numbers nil)
              (reserve (+ 1 tabulated-list-padding 9 12 2)))
          (should (= (+ reserve (hermes-files--name-width)) 40))
          (let ((display-line-numbers t))
            (should (= (+ reserve (hermes-files--name-width)) 36)))
          (should (eq first (selected-window)))
          (should (eq browser (current-buffer))))))))

(provide 'hermes-files-tests)
;;; hermes-files-tests.el ends here
