;;; hermes-chat-slash-tests.el --- Chat topic tests -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'delsel)
(require 'hermes-test-helpers)

(ert-deftest hermes-chat-parses-slash-commands-with-arguments ()
  (should (equal (hermes-chat--parse-slash "/QUEUE next message")
                 '("queue" . "next message")))
  (should (equal (hermes-chat--parse-slash "/Goal\nstatus")
                 '("goal" . "status")))
  (should (equal (hermes-chat--parse-slash "/commands")
                 '("commands" . "")))
  (should-not (hermes-chat--parse-slash " /queue not-a-command")))

(ert-deftest hermes-chat-catalog-candidates-extracts-names ()
  "Catalog candidates extract bare command names and descriptions."
  (let ((cands (hermes-chat--catalog-candidates
                '((categories . (((name . "Session")
                                  (pairs . (("/steer" "Steer the run")
                                            ("/model" "Switch model"))))))))))
    (should (equal (assoc "steer" cands) '("steer" . "Steer the run")))
    (should (assoc "model" cands))))

(ert-deftest hermes-chat-slash-capf-completes-in-input ()
  "The slash capf offers command names while typing /cmd in the input."
  (hermes-test-with-chat-buffer
   (setq hermes-chat--commands-cache '(("steer" . "Steer") ("model" . "Switch")))
   (goto-char (point-max))
   (insert "/st")
   (let ((capf (hermes-chat--slash-capf)))
     (should capf)
     (should (member "steer" (nth 2 capf)))
     (should (= (nth 0 capf) (1+ (hermes-chat--input-position))))
     (should (= (nth 1 capf) (point))))))

(ert-deftest hermes-chat-slash-capf-inactive-off-command ()
  "The slash capf is inactive for non-slash input or inside arguments."
  (hermes-test-with-chat-buffer
   (setq hermes-chat--commands-cache '(("steer" . "Steer")))
   (goto-char (point-max))
   (insert "hello")
   (should-not (hermes-chat--slash-capf))
   (hermes-chat--delete-input-tail)
   (insert "/steer now")
   (should-not (hermes-chat--slash-capf))))

(ert-deftest hermes-chat-native-slash-handler-resolves-names-and-aliases ()
  "The resolver maps known names and aliases to handlers and others to nil."
  (should (functionp (hermes-chat--native-slash-handler "stop")))
  (should (functionp (hermes-chat--native-slash-handler "interrupt")))
  (should (functionp (hermes-chat--native-slash-handler "int")))
  (should (functionp (hermes-chat--native-slash-handler "clear")))
  (should (functionp (hermes-chat--native-slash-handler "reset")))
  (should (functionp (hermes-chat--native-slash-handler "compact")))
  (should (functionp (hermes-chat--native-slash-handler "compress")))
  (should-not (hermes-chat--native-slash-handler "definitely-not-a-command"))
  (should-not (hermes-chat--native-slash-handler nil)))

(ert-deftest hermes-chat-slash-stop-calls-process-stop ()
  "/stop runs the process.stop RPC rather than forwarding to the agent."
  (let ((client (hermes-test--dashboard-client))
        (stopped 0))
    (cl-letf (((symbol-function 'hermes-transport-send)
               (lambda (&rest _a) (error "CLI fallback should not run")))
              ((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _a) client))
              ((symbol-function 'hermes-dashboard-transport-session-create)
               (lambda (_c &rest args)
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-active")))))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (_c _t &rest _a) nil))
              ((symbol-function 'hermes-dashboard-transport-process-stop)
               (lambda (_c &rest args)
                 (setq stopped (1+ stopped))
                 (funcall (plist-get args :resolve) '((killed . 2)))))
              ((symbol-function 'yes-or-no-p) (lambda (_) t)))
      (let ((hermes-transport-send-function #'hermes-transport-send))
        (hermes-test-with-chat-buffer
         (insert "go")
         (hermes-chat-send)
         (insert "/stop")
         (hermes-chat-send)
         (should (= stopped 1)))))))

(ert-deftest hermes-chat-slash-clear-resets-transcript-and-session ()
  "/clear empties the transcript and forgets the live and durable session ids."
  (let ((client (hermes-test--dashboard-client))
        (stopped 0))
    (cl-letf (((symbol-function 'hermes-transport-send)
               (lambda (&rest _a) (error "CLI fallback should not run")))
              ((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _a) client))
              ((symbol-function 'hermes-dashboard-transport-session-create)
               (lambda (_c &rest args)
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-active")))))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (_c _t &rest _a) nil))
              ((symbol-function 'hermes-chat--stop-dashboard-client)
               (lambda () (setq stopped (1+ stopped))))
              ((symbol-function 'y-or-n-p) (lambda (&rest _a) t)))
      (let ((hermes-transport-send-function #'hermes-transport-send))
        (hermes-test-with-chat-buffer
         (insert "remember this")
         (hermes-chat-send)
         (should hermes-chat--dashboard-active-session-id)
         (setq stopped 0
               hermes-chat--model "stale-model"
               hermes-chat--agent-name "stale-agent"
               hermes-chat--context '(:used 45000 :max 200000 :percent 22)
               hermes-chat--goal '(:running t :turns-used 2 :max-turns 20)
               hermes-chat--runtime-flags '(:reasoning-effort "high" :fast t :yolo t))
         (insert "/clear")
         (hermes-chat-send)
         (should (= stopped 1))
         (should-not hermes-chat--dashboard-active-session-id)
         (should-not hermes-chat--session-id)
         (should-not hermes-chat--model)
         (should-not hermes-chat--agent-name)
         (should-not hermes-chat--context)
         (should-not hermes-chat--goal)
         (should-not hermes-chat--runtime-flags)
         (should-not (string-match-p "Goal\\|ctx\\|stale-model\\|high\\|fast\\|YOLO"
                                     (hermes-test--header-line-string)))
         (should (equal (mapcar (lambda (e) (plist-get e :role))
                                (hermes-chat--entries))
                        '(status))))))))

(ert-deftest hermes-chat-reset-runs-buffer-cleanup-before-reinitializing ()
  "Reset cancels per-buffer resources before constructing the new transcript."
  (let ((timer 'handoff-timer) cancelled cleanup-ran)
    (cl-letf (((symbol-function 'cancel-timer)
               (lambda (value) (push value cancelled)))
              ((symbol-function 'hermes-chat--stop-dashboard-client) #'ignore))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--handoff-poll (list :timer timer :id 'old)
             hermes-chat-cleanup-functions
             (list (lambda ()
                     (setq cleanup-ran t)
                     (hermes-chat--handoff-stop))))
       (hermes-chat--reset-transcript)
       (should cleanup-ran)
       (should (memq timer cancelled))
       (should-not hermes-chat--handoff-poll)))))

(ert-deftest hermes-chat-unknown-slash-falls-through-to-gateway ()
  "An unknown slash command dispatches to the gateway, not a native handler."
  (let ((client (hermes-test--dashboard-client))
        slash-name)
    (cl-letf (((symbol-function 'hermes-transport-send)
               (lambda (&rest _a) (error "CLI fallback should not run")))
              ((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _a) client))
              ((symbol-function 'hermes-dashboard-transport-session-create)
               (lambda (_c &rest args)
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-active")))))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (_c _t &rest _a) nil))
              ((symbol-function 'hermes-chat--dashboard-slash-exec)
               (lambda (name _arg _raw) (setq slash-name name))))
      (let ((hermes-transport-send-function #'hermes-transport-send))
        (hermes-test-with-chat-buffer
         (insert "go")
         (hermes-chat-send)
         (insert "/somethingcustom foo")
         (hermes-chat-send)
         (should (equal slash-name "somethingcustom")))))))

(ert-deftest hermes-chat-control-error-keeps-active-turn ()
  (let ((client (hermes-test--dashboard-client))
        callback last-frame submits first-assistant)
    (cl-letf (((symbol-function 'hermes-transport-send)
               (lambda (&rest _args) (error "CLI fallback should not run")))
              ((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest args)
                 (setq callback (plist-get args :callback))
                 (setf (hermes-dashboard-transport-client-callback client)
                       callback)
                 client))
              ((symbol-function 'hermes-dashboard-transport-session-create)
               (lambda (_client &rest args)
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-active")))))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (_client text &rest args)
                 (push text submits)
                 (when-let* ((resolve (plist-get args :resolve)))
                   (funcall resolve '((status . "streaming")))))))
      (let ((hermes-transport-send-function #'hermes-transport-send)
            (hermes-dashboard-transport-websocket-send-function
             (lambda (_websocket text)
               (setq last-frame
                     (hermes-dashboard-transport--decode-frame text)))))
        (hermes-test-with-chat-buffer
         (insert "first")
         (hermes-chat-send)
         (setq first-assistant hermes-chat--pending-assistant-id)
         (insert "/steer cite files")
         (hermes-chat-send)
         (hermes-dashboard-transport--handle-frame
          client
          `((jsonrpc . "2.0")
            (id . ,(alist-get 'id last-frame))
            (error . ((message . "agent does not support steer")))))
         (should (equal hermes-chat--pending-assistant-id first-assistant))
         (should (equal (hermes-test--queued-contents) '("cite files")))
         (should (equal submits '("first")))
         (funcall callback '(:type done :session-id "sid-active"))
         (hermes-test--emit-dashboard-idle client)
         (should (equal submits '("cite files" "first"))))))))

(ert-deftest hermes-chat-commands-catalog-rendering ()
  (let ((client (hermes-test--dashboard-client))
        catalog-requested
        (catalog '((categories
                    . (((name . "Session")
                        (pairs . (("/queue" "Queue next message")
                                  ("/steer" "Steer active run"))))))
                   (sub . (("goal" . ("status" "pause" "resume"))
                           ("config" . ("get" "set"))))
                   (warning . "skill discovery unavailable"))))
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-commands-catalog)
               (lambda (_client &rest args)
                 (setq catalog-requested t)
                 (funcall (plist-get args :resolve) catalog))))
      (hermes-test-with-chat-buffer
       (insert "/commands")
       (hermes-chat-send)
       (should catalog-requested)
       (let ((text (buffer-string)))
         (should (string-match-p "Session" text))
         (should (string-match-p "/queue — Queue next message" text))
         (should (string-match-p "/steer — Steer active run" text))
         (should (string-match-p "skill discovery unavailable" text))
         (should (string-match-p "Subcommands" text))
         (should (string-match-p "/goal status" text))
         (should (string-match-p "/goal pause" text))
         (should (string-match-p "/config get" text)))))))

(ert-deftest hermes-chat-command-skill-sends-message ()
  (let ((client (hermes-test--dashboard-client))
        submit-text slash-command dispatch-name dispatch-arg)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-create)
               (lambda (_client &rest args)
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-active")))))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (_client text &rest _args)
                 (setq submit-text text)))
              ((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (_client command &rest args)
                 (setq slash-command command)
                 (funcall (plist-get args :reject)
                          "skill command uses command.dispatch")))
              ((symbol-function 'hermes-dashboard-transport-command-dispatch)
               (lambda (_client name arg &rest args)
                 (setq dispatch-name name
                       dispatch-arg arg)
                 (funcall (plist-get args :resolve)
                          '((type . "skill")
                            (name . "demo")
                            (message . "use demo skill"))))))
      (hermes-test-with-chat-buffer
       (insert "/demo now")
       (hermes-chat-send)
       (should (equal slash-command "demo now"))
       (should (equal dispatch-name "demo"))
       (should (equal dispatch-arg "now"))
       (should (equal submit-text "use demo skill"))
       (let ((text (buffer-string)))
         (should (string-match-p "loading skill: demo" text))
         ;; the full skill payload is sent to the agent but never echoed
         (should-not (string-match-p "use demo skill" text)))))))

(ert-deftest hermes-chat-command-skill-queues-while-active ()
  (let ((client (hermes-test--dashboard-client)) callback submits)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest args)
                 (setq callback (plist-get args :callback))
                 client))
              ((symbol-function 'hermes-dashboard-transport-session-create)
               (lambda (_client &rest args)
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-active")))))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (_client text &rest args)
                 (push text submits)
                 (when-let* ((resolve (plist-get args :resolve)))
                   (funcall resolve '((status . "streaming"))))))
              ((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (_client _command &rest args)
                 (funcall (plist-get args :reject)
                          "skill command uses command.dispatch")))
              ((symbol-function 'hermes-dashboard-transport-command-dispatch)
               (lambda (_client _name _arg &rest args)
                 (funcall (plist-get args :resolve)
                          '((type . "skill")
                            (name . "demo")
                            (message . "use demo while busy"))))))
      (hermes-test-with-chat-buffer
       (insert "first")
       (hermes-chat-send)
       (insert "/demo now")
       (hermes-chat-send)
       (should (equal submits '("first")))
       (should (equal (hermes-test--queued-contents)
                      '("use demo while busy")))
       (should (string-match-p "loading skill: demo" (buffer-string)))
       (funcall callback '(:type done :session-id "sid-active"))
       (hermes-test--emit-dashboard-idle client)
       (should (equal submits '("use demo while busy" "first")))))))

(ert-deftest hermes-chat-command-prefill-preserves-edited-composer ()
  "Delayed prefill retains literal text separately, even after typing is undone."
  (dolist (edit '(draft erased whitespace unchanged reading))
    (let (resolve recovery)
      (unwind-protect
          (hermes-test-with-chat-buffer
            (setq hermes-chat--dashboard-client (hermes-test--dashboard-client)
                  hermes-chat--dashboard-active-session-id "prefill-session"
                  hermes-chat--dashboard-session-ready-p t)
            (cl-letf (((symbol-function 'hermes-dashboard-transport-slash-exec)
                       (lambda (_client _command &rest args)
                         (setq resolve (plist-get args :resolve))))
                      ((symbol-function 'display-buffer)
                       (lambda (buffer &rest _) (setq recovery buffer))))
              (insert "/undo")
              (call-interactively (key-binding (kbd "RET")))
              (pcase edit
                ('draft (insert "newer draft"))
                ('erased (insert "x") (delete-char -1))
                ('whitespace (insert "  ")))
              ;; Transcript output is not an edit to the composer.
              (hermes-chat--insert-local-status "Background notice" 'done)
              (when (eq edit 'reading) (goto-char (point-min)))
              (let ((draft (hermes-chat-input-string))
                    (offset (- (point) (hermes-chat--input-position)))
                    (text "  Earlier answer; όχι\nsecond line  "))
                (funcall resolve `((type . "prefill") (message . ,text)
                                   (notice . "Undid one turn")))
                (should-not hermes-chat--command-owner)
                (if (memq edit '(unchanged reading))
                    (progn
                      (should (equal (hermes-chat-input-string) text))
                      (when (eq edit 'reading) (should (= (point) (point-min))))
                      (should-not recovery))
                  (should (equal (hermes-chat-input-string) draft))
                  (should (= (- (point) (hermes-chat--input-position)) offset))
                  (should (buffer-live-p recovery))
                  (should (eq (current-buffer) buffer))
                  (should (string-match-p (regexp-quote (buffer-name recovery))
                                          (buffer-string)))
                  (should (equal (with-current-buffer recovery (buffer-string))
                                 text)))
                (should-not (hermes-test--queued-contents))
                ;; A duplicate completion must not insert or create another copy.
                (let ((before (buffer-string)) (copy recovery))
                  (funcall resolve `((type . "prefill") (message . ,text)))
                  (should (equal (buffer-string) before))
                  (should (eq recovery copy))))))
        (when (buffer-live-p recovery) (kill-buffer recovery))))))

(ert-deftest hermes-chat-command-prefill-fallback-retains-edit-evidence ()
  "Legacy dispatch fallback cannot forget typing erased during slash execution."
  (let (reject resolve recovery)
    (unwind-protect
        (hermes-test-with-chat-buffer
          (setq hermes-chat--dashboard-client (hermes-test--dashboard-client)
                hermes-chat--dashboard-active-session-id "prefill-session"
                hermes-chat--dashboard-session-ready-p t)
          (cl-letf (((symbol-function 'hermes-dashboard-transport-slash-exec)
                     (lambda (_client _command &rest args)
                       (setq reject (plist-get args :reject))))
                    ((symbol-function 'hermes-dashboard-transport-command-dispatch)
                     (lambda (_client _name _arg &rest args)
                       (setq resolve (plist-get args :resolve))))
                    ((symbol-function 'display-buffer)
                     (lambda (buffer &rest _) (setq recovery buffer))))
            (insert "/undo")
            (hermes-chat-send)
            (insert "x")
            (delete-char -1)
            (funcall reject "Use command.dispatch")
            (funcall resolve '((type . "prefill") (message . "Old answer")))
            (should (string-empty-p (hermes-chat-input-string)))
            (should (equal (with-current-buffer recovery (buffer-string))
                           "Old answer"))))
      (when (buffer-live-p recovery) (kill-buffer recovery)))))

(ert-deftest hermes-chat-command-prefill-stale-owners-stay-quiet ()
  "Prefill cannot affect a replacement command, session, lifetime or mode."
  (dolist (change '(command session lifetime mode))
    (let (resolve displayed)
      (hermes-test-with-chat-buffer
        (setq hermes-chat--dashboard-client (hermes-test--dashboard-client)
              hermes-chat--dashboard-active-session-id "prefill-session"
              hermes-chat--dashboard-session-ready-p t)
        (cl-letf (((symbol-function 'hermes-dashboard-transport-slash-exec)
                   (lambda (_client _command &rest args)
                     (setq resolve (plist-get args :resolve))))
                  ((symbol-function 'display-buffer)
                   (lambda (&rest _) (setq displayed t))))
          (insert "/undo")
          (hermes-chat-send)
          (pcase change
            ('command (hermes-chat--command-stop) (hermes-chat--command-start))
            ('session (setq hermes-chat--dashboard-active-session-id "successor"))
            ('lifetime (setq hermes-chat--lifecycle-generation
                             (hermes-chat--next-lifetime-token)))
            ('mode (fundamental-mode)))
          (let ((before (buffer-string)) (owner hermes-chat--command-owner))
            (funcall resolve '((type . "prefill") (message . "obsolete")))
            (should (equal (buffer-string) before))
            (should-not displayed)
            (when (eq change 'command)
              (should (eq hermes-chat--command-owner owner)))))))))

(ert-deftest hermes-chat-command-prefill-renders-notice ()
  (hermes-test-with-chat-buffer
   (hermes-chat--handle-command-result
    '((type . "prefill")
      (message . "edited prompt")
      (notice . "Undid one turn")))
   (should (equal (hermes-chat-input-string) "edited prompt"))
   (should (string-match-p "Undid one turn" (buffer-string)))))

(ert-deftest hermes-chat-slash-resume-running-skill-queues ()
  (let ((client (hermes-test--dashboard-client)) submit-text queued-result)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-resume)
               (lambda (_client session-id &rest args)
                 (should (equal session-id "stored-session"))
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-live")
                            (resumed . "stored-session")
                            (running . t)
                            (inflight . ((user . "remote prompt")
                                         (assistant . "")
                                         (streaming . t)))))))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (_client text &rest args)
                 (setq submit-text text)
                 (when-let* ((resolve (plist-get args :resolve)))
                   (funcall resolve '((status . "streaming"))))))
              ((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (_client _command &rest args)
                 (funcall (plist-get args :reject)
                          "skill command uses command.dispatch")))
              ((symbol-function 'hermes-dashboard-transport-command-dispatch)
               (lambda (_client _name _arg &rest args)
                 (funcall (plist-get args :resolve)
                          '((type . "skill")
                            (name . "demo")
                            (message . "use demo skill while remote turn runs"))))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--session-id "stored-session")
       (insert "/demo now")
       (hermes-chat-send)
       (setq queued-result (car (hermes-test--queued-contents)))
       (should-not submit-text)
       (should (equal queued-result "use demo skill while remote turn runs"))
       (should hermes-chat--pending-assistant-id)
       (should (string-match-p "Hermes session is still running"
                               (buffer-string)))
       (hermes-dashboard-transport--dispatch-event client
                '(:type done :session-id "sid-live"))
       (hermes-test--emit-dashboard-idle client "sid-live")
       (should (equal submit-text
                      "use demo skill while remote turn runs"))))))

(ert-deftest hermes-chat-slash-queue-resume-running-queues ()
  (let ((client (hermes-test--dashboard-client))
        dispatch-name dispatch-arg dispatch-session submits)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-resume)
               (lambda (_client session-id &rest args)
                 (should (equal session-id "stored-session"))
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-live")
                            (resumed . "stored-session")
                            (running . t)
                            (inflight . ((user . "remote prompt")
                                         (assistant . "")
                                         (streaming . t)))))))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (_client text &rest args)
                 (push text submits)
                 (when-let* ((resolve (plist-get args :resolve)))
                   (funcall resolve '((status . "streaming"))))))
              ((symbol-function 'hermes-dashboard-transport-command-dispatch)
               (lambda (_client name arg &rest args)
                 (setq dispatch-name name
                       dispatch-arg arg
                       dispatch-session (plist-get args :session-id))
                 (funcall (plist-get args :resolve)
                          '((type . "send")
                            (message . "queued prompt"))))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--session-id "stored-session")
       (insert "/queue queued prompt")
       (hermes-chat-send)
       (should (equal dispatch-name "queue"))
       (should (equal dispatch-arg "queued prompt"))
       (should (equal dispatch-session "sid-live"))
       (should-not submits)
       (should (equal (hermes-test--queued-contents) '("queued prompt")))
       (should hermes-chat--pending-assistant-id)
       (hermes-dashboard-transport--dispatch-event client
                '(:type done :session-id "sid-live"))
       (hermes-test--emit-dashboard-idle client "sid-live")
       (should (equal submits '("queued prompt")))
       (hermes-dashboard-transport--dispatch-event client
                '(:type done :session-id "sid-live"))
       (should (equal submits '("queued prompt")))))))

(ert-deftest hermes-chat-queue-message-resume-running-queues ()
  (let ((client (hermes-test--dashboard-client)) submits)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-resume)
               (lambda (_client session-id &rest args)
                 (should (equal session-id "stored-session"))
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-live")
                            (resumed . "stored-session")
                            (running . t)
                            (inflight . ((user . "remote prompt")
                                         (assistant . "")
                                         (streaming . t)))))))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (_client text &rest args)
                 (push text submits)
                 (when-let* ((resolve (plist-get args :resolve)))
                   (funcall resolve '((status . "streaming")))))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--session-id "stored-session")
       (hermes-chat-queue-message "queued via key")
       (should-not submits)
       (should (equal (hermes-test--queued-contents) '("queued via key")))
       (should hermes-chat--pending-assistant-id)
       (hermes-dashboard-transport--dispatch-event client
                '(:type done :session-id "sid-live"))
       (hermes-test--emit-dashboard-idle client "sid-live")
       (should (equal submits '("queued via key")))
       (hermes-dashboard-transport--dispatch-event client
                '(:type done :session-id "sid-live"))
       (should (equal submits '("queued via key")))))))

(ert-deftest hermes-chat-queue-message-resume-error-preserves-text ()
  (let ((client (hermes-test--dashboard-client)) submitted)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-resume)
               (lambda (_client session-id &rest args)
                 (should (equal session-id "stored-session"))
                 (when-let* ((reject (plist-get args :reject)))
                   (funcall reject "resume failed"))))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (&rest _args)
                 (setq submitted t))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--session-id "stored-session")
       (insert "queued via key")
       (hermes-chat-queue-message)
       (should-not submitted)
       (should (hermes-test--control-content-preserved-p "queued via key"))
       (should (string-match-p "resume failed" (buffer-string)))))))

(ert-deftest hermes-chat-slash-queue-resume-error-preserves-text ()
  (let ((client (hermes-test--dashboard-client)) dispatched submitted)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-resume)
               (lambda (_client session-id &rest args)
                 (should (equal session-id "stored-session"))
                 (when-let* ((reject (plist-get args :reject)))
                   (funcall reject "resume failed"))))
              ((symbol-function 'hermes-dashboard-transport-command-dispatch)
               (lambda (&rest _args)
                 (setq dispatched t)))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (&rest _args)
                 (setq submitted t))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--session-id "stored-session")
       (insert "/queue queued prompt")
       (hermes-chat-send)
       (should-not dispatched)
       (should-not submitted)
       (should (hermes-test--control-content-preserved-p
                "queued prompt" "/queue queued prompt"))
       (should (string-match-p "resume failed" (buffer-string)))))))

(ert-deftest hermes-chat-slash-queue-start-error-preserves-text ()
  (let (dispatched signaled)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args)
                 (user-error "dashboard failed")))
              ((symbol-function 'hermes-dashboard-transport-command-dispatch)
               (lambda (&rest _args)
                 (setq dispatched t))))
      (hermes-test-with-chat-buffer
       (insert "/queue queued prompt")
       (condition-case err
           (hermes-chat-send)
         (error (setq signaled (error-message-string err))))
       (should-not signaled)
       (should-not dispatched)
       (should (hermes-test--control-content-preserved-p
                "queued prompt" "/queue queued prompt"))
       (should (string-match-p "dashboard failed" (buffer-string)))))))

(ert-deftest hermes-chat-slash-queue-create-error-preserves-text ()
  (let ((client (hermes-test--dashboard-client)) dispatched signaled)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-create)
               (lambda (_client &rest args)
                 (when-let* ((reject (plist-get args :reject)))
                   (funcall reject "create failed"))))
              ((symbol-function 'hermes-dashboard-transport-command-dispatch)
               (lambda (&rest _args)
                 (setq dispatched t))))
      (hermes-test-with-chat-buffer
       (insert "/queue queued prompt")
       (condition-case err
           (hermes-chat-send)
         (error (setq signaled (error-message-string err))))
       (should-not signaled)
       (should-not dispatched)
       (should (hermes-test--control-content-preserved-p
                "queued prompt" "/queue queued prompt"))
       (should (string-match-p "create failed" (buffer-string)))))))

(ert-deftest hermes-chat-slash-steer-resume-error-preserves-text ()
  (let ((client (hermes-test--dashboard-client)) steered submitted)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-resume)
               (lambda (_client session-id &rest args)
                 (should (equal session-id "stored-session"))
                 (when-let* ((reject (plist-get args :reject)))
                   (funcall reject "resume failed"))))
              ((symbol-function 'hermes-dashboard-transport-session-steer)
               (lambda (&rest _args)
                 (setq steered t)))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (&rest _args)
                 (setq submitted t))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--session-id "stored-session")
       (insert "/steer adjust current run")
       (hermes-chat-send)
       (should-not steered)
       (should-not submitted)
       (should (hermes-test--control-content-preserved-p
                "adjust current run" "/steer adjust current run"))
       (should (string-match-p "resume failed" (buffer-string)))))))

(ert-deftest hermes-chat-queue-message-start-error-preserves-text ()
  (let (signaled)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args)
                 (user-error "dashboard failed"))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--session-id "stored-session")
       (insert "queued before start")
       (condition-case err
           (hermes-chat-queue-message)
         (error (setq signaled (error-message-string err))))
       (should-not signaled)
       (should (hermes-test--control-content-preserved-p
                "queued before start"))
       (should (string-match-p "dashboard failed" (buffer-string)))))))

(ert-deftest hermes-chat-slash-start-error-preserves-text ()
  (let (signaled)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args)
                 (user-error "dashboard failed"))))
      (hermes-test-with-chat-buffer
       (insert "/demo arg")
       (condition-case err
           (hermes-chat-send)
         (error (setq signaled (error-message-string err))))
       (should-not signaled)
       (should (hermes-test--control-content-preserved-p "/demo arg"))
       (should (string-match-p "dashboard failed" (buffer-string)))))))

(ert-deftest hermes-chat-slash-create-error-preserves-text ()
  (let ((client (hermes-test--dashboard-client)) signaled slash-ran)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-create)
               (lambda (_client &rest args)
                 (when-let* ((reject (plist-get args :reject)))
                   (funcall reject "create failed"))))
              ((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (&rest _args)
                 (setq slash-ran t))))
      (hermes-test-with-chat-buffer
       (insert "/demo arg")
       (condition-case err
           (hermes-chat-send)
         (error (setq signaled (error-message-string err))))
       (should-not signaled)
       (should-not slash-ran)
       (should (hermes-test--control-content-preserved-p "/demo arg"))
       (should (string-match-p "create failed" (buffer-string)))))))

(ert-deftest hermes-chat-slash-steer-start-error-preserves-text ()
  (let (signaled)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args)
                 (user-error "dashboard failed"))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--session-id "stored-session")
       (insert "/steer adjust before start")
       (condition-case err
           (hermes-chat-send)
         (error (setq signaled (error-message-string err))))
       (should-not signaled)
       (should (hermes-test--control-content-preserved-p
                "adjust before start" "/steer adjust before start"))
       (should (string-match-p "dashboard failed" (buffer-string)))))))

(ert-deftest hermes-chat-slash-steer-resume-running-steers ()
  (let ((client (hermes-test--dashboard-client))
        steer-session steer-text submit-text)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-resume)
               (lambda (_client session-id &rest args)
                 (should (equal session-id "stored-session"))
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-live")
                            (resumed . "stored-session")
                            (running . t)
                            (inflight . ((user . "remote prompt")
                                         (assistant . "")
                                         (streaming . t)))))))
              ((symbol-function 'hermes-dashboard-transport-prompt-submit)
               (lambda (_client text &rest _args)
                 (setq submit-text text)))
              ((symbol-function 'hermes-dashboard-transport-session-steer)
               (lambda (_client text &rest args)
                 (setq steer-session (plist-get args :session-id)
                       steer-text text)
                 (funcall (plist-get args :resolve)
                          '((status . "queued"))))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--session-id "stored-session")
       (insert "/steer adjust current run")
       (hermes-chat-send)
       (should-not submit-text)
       (should (equal steer-session "sid-live"))
       (should (equal steer-text "adjust current run"))
       (should (string-match-p "Steering: adjust current run" (buffer-string)))))))

(ert-deftest hermes-chat-command-alias-dispatches-target ()
  (let ((client (hermes-test--dashboard-client)) dispatches)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-create)
               (lambda (_client &rest args)
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-active")))))
              ((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (_client _command &rest args)
                 (funcall (plist-get args :reject)
                          "use command.dispatch")))
              ((symbol-function 'hermes-dashboard-transport-command-dispatch)
               (lambda (_client name arg &rest args)
                 (push (cons name arg) dispatches)
                 (funcall (plist-get args :resolve)
                          (if (equal name "short")
                              '((type . "alias") (target . "demo"))
                            '((type . "exec") (output . "alias target ran")))))))
      (hermes-test-with-chat-buffer
       (insert "/short now")
       (hermes-chat-send)
       (should (equal (nreverse dispatches)
                      '(("goal" . "status")
                        ("short" . "now")
                        ("demo" . "now"))))
       (should (string-match-p "alias target ran" (buffer-string)))))))

(ert-deftest hermes-chat-command-output-renders-warning ()
  (hermes-test-with-chat-buffer
   (hermes-chat--handle-command-result
    '((type . "exec")
      (output . "command output")
      (warning . "command warning")))
   (let ((text (buffer-string)))
     (should (string-match-p "warning: command warning" text))
     (should (string-match-p "command output" text)))))

(ert-deftest hermes-chat-command-output-ignores-empty-body-fields ()
  (hermes-test-with-chat-buffer
   (hermes-chat--handle-command-result
    '((type . "exec")
      (output . "")
      (notice . "fallback notice")))
   (should (string-match-p "fallback notice" (buffer-string)))))

(ert-deftest hermes-chat-goal-command-refreshes-vanilla-state ()
  "A successful `/goal' command refreshes state through vanilla status output."
  (let ((client (hermes-test--dashboard-client)) status-queries)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (_client _command &rest args)
                 (funcall (plist-get args :resolve)
                          '((type . "exec") (output . "Goal paused")))))
              ((symbol-function 'hermes-dashboard-transport-command-dispatch)
               (lambda (_client name arg &rest args)
                 (push (cons name arg) status-queries)
                 (funcall (plist-get args :resolve)
                          '((type . "exec")
                            (output . "⏸ Goal (paused, 2/20 turns): Ship it"))))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-active"
             hermes-chat--dashboard-session-ready-p t)
       (insert "/goal pause")
       (hermes-chat-send)
       (should (equal status-queries '(("goal" . "status"))))
       (should-not (plist-get hermes-chat--goal :running))))))

(ert-deftest hermes-chat-compact-uses-session-compress ()
  "/compact uses session.compress and settles one progress line."
  (let ((client (hermes-test--dashboard-client))
        compress-args resolve)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (&rest _)
                 (ert-fail "compact must not use slash.exec")))
              ((symbol-function 'hermes-dashboard-transport-session-compress)
               (lambda (_client &rest args)
                 (setq compress-args args
                       resolve (plist-get args :resolve)))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-active"
             hermes-chat--dashboard-session-ready-p t)
       (hermes-chat--insert-entry (hermes-chat--make-entry 'user "hi"))
       (hermes-chat--insert-entry
        (hermes-chat--make-entry 'assistant "settled reply" 'done))
       (insert "/compact keep blobs")
       (hermes-chat-send)
       (should (equal (plist-get compress-args :session-id) "sid-active"))
       (should (equal (plist-get compress-args :focus-topic) "keep blobs"))
       (should (equal (mapcar (lambda (entry) (plist-get entry :role))
                             (hermes-chat--entries))
                      '(user assistant status)))
       (should (string-match-p "Compressing" (buffer-string)))
       (hermes-chat--run-turn-reducer
        "a1" '(:type status :event "status.update" :status "compressing"
                     :session-id "sid-active"
                     :content "compressing 12 messages (~4,000 tok)…"))
       (let ((lines (ewoc-collect
                     hermes-chat--ewoc
                     (lambda (entry)
                       (eq (plist-get entry :role) 'status)))))
         (should (= 1 (length lines)))
         (should (string-match-p "4,000" (plist-get (car lines) :content))))
       (funcall resolve
                '((status . "compressed")
                  (summary . ((headline . "Compressed: 40 → 12 messages")
                              (token_line . "Approx request size: ~120,000 → ~40,000 tokens")))))
       (should (string-match-p "Compressed: 40 → 12" (buffer-string)))
       (should (string-match-p "120,000" (buffer-string)))
       (should-not (string-match-p "Compressing" (buffer-string)))
       (should (= 1 (length
                     (ewoc-collect
                      hermes-chat--ewoc
                      (lambda (entry)
                        (eq (plist-get entry :role) 'status))))))))))

(ert-deftest hermes-chat-compact-reject-settles-progress-line ()
  "A rejected session.compress replaces the pending compress line."
  (let ((client (hermes-test--dashboard-client)) reject)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (&rest _)
                 (ert-fail "compact must not use slash.exec")))
              ((symbol-function 'hermes-dashboard-transport-session-compress)
               (lambda (_client &rest args)
                 (setq reject (plist-get args :reject)))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-active"
             hermes-chat--dashboard-session-ready-p t)
       (insert "/compress")
       (hermes-chat-send)
       (should (string-match-p "Compressing" (buffer-string)))
       (funcall reject "session busy — /interrupt the current turn before /compress")
       (should (string-match-p "session busy" (buffer-string)))
       (should-not (string-match-p "Compressing" (buffer-string)))))))

(ert-deftest hermes-chat-compact-ignores-stale-session-result ()
  "A late session.compress result does not settle a successor chat."
  (let ((client (hermes-test--dashboard-client)) resolve)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (&rest _)
                 (ert-fail "compact must not use slash.exec")))
              ((symbol-function 'hermes-dashboard-transport-session-compress)
               (lambda (_client &rest args)
                 (setq resolve (plist-get args :resolve)))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-active"
             hermes-chat--dashboard-session-ready-p t)
       (insert "/compact")
       (hermes-chat-send)
       (setq hermes-chat--lifecycle-generation
             (hermes-chat--next-lifetime-token))
       (funcall resolve
                '((summary . ((headline . "Compressed: 40 → 12 messages")))))
       (should (string-match-p "Compressing" (buffer-string)))
       (should-not (string-match-p "Compressed: 40" (buffer-string)))))))

(ert-deftest hermes-chat-reasoning-command-mutates-live-session ()
  "`/reasoning' sets and reads back the owned dashboard session."
  (let ((client (hermes-test--dashboard-client)) set-args get-args)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (&rest _args)
                 (ert-fail "Reasoning must not run in the isolated slash worker")))
              ((symbol-function 'hermes-dashboard-transport-config-set)
               (lambda (_client key value &rest args)
                 (setq set-args (list key value
                                      (plist-get args :session-id)))
                 (funcall (plist-get args :resolve) '((value . "ultra")))))
              ((symbol-function 'hermes-dashboard-transport-config-get)
               (lambda (_client key &rest args)
                 (setq get-args (list key (plist-get args :session-id)))
                 (funcall (plist-get args :resolve) '((value . "ultra"))))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-active"
             hermes-chat--dashboard-session-ready-p t
             hermes-chat--runtime-flags '(:reasoning-effort "high"))
       (insert "/reasoning ultra")
       (hermes-chat-send)
       (should (equal set-args '("reasoning" "ultra" "sid-active")))
       (should (equal get-args '("reasoning" "sid-active")))
       (should-not
        (cl-find-if (lambda (entry)
                      (and (eq (plist-get entry :role) 'status)
                           (string-match-p "Reasoning set"
                                           (or (plist-get entry :content) ""))))
                    (hermes-chat--entries)))
       (should (equal (plist-get hermes-chat--runtime-flags :reasoning-effort)
                      "ultra"))
       (should-not (string-match-p "ultra" (hermes-test--header-line-string)))
       (should (string-match-p "ultra" (hermes-chat--session-details-text)))
       (should-not (string-match-p "high" (hermes-test--header-line-string)))))))

(ert-deftest hermes-chat-reasoning-query-follows-public-setter-readback ()
  "A public effort pick, readback, and bare query share one session authority."
  (let ((client (hermes-test--dashboard-client))
        (efforts (make-hash-table :test #'equal))
        (undo-in-region nil) (last-command nil)
        (undo-equiv-table (make-hash-table :test #'eq)) requests query-resolve)
    ;; Keep the public setter, typed RPCs, command owner, and renderer real.
    (cl-letf (((symbol-function 'hermes-dashboard-transport-request)
               (lambda (sent-client method params resolve &optional _reject)
                 (push method requests)
                 (should (eq sent-client client))
                 (should (equal (alist-get 'key params) "reasoning"))
                 (should (equal (alist-get 'session_id params) "sid-active"))
                 (pcase method
                   ("config.set"
                    (puthash (alist-get 'session_id params)
                             (alist-get 'value params) efforts)
                    (funcall resolve `((value . ,(alist-get 'value params)))))
                   ("config.get"
                    (if hermes-chat--command-owner
                        (setq query-resolve resolve)
                      (funcall resolve
                               `((value . ,(gethash "sid-active" efforts))
                                 (display . "hide")))))
                   (_ (ert-fail "Bare reasoning must not use slash.exec"))))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-active"
             hermes-chat--dashboard-session-ready-p t)
       (dolist (effort '("max" "xhigh"))
         (hermes-chat-set-reasoning effort)
         (should (equal (gethash "sid-active" efforts) effort))
         (should (equal (plist-get hermes-chat--runtime-flags :reasoning-effort)
                        effort))
         (should-not hermes-chat--command-owner)
         (insert "/reasoning")
         (hermes-chat-send)
         (should-not (member "slash.exec" requests))
         (should hermes-chat--command-owner)
         (should (functionp query-resolve))
         (undo-boundary)
         (insert "new draft α")
         (undo-boundary)
         (let ((undo buffer-undo-list)
               (point-offset (- (point) (hermes-chat--input-position))))
           (funcall query-resolve `((value . ,(gethash "sid-active" efforts))
                                   (display . "hide")))
           (should-not hermes-chat--command-owner)
           (should (equal (hermes-chat-input-string) "new draft α"))
           (should (eq buffer-undo-list undo))
           (should (= (- (point) (hermes-chat--input-position)) point-offset))
           (let ((transcript (buffer-substring (point-min) hermes-chat--input-marker)))
             (hermes-test--draft-undo-command #'undo-only)
             (should (equal (hermes-chat-input-string) ""))
             (hermes-test--draft-undo-command #'undo-redo)
             (should (equal (hermes-chat-input-string) "new draft α"))
             (should (equal (buffer-substring (point-min) hermes-chat--input-marker)
                            transcript)))
           (should (string-match-p (concat "Reasoning effort:  " effort)
                                   (buffer-string)))
           (should (string-match-p "Reasoning display: off" (buffer-string)))
           (should-not (string-match-p "clamped to\\|medium" (buffer-string))))
         (hermes-chat--delete-input-tail))
       (should (equal (nreverse requests)
                      '("config.set" "config.get" "config.get"
                        "config.set" "config.get" "config.get")))))))

(ert-deftest hermes-chat-reasoning-query-reports-only-returned-fields ()
  "Reasoning reports distinguish missing values, disabled effort, and display."
  (dolist (case '((nil "unknown" "unknown")
                  (((value . "max")) "max" "unknown")
                  (((display . "show")) "unknown" "on")
                  (((value . "none") (display . "hide")) "none (disabled)" "off")
                  (((value . "") (display . "")) "unknown" "unknown")
                  (((value . "future-effort") (display . "future-display"))
                   "future-effort" "future-display")))
    (let ((expected (format "Reasoning effort:  %s\nReasoning display: %s"
                            (nth 1 case) (nth 2 case))))
      (should (equal (hermes-chat--reasoning-report (car case)) expected))))
  (should (equal (hermes-chat--reasoning-report
                  '(:value "medium" :display "show"))
                 "Reasoning effort:  medium\nReasoning display: on"))
  (let ((result (make-hash-table :test #'equal)))
    (puthash "value" "xhigh" result)
    (puthash "display" "hide" result)
    (puthash "reasoning_full" t result)
    (should (equal (hermes-chat--reasoning-report result)
                   "Reasoning effort:  xhigh\nReasoning display: off"))))

(ert-deftest hermes-chat-reasoning-query-settles-rejection-and-stale-callbacks ()
  "A query settles once and cannot paint or release a successor's owner."
  (dolist (terminal '(reject session disconnect kill))
    (let ((client (hermes-test--dashboard-client)) resolve reject)
      (cl-letf (((symbol-function 'hermes-dashboard-transport-request)
                 (lambda (_client method params on-success on-error)
                   (should (equal method "config.get"))
                   (should (equal params '((key . "reasoning")
                                          (session_id . "sid-active"))))
                   (setq resolve on-success reject on-error))))
        (hermes-test-with-chat-buffer
         (setq hermes-chat--dashboard-client client
               hermes-chat--dashboard-active-session-id "sid-active"
               hermes-chat--dashboard-session-ready-p t
               hermes-chat--runtime-flags '(:reasoning-effort "low"))
         (insert "/reasoning")
         (hermes-chat-send)
         (should hermes-chat--command-owner)
         (pcase terminal
           ('reject (funcall reject "Reasoning query rejected"))
           ('session
            (setq hermes-chat--dashboard-active-session-id "sid-new")
            (funcall resolve '((value . "max") (display . "hide"))))
           ('disconnect (hermes-chat-disconnect))
           ('kill (kill-buffer (current-buffer))))
         (if (eq terminal 'kill)
             (with-temp-buffer
               (insert "Unrelated buffer")
               (funcall resolve '((value . "max") (display . "show")))
               (funcall reject "late failure")
               (should (equal (buffer-string) "Unrelated buffer")))
           (should-not hermes-chat--command-owner)
           (should (equal (plist-get hermes-chat--runtime-flags :reasoning-effort)
                          "low"))
           (when (eq terminal 'reject)
             (should (string-match-p "Reasoning query rejected" (buffer-string)))
             (should (eq (plist-get hermes-chat--status-state :status) 'error)))
           (let ((owner (hermes-chat--command-start))
                 (text (buffer-string))
                 (undo (copy-tree buffer-undo-list)))
             (funcall resolve '((value . "max") (display . "show")))
             (funcall reject "late failure")
             (should (eq hermes-chat--command-owner owner))
             (should (equal (buffer-string) text))
             (should (equal buffer-undo-list undo)))))))))

(ert-deftest hermes-chat-reasoning-query-transport-error-and-timeout ()
  "Real RPC rejection and timeout release the query without a worker fallback."
  (dolist (failure '(error timeout stop))
    (let ((client (hermes-test--dashboard-client)) frames
          (hermes-dashboard-transport-websocket-close-function #'ignore))
      (let ((hermes-dashboard-transport-websocket-send-function
             (lambda (_socket frame) (push frame frames))))
        (hermes-test-with-chat-buffer
         (setq hermes-chat--dashboard-client client
               hermes-chat--dashboard-active-session-id "sid-active"
               hermes-chat--dashboard-session-ready-p t)
         (insert "/reasoning")
         (hermes-chat-send)
         (let* ((pending (hermes-dashboard-transport-client-pending client))
                (id (car (hash-table-keys pending)))
                (request (gethash id pending)))
           (should (= (length frames) 1))
           (should (equal (plist-get request :method) "config.get"))
           (should hermes-chat--command-owner)
           (pcase failure
             ('error
              (hermes-dashboard-transport--handle-frame
               client (hermes-dashboard-transport--encode-frame
                       `((jsonrpc . "2.0") (id . ,id)
                         (error . ((code . 4002) (message . "Reasoning unavailable")))))))
             ('timeout (hermes-dashboard-transport--on-request-timeout client id))
             ('stop (hermes-dashboard-transport-stop client "Socket closed")))
           (should (= (hash-table-count pending) 0))
           (should-not hermes-chat--command-owner)
           (should-not hermes-chat--runtime-flags)
           (should (eq (plist-get hermes-chat--status-state :status) 'error))
           (should (string-match-p
                    (pcase failure
                      ('error "Reasoning unavailable")
                      ('timeout "[Tt]ime")
                      ('stop "Socket closed"))
                    (buffer-string)))
           (should (= (length frames) 1))))))))

(ert-deftest hermes-chat-reasoning-query-keeps-busy-guards ()
  "Existing exclusive command, handoff, and creation guards refuse a bare query."
  (dolist (busy '(handoff creation command))
    (cl-letf (((symbol-function 'hermes-dashboard-transport-request)
               (lambda (&rest _) (ert-fail "Busy query must not dispatch"))))
      (hermes-test-with-chat-buffer
       (pcase busy
         ('handoff (setq hermes-chat--handoff-owner 'handoff))
         ('creation (setq hermes-chat--create-override-owner 'creation))
         ('command (hermes-chat--command-start)))
       (insert "/reasoning")
       (let ((text (buffer-string)) (undo (copy-tree buffer-undo-list)))
         (should-error (hermes-chat-send) :type 'user-error)
         (should (equal (buffer-string) text))
         (should (equal buffer-undo-list undo)))))))

(ert-deftest hermes-chat-reasoning-query-preserves-argument-routing ()
  "Only a bare query changes route; display, effort, and flag handling stays put."
  (dolist (case '(("max --session" "config.set" "max" "sid-active")
                  ("xhigh --global" "config.set" "xhigh" nil)
                  ("show" "config.set" "show" "sid-active")
                  ("hide" "config.set" "hide" "sid-active")
                  ("full" "config.set" "full" "sid-active")
                  ("clamp" "config.set" "clamp" "sid-active")
                  ("unknown" "config.set" "unknown" "sid-active")
                  ("--global" "slash.exec" nil "sid-active")
                  ("--session" "slash.exec" nil "sid-active")))
    (let ((client (hermes-test--dashboard-client)) request)
      (cl-letf (((symbol-function 'hermes-dashboard-transport-request)
                 (lambda (_client method params _resolve _reject)
                   (setq request (list method params)))))
        (hermes-test-with-chat-buffer
         (setq hermes-chat--dashboard-client client
               hermes-chat--dashboard-active-session-id "sid-active"
               hermes-chat--dashboard-session-ready-p t)
         (insert (concat "/reasoning " (car case)))
         (hermes-chat-send)
         (should (equal (car request) (nth 1 case)))
         (should (equal (alist-get 'value (cadr request)) (nth 2 case)))
         (should (equal (alist-get 'session_id (cadr request)) (nth 3 case)))
         (when (equal (car request) "slash.exec")
           (should (equal (alist-get 'command (cadr request))
                          (concat "reasoning " (car case))))))))))

(ert-deftest hermes-chat-reasoning-request-projects-scope ()
  "Reasoning arguments project to one value and optional global scope."
  (should (equal (hermes-chat--reasoning-request "ultra --session")
                 '("ultra")))
  (should (equal (hermes-chat--reasoning-request "--global ultra")
                 '("ultra" . "global"))))

(ert-deftest hermes-chat-global-reasoning-omits-live-session ()
  "Global reasoning uses `config.set' without scoping it to the live session."
  (let ((client (hermes-test--dashboard-client)) request)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-config-set)
               (lambda (_client key value &rest args)
                 (setq request
                       (list key value (plist-get args :session-id)))
                 (funcall (plist-get args :resolve) nil)))
              ((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (&rest _args)
                 (ert-fail "Global reasoning must use config.set"))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-active"
             hermes-chat--dashboard-session-ready-p t)
       (insert "/reasoning ultra --global")
       (hermes-chat-send)
       (should (equal request '("reasoning" "ultra" nil)))))))

(ert-deftest hermes-chat-model-command-sets-explicit-model-on-live-session ()
  "`/model MODEL' uses typed config.set without opening the model picker."
  (let ((client (hermes-test--dashboard-client)) request)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-config-set)
               (lambda (_client key value &rest args)
                 (setq request
                       (list key value (plist-get args :session-id)
                             (plist-get args :confirm-expensive-model)))
                 (funcall (plist-get args :resolve)
                          `((value . ,value)))))
              ((symbol-function 'hermes-chat-switch-model)
               (lambda (&rest _args)
                 (ert-fail "Explicit /model must not open completing-read")))
              ((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (&rest _args)
                 (ert-fail "Explicit /model must not use slash.exec"))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-active"
             hermes-chat--dashboard-session-ready-p t)
       (insert "/model gpt-5.6 --provider openai-codex")
       (hermes-chat-send)
       (should (equal request
                      '("model" "gpt-5.6 --provider openai-codex"
                        "sid-active" nil)))
       (should-not hermes-chat--command-owner)
       (should (string-match-p "Model set to gpt-5.6"
                               (buffer-string)))))))

(ert-deftest hermes-chat-model-command-confirms-expensive-model ()
  "`/model MODEL' retries an expensive switch only after confirmation."
  (let ((client (hermes-test--dashboard-client))
        (calls 0)
        confirms)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-config-set)
               (lambda (_client _key _value &rest args)
                 (cl-incf calls)
                 (push (plist-get args :confirm-expensive-model) confirms)
                 (funcall (plist-get args :resolve)
                          (if (= calls 1)
                              '((confirm_required . t)
                                (confirm_message . "Expensive model"))
                            '((value . "gpt-5.6"))))))
              ((symbol-function 'yes-or-no-p) (lambda (_prompt) t)))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-active"
             hermes-chat--dashboard-session-ready-p t)
       (insert "/model gpt-5.6 --provider openai-codex")
       (hermes-chat-send)
       (should (= calls 2))
       (should (equal (nreverse confirms) '(nil t)))
       (should-not hermes-chat--command-owner)))))

(ert-deftest hermes-chat-model-command-does-not-confirm-into-replacement-session ()
  "An expensive confirmation cannot redirect its retry to a replacement session."
  (let ((client (hermes-test--dashboard-client)) calls)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-config-set)
               (lambda (_client _key _value &rest args)
                 (push (plist-get args :session-id) calls)
                 (funcall (plist-get args :resolve)
                          '((confirm_required . t)
                            (confirm_message . "Expensive model")))))
              ((symbol-function 'yes-or-no-p)
               (lambda (_prompt)
                 (setq hermes-chat--dashboard-active-session-id "sid-new")
                 t)))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-old"
             hermes-chat--dashboard-session-ready-p t)
       (insert "/model gpt-5.6 --provider openai-codex")
       (hermes-chat-send)
       (should (equal (nreverse calls) '("sid-old")))
       (should-not hermes-chat--command-owner)))))

(ert-deftest hermes-chat-model-command-stale-confirmation-releases-owner ()
  "A confirmation response for a replaced session cannot leave ownership stuck."
  (let ((client (hermes-test--dashboard-client)) resolve prompted)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-config-set)
               (lambda (_client _key _value &rest args)
                 (setq resolve (plist-get args :resolve))))
              ((symbol-function 'yes-or-no-p)
               (lambda (_prompt) (setq prompted t))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-old"
             hermes-chat--dashboard-session-ready-p t)
       (insert "/model gpt-5.6 --provider openai-codex")
       (hermes-chat-send)
       (setq hermes-chat--dashboard-active-session-id "sid-new")
       (funcall resolve '((confirm_required . t)))
       (should-not prompted)
       (should-not hermes-chat--command-owner)))))

(ert-deftest hermes-chat-model-command-without-argument-keeps-picker ()
  "Bare `/model' retains the interactive cached model picker."
  (let (picked)
    (cl-letf (((symbol-function 'hermes-chat-switch-model)
               (lambda (&rest _args) (setq picked t))))
      (hermes-test-with-chat-buffer
       (insert "/model")
       (hermes-chat-send)
       (should picked)))))

(ert-deftest hermes-chat-reasoning-settlement-ignores-stale-session ()
  "A late reasoning setter cannot read into a replacement session."
  (let ((client (hermes-test--dashboard-client)) resolve-set config-gets)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-config-set)
               (lambda (_client _key _value &rest args)
                 (setq resolve-set (plist-get args :resolve))))
              ((symbol-function 'hermes-dashboard-transport-config-get)
               (lambda (&rest _args) (cl-incf config-gets))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-old"
             hermes-chat--dashboard-session-ready-p t
             hermes-chat--runtime-flags '(:reasoning-effort "low")
             config-gets 0)
       (insert "/reasoning high")
       (hermes-chat-send)
       (setq hermes-chat--dashboard-active-session-id "sid-new")
       (funcall resolve-set '((value . "high")))
       (should (= config-gets 0))
       (should (equal (plist-get hermes-chat--runtime-flags :reasoning-effort)
                      "low"))))))

(ert-deftest hermes-chat-reasoning-readback-ignores-stale-session ()
  "A late reasoning readback cannot overwrite a replacement session."
  (let ((client (hermes-test--dashboard-client)) resolve-get)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-config-set)
               (lambda (_client _key _value &rest args)
                 (funcall (plist-get args :resolve) '((value . "high")))))
              ((symbol-function 'hermes-dashboard-transport-config-get)
               (lambda (_client _key &rest args)
                 (setq resolve-get (plist-get args :resolve)))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-old"
             hermes-chat--dashboard-session-ready-p t
             hermes-chat--runtime-flags '(:reasoning-effort "low"))
       (insert "/reasoning high")
       (hermes-chat-send)
       (setq hermes-chat--dashboard-active-session-id "sid-new")
       (funcall resolve-get '((value . "high")))
       (should (equal (plist-get hermes-chat--runtime-flags :reasoning-effort)
                      "low"))))))

(ert-deftest hermes-chat-reasoning-rejection-preserves-effective-state ()
  "A rejected reasoning setter preserves the previous effective effort."
  (let ((client (hermes-test--dashboard-client)))
    (cl-letf (((symbol-function 'hermes-dashboard-transport-config-set)
               (lambda (_client _key _value &rest args)
                 (funcall (plist-get args :reject) "reasoning rejected")))
              ((symbol-function 'hermes-dashboard-transport-config-get)
               (lambda (&rest _args)
                 (ert-fail "Rejected setter must not read reasoning"))))
      (hermes-test-with-chat-buffer
       (setq hermes-chat--dashboard-client client
             hermes-chat--dashboard-active-session-id "sid-active"
             hermes-chat--dashboard-session-ready-p t
             hermes-chat--runtime-flags '(:reasoning-effort "low"))
       (insert "/reasoning high")
       (hermes-chat-send)
       (should (equal (plist-get hermes-chat--runtime-flags :reasoning-effort)
                      "low"))
       (should
        (cl-find-if (lambda (entry)
                      (and (eq (plist-get entry :role) 'status)
                           (eq (plist-get entry :status) 'error)
                           (equal (plist-get entry :content)
                                  "reasoning rejected")))
                    (hermes-chat--entries)))))))

(ert-deftest hermes-chat-command-dispatch-output-renders ()
  (let ((client (hermes-test--dashboard-client)) slash-command dispatch-name dispatch-arg)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-create)
               (lambda (_client &rest args)
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-active")))))
              ((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (_client command &rest args)
                 (setq slash-command command)
                 (funcall (plist-get args :reject)
                          "pending-input command: use command.dispatch")))
              ((symbol-function 'hermes-dashboard-transport-command-dispatch)
               (lambda (_client name arg &rest args)
                 (setq dispatch-name name
                       dispatch-arg arg)
                 (funcall (plist-get args :resolve)
                          '((type . "exec")
                            (output . "dispatch output"))))))
      (hermes-test-with-chat-buffer
       (insert "/foo dispatch output")
       (hermes-chat-send)
       (should (equal slash-command "foo dispatch output"))
       (should (equal dispatch-name "foo"))
       (should (equal dispatch-arg "dispatch output"))
       (should (string-match-p "dispatch output" (buffer-string)))))))

(ert-deftest hermes-chat-command-dispatch-rejection-renders-error ()
  (let ((client (hermes-test--dashboard-client)) dispatch-name dispatch-arg)
    (cl-letf (((symbol-function 'hermes-dashboard-transport-start)
               (lambda (&rest _args) client))
              ((symbol-function 'hermes-dashboard-transport-session-create)
               (lambda (_client &rest args)
                 (funcall (plist-get args :resolve)
                          '((session_id . "sid-active")))))
              ((symbol-function 'hermes-dashboard-transport-slash-exec)
               (lambda (_client _command &rest args)
                 (funcall (plist-get args :reject)
                          "pending-input command: use command.dispatch")))
              ((symbol-function 'hermes-dashboard-transport-command-dispatch)
               (lambda (_client name arg &rest args)
                 (setq dispatch-name name
                       dispatch-arg arg)
                 (funcall (plist-get args :reject)
                          "unknown command: nope"))))
      (hermes-test-with-chat-buffer
       (insert "/nope argument")
       (hermes-chat-send)
       (should (equal dispatch-name "nope"))
       (should (equal dispatch-arg "argument"))
       (should (equal (plist-get hermes-chat--status-state :status) 'error))
       (should (string-match-p "unknown command: nope" (buffer-string)))))))

(provide 'hermes-chat-slash-tests)
;;; hermes-chat-slash-tests.el ends here
