;;; hermes-tool-setup-tests.el --- Tool setup tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'hermes-tool-setup)

(ert-deftest hermes-tool-setup-dispatch-fence-survives-auth-retry ()
  (with-temp-buffer
    (hermes-tool-setup-mode)
    (let ((first (hermes--promise-make)) (second (hermes--promise-make))
          (auth-count 0) (writes 0)
          (current-p (hermes-browser--dispatch-guard nil)))
      (cl-letf (((symbol-function 'hermes-dashboard-transport-api-auth-async)
                 (lambda (&rest _) (if (= (cl-incf auth-count) 1) first second)))
                ((symbol-function 'hermes-dashboard-transport--http-json-request-async)
                 (lambda (_)
                   (cl-incf writes)
                   (hermes--promise-rejected "HTTP 401")))
                ((symbol-function 'hermes-dashboard-transport--auth-error-p)
                 (lambda (_) t)))
        (hermes-dashboard-transport--api-request-1-async
         "DELETE" "/api/example" :retry t :base-url "http://example.test"
         :current-p current-p)
        (hermes--promise-resolve first '(:base-url "http://example.test"))
        (should (= auth-count 2))
        (should (= writes 1))
        (fundamental-mode)
        (hermes--promise-resolve second '(:base-url "http://example.test"))
        (should (= writes 1))))))

(ert-deftest hermes-tool-setup-mutation-acquisition-settles-and-retries ()
  (dolist (condition '(error quit))
    (dolist (replace '(nil t))
      (with-temp-buffer
        (hermes-tool-setup-mode)
        (setq hermes-instance (list :id "test" :name "test" :url "http://example.test"))
        (setq hermes-tool-setup--name "web")
        (let ((hermes-instances (list hermes-instance))
              (client (make-hermes-dashboard-transport-client :base-url "http://example.test"))
              (successor (list 'successor)) (attempts 0) (released 0))
          (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                    ((symbol-function 'hermes-browser--existing-client) (lambda () nil))
                    ((symbol-function 'hermes-dashboard-transport-acquire)
                     (lambda (&rest _)
                       (cl-incf attempts)
                       (if (> attempts 1) client
                         (when replace
                           (hermes-browser--next-request-generation)
                           (setq hermes-tool-setup--busy successor))
                         (signal condition '("acquisition failed")))))
                    ((symbol-function 'hermes-dashboard-transport-release)
                     (lambda (_) (cl-incf released)))
                    ((symbol-function 'hermes-dashboard-transport-api-request-async)
                     (lambda (&rest _) (hermes--promise-resolved '(:ok t))))
                    ((symbol-function 'hermes-tool-setup-refresh) #'ignore))
            (should (eq condition
                        (condition-case err
                            (progn (hermes-tool-setup--change "/env" nil "Save? ") nil)
                          ((error quit) (car err)))))
            (if replace
                (should (eq hermes-tool-setup--busy successor))
              (should-not hermes-tool-setup--busy)
              (hermes-tool-setup--change "/env" nil "Save? ")
              (should (= attempts 2))
              (should (= released 1))
              (should-not hermes-tool-setup--busy))))))))

(ert-deftest hermes-tool-setup-mutation-delayed-auth-owner-fence ()
  (dolist (retire '(live kill mode instance instance-value generation client endpoint name profile))
    (with-temp-buffer
      (hermes-tool-setup-mode)
      (setq hermes-instance (list :name "test" :url "http://example.test"))
      (setq hermes-tool-setup--name "web")
      (let ((auth (hermes--promise-make))
            (client (make-hermes-dashboard-transport-client :base-url "http://example.test"))
            (released 0) writes)
        (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                  ((symbol-function 'hermes-browser--with-client)
                   (lambda (fn) (funcall fn client (lambda () (cl-incf released)))))
                  ((symbol-function 'hermes-dashboard-transport-api-auth-async)
                   (lambda (&rest _) auth))
                  ((symbol-function 'hermes-dashboard-transport--http-json-request-async)
                   (lambda (request)
                     (unless (equal (plist-get request :method) "GET")
                       (push request writes))
                     (hermes--promise-resolved '(:body (:ok t))))))
          (hermes-tool-setup--change "/env" '((env . ((KEY . "secret")))) "Save? "
                                     nil nil #'ignore)
          (should-not writes)
          (pcase retire
            ('name (setq hermes-tool-setup--name "other"))
            ('profile (setq hermes-tool-setup--profile "other"))
            ('kill (kill-buffer (current-buffer)))
            ('mode (fundamental-mode))
            ('instance (setq hermes-instance (copy-tree hermes-instance)))
            ('instance-value (setf (plist-get hermes-instance :url) "http://other.test"))
            ('generation (hermes-browser--next-request-generation))
            ('client (cl-incf (hermes-dashboard-transport-client-generation client)))
            ('endpoint (setf (hermes-dashboard-transport-client-base-url client)
                             "http://other.test")))
          (hermes--promise-resolve auth '(:base-url "http://example.test"))
          (should (= (length writes) (if (eq retire 'live) 1 0)))
          (should (= released 1)))))))

(ert-deftest hermes-tool-setup-schema-readiness ()
  (let* ((cfg '((providers . (((name . "Future") (status . "needs_auth")
                              (is_active . t) (env_vars . nil))
                             ((name . "Other") (status . "future_state"))))))
         (rows (hermes-tool-setup--rows cfg)))
    (should (equal (mapcar #'car rows) '("Future" "Other")))
    (should (equal (aref (cadar rows) 2) "needs_auth"))
    (should (equal (aref (cadr (cadr rows)) 2) "future_state"))))

(ert-deftest hermes-tool-setup-secret-save-and-readback ()
  (with-temp-buffer
    (hermes-tool-setup-mode)
    (setq hermes-tool-setup--name "future/tool"
          hermes-tool-setup--profile "second"
          hermes-tool-setup--config
          '((providers . (((name . "Future")
                           (env_vars . (((key . "FUTURE_KEY")))))))))
    (let (request refreshed)
      (cl-letf (((symbol-function 'hermes-tool-setup--provider)
                 (lambda () (car (hermes-transport--get hermes-tool-setup--config 'providers))))
                ((symbol-function 'read-passwd) (lambda (&rest _) "private-value"))
                ((symbol-function 'yes-or-no-p) (lambda (&rest _) t))
                ((symbol-function 'hermes-browser--run-on-client)
                 (lambda (make success &optional _error)
                   (funcall make 'client)
                   (funcall success '((ok . t)))))
                ((symbol-function 'hermes-dashboard-transport-api-request-async)
                 (lambda (&rest args) (setq request args)))
                ((symbol-function 'hermes-tool-setup-refresh)
                 (lambda (&rest _) (setq refreshed t))))
        (hermes-tool-setup-save-credentials)
        (should (equal (cadr request) "/api/tools/toolsets/future%2Ftool/env"))
        (should (equal (plist-get (cddr request) :query) '((profile . "second"))))
        (should (equal (plist-get (cddr request) :secrets) '("private-value")))
        (should refreshed)
        (should-not (string-match-p "private-value" (buffer-string)))))))


(ert-deftest hermes-tool-setup-failure-and-stale-settlement ()
  (dolist (replacement '(generation instance profile mode killed))
    (let ((buffer (generate-new-buffer " *setup-test*")) success failure changed notices)
      (unwind-protect
          (with-current-buffer buffer
            (hermes-tool-setup-mode)
            (setq hermes-tool-setup--name "future")
            (cl-letf (((symbol-function 'hermes-browser--run-on-client)
                       (lambda (_make ok &optional bad) (setq success ok failure bad)))
                      ((symbol-function 'message)
                       (lambda (&rest args) (push args notices))))
              (hermes-tool-setup--request "GET" "/config" (lambda (_) (setq changed t)))
              (pcase replacement
                ('generation (hermes-browser--next-request-generation))
                ('instance (setq hermes-instance 'other))
                ('profile (setq hermes-tool-setup--profile "other"))
                ('mode (fundamental-mode))
                ('killed (kill-buffer buffer)))
              (funcall success '((ok . t)))
              (funcall failure "secret-from-backend")
              (should-not changed)
              (should-not notices)))
        (when (buffer-live-p buffer) (kill-buffer buffer))))))

(ert-deftest hermes-tool-setup-refusal-rejection-and-prompt-race ()
  (dolist (outcome '(refused rejected declined changed))
    (with-temp-buffer
      (hermes-tool-setup-mode)
      (setq hermes-tool-setup--name "future")
      (let (refreshed dispatched notices)
        (cl-letf (((symbol-function 'yes-or-no-p)
                   (lambda (&rest _)
                     (when (eq outcome 'changed) (hermes-browser--next-request-generation))
                     (not (eq outcome 'declined))))
                  ((symbol-function 'hermes-browser--run-on-client)
                   (lambda (_make ok &optional bad)
                     (setq dispatched t)
                     (if (eq outcome 'rejected) (funcall bad "private-value")
                       (funcall ok '((ok . :false))))))
                  ((symbol-function 'hermes-tool-setup-refresh)
                   (lambda (&rest _) (setq refreshed t)))
                  ((symbol-function 'message) (lambda (&rest args) (push args notices))))
          (if (eq outcome 'changed)
              (should-error (hermes-tool-setup--change "/provider" nil "Change? ") :type 'user-error)
            (hermes-tool-setup--change "/provider" nil "Change? "))
          (should-not refreshed)
          (should-not hermes-tool-setup--busy)
          (when (memq outcome '(changed declined)) (should-not dispatched))
          (should-not (string-match-p "private-value" (format "%S" notices))))))))

(ert-deftest hermes-tool-setup-model-catalog-and-capability-routing ()
  (with-temp-buffer
    (hermes-tool-setup-mode)
    (setq hermes-tool-setup--name "future" hermes-tool-setup--profile "second")
    (let (requests changes)
      (cl-letf (((symbol-function 'hermes-tool-setup--provider)
                 (lambda () '((name . "Future") (capabilities . ("search" "extract")))) )
                ((symbol-function 'completing-read)
                 (lambda (_prompt choices &rest _) (if (consp (car choices)) (caar choices) (car choices))))
                ((symbol-function 'hermes-tool-setup--change)
                 (lambda (&rest args) (push args changes)))
                ((symbol-function 'hermes-browser--run-on-client)
                 (lambda (make ok &optional _bad)
                   (funcall make 'second-client)
                   (funcall ok '((has_models . t) (current . "m")
                                 (models . (((id . "m") (display . "Future Model"))))))))
                ((symbol-function 'hermes-dashboard-transport-api-request-async)
                 (lambda (&rest args) (push args requests))))
        (hermes-tool-setup-select-provider)
        (should (equal (cadar changes) '((provider . "Future") (capability . "search"))))
        (hermes-tool-setup-select-model)
        (should (equal (cadar changes) '((provider . "Future") (model . "m"))))
        (should (equal (plist-get (cddar requests) :query)
                       '((provider . "Future") (profile . "second"))))
        (should (eq (plist-get (cddar requests) :client) 'second-client))))))

(ert-deftest hermes-tool-setup-post-status-is-not-readiness ()
  (with-temp-buffer
    (hermes-tool-setup-mode)
    (setq hermes-tool-setup--name "future")
    (let (request refreshed)
      (cl-letf (((symbol-function 'hermes-browser--run-on-client)
                 (lambda (make ok &optional _bad)
                   (funcall make 'client)
                   (funcall ok '((running . :false) (exit_code . 1)))))
                ((symbol-function 'hermes-dashboard-transport-api-request-async)
                 (lambda (&rest args) (setq request args)))
                ((symbol-function 'hermes-tool-setup-refresh)
                 (lambda (&rest _) (setq refreshed t))))
        (hermes-tool-setup-post-setup-status)
        (should (equal (cadr request) "/api/actions/tools-post-setup/status"))
        (should (equal hermes-tool-setup--post-status "exited 1"))
        (should refreshed)
        (should-not hermes-tool-setup--config)))))


(ert-deftest hermes-tool-setup-public-open-keeps-instance-and-profile ()
  (let ((instance '("second" . "http://second.invalid")) buffer request)
    (unwind-protect
        (cl-letf (((symbol-function 'hermes-instance-resolve) (lambda () instance))
                  ((symbol-function 'pop-to-buffer) (lambda (value &rest _) (setq buffer value)))
                  ((symbol-function 'hermes-browser--run-on-client)
                   (lambda (make ok &optional _bad)
                     (should (equal hermes-instance instance))
                     (funcall make 'second-client)
                     (funcall ok '((has_category . t)
                                   (providers . (((name . "Future") (status . "needs_setup"))))))))
                  ((symbol-function 'hermes-dashboard-transport-api-request-async)
                   (lambda (&rest args) (setq request args))))
          (hermes-tool-setup "future" "second-profile")
          (should (equal (plist-get (cddr request) :query) '((profile . "second-profile"))))
          (with-current-buffer buffer
            (should (equal hermes-instance instance))
            (should (string-match-p "Future" (buffer-string)))
            (should (string-match-p "needs_setup" (buffer-string)))
            (should (string-match-p "second-profile" header-line-format))
            (should (eq (key-binding (kbd "k")) #'hermes-tool-setup-save-credentials))))
      (when (buffer-live-p buffer) (kill-buffer buffer)))))

(ert-deftest hermes-tool-setup-model-readback-detects-mismatch ()
  (with-temp-buffer
    (hermes-tool-setup-mode)
    (setq hermes-tool-setup--name "future" hermes-tool-setup--profile "second")
    (let (notice request refreshed)
      (cl-letf (((symbol-function 'hermes-browser--run-on-client)
                 (lambda (make ok &optional _bad)
                   (funcall make 'client)
                   (funcall ok '((current . "different")))))
                ((symbol-function 'hermes-dashboard-transport-api-request-async)
                 (lambda (&rest args) (setq request args)))
                ((symbol-function 'hermes-tool-setup-refresh) (lambda (&rest _) (setq refreshed t)))
                ((symbol-function 'message) (lambda (fmt &rest args) (setq notice (apply #'format fmt args)))))
        (hermes-tool-setup--verify-model "Future" "wanted")
        (should (equal (cadr request) "/api/tools/toolsets/future/models"))
        (should (equal (plist-get (cddr request) :query)
                       '((provider . "Future") (profile . "second"))))
        (should refreshed)
        (should (string-match-p "not confirmed" notice))))))

(ert-deftest hermes-tool-setup-install-requires-explicit-named-profile ()
  ;; Default on a named dashboard inherits its home; nil on a root dashboard
  ;; can reread a changed active_profile.  Neither is an exact install scope.
  (dolist (profile '("default" nil "current" " DEFAULT " "" "second"))
    (with-temp-buffer
      (hermes-tool-setup-mode)
      (setq hermes-tool-setup--name "future"
            hermes-tool-setup--profile profile)
      (let (request confirmed)
        (cl-letf (((symbol-function 'hermes-tool-setup--provider)
                   (lambda () '((name . "Future") (post_setup . "future-install"))))
                  ((symbol-function 'yes-or-no-p)
                   (lambda (&rest _) (setq confirmed t)))
                  ((symbol-function 'hermes-browser--run-on-client)
                   (lambda (make &rest _) (funcall make 'client)))
                  ((symbol-function 'hermes-dashboard-transport-api-request-async)
                   (lambda (&rest args) (setq request args))))
          (if (equal profile "second")
              (progn
                (hermes-tool-setup-run-post-setup)
                (should confirmed)
                (should (equal (car request) "POST"))
                (should (equal (cadr request) "/api/tools/toolsets/future/post-setup"))
                (should (equal (plist-get (cddr request) :query) '((profile . "second"))))
                (should (equal (plist-get (cddr request) :body) '((key . "future-install")))))
            (should-error (hermes-tool-setup-run-post-setup) :type 'user-error)
            (should-not request)
            (should-not confirmed)
            (should-not hermes-tool-setup--busy)))))))

(ert-deftest hermes-tool-setup-install-limitation-visible-in-panel ()
  (dolist (profile '(nil "default" "second"))
    (with-temp-buffer
      (hermes-tool-setup-mode)
      (setq hermes-tool-setup--name "future"
            hermes-tool-setup--profile profile)
      (cl-letf (((symbol-function 'hermes-browser--run-on-client)
                 (lambda (_make success &rest _) (funcall success nil))))
        (hermes-tool-setup-refresh)
        (should (eq (not (null (string-match-p "Install unavailable" header-line-format)))
                    (not (equal profile "second"))))))))


(ert-deftest hermes-tool-setup-popup-shows-reported-not-available-values ()
  "Two owners show their actual readback, with unknown and pending explicit."
  (save-window-excursion
    (dolist (name '("One" "Two"))
      (with-temp-buffer
        (switch-to-buffer (current-buffer))
        (hermes-tool-setup-mode)
        (setq hermes-tool-setup--name "image_gen"
              hermes-tool-setup--profile name)
        (let ((keymap-popup-backend #'keymap-popup-backend-side-window)
              (keymap-popup--buffer-name " *tool setup labels test*"))
          (unwind-protect
              (cl-letf (((symbol-function 'hermes-browser--run-on-client)
                         (lambda (_make ok &optional _bad)
                           (funcall ok
                                    (if hermes-tool-setup--config
                                        `((has_models . t) (provider . ,name)
                                          (current . ,(concat name "-model")))
                                      `((providers . (((name . ,name) (is_active . t))
                                                      ((name . "Available only") (status . "ready"))))))))))
                (hermes-tool-setup-refresh)
                (execute-kbd-macro (kbd "?"))
                (with-current-buffer keymap-popup--buffer-name
                  (should (string-match-p (concat "Provider: " name) (buffer-string)))
                  (should (string-match-p (concat "Model: " name "-model") (buffer-string)))
                  (should-not (string-match-p "Available only" (buffer-string))))
                (keymap-popup-dismiss)
                (setq hermes-tool-setup--config '((providers . (((name . "Available only") (status . "ready")))))
                      hermes-tool-setup--model-catalog '((default . "not-current")))
                (execute-kbd-macro (kbd "?"))
                (with-current-buffer keymap-popup--buffer-name
                  (should (string-match-p "Provider: unknown" (buffer-string)))
                  (should (string-match-p "Model: unknown" (buffer-string))))
                (keymap-popup-dismiss)
                (setq hermes-tool-setup--busy t)
                (execute-kbd-macro (kbd "?"))
                (with-current-buffer keymap-popup--buffer-name
                  (should (string-match-p "pending" (buffer-string)))))
            (keymap-popup-dismiss)))))))


(ert-deftest hermes-tool-setup-current-model-read-is-owned-and-provider-checked ()
  "Only an owning active-provider readback supplies the model label."
  (with-temp-buffer
    (hermes-tool-setup-mode)
    (setq hermes-tool-setup--name "image_gen" hermes-tool-setup--profile "second")
    (let (success failure request)
      (cl-letf (((symbol-function 'hermes-browser--run-on-client)
                 (lambda (make ok &optional bad)
                   (setq success ok failure bad)
                   (funcall make 'test-client)))
                ((symbol-function 'hermes-dashboard-transport-api-request-async)
                 (lambda (&rest args) (setq request args))))
        (hermes-tool-setup-refresh)
        (should (string-match-p "loading" (hermes-tool-setup--setting-description 'provider)))
        (funcall success '((providers . (((name . "Active") (is_active . t))
                                        ((name . "Inactive") (status . "ready"))))))
        (should (equal (cadr request) "/api/tools/toolsets/image_gen/models"))
        (should (equal (plist-get (cddr request) :query) '((profile . "second"))))
        (should (string-match-p "loading" (hermes-tool-setup--setting-description 'model)))
        (funcall success '((has_models . t) (provider . "Inactive") (current . "not-active")))
        (should (string-match-p "unknown" (hermes-tool-setup--setting-description 'model)))
        (hermes-tool-setup-refresh)
        (funcall failure "test failure")
        (should (string-match-p "unknown" (hermes-tool-setup--setting-description 'provider)))
        (should (string-match-p "unknown" (hermes-tool-setup--setting-description 'model)))
        (hermes-tool-setup-refresh)
        (let ((old-success success))
          (hermes-browser--next-request-generation)
          (funcall old-success '((active_provider . "Stale")))
          (should-not hermes-tool-setup--config)
          (should (string-match-p "unknown" (hermes-tool-setup--setting-description 'provider))))))))

(ert-deftest hermes-tool-setup-multiple-and-capability-values-retain-full-help ()
  "Provider names and distinct web dispatchers are not replaced by catalog order."
  (with-temp-buffer
    (hermes-tool-setup-mode)
    (setq hermes-tool-setup--name "browser"
          hermes-tool-setup--config '((active_provider . "First")
                                     (providers . (((name . "First") (is_active . t))
                                                   ((name . "Driver") (is_active . t))))))
    (should (equal (substring-no-properties (hermes-tool-setup--setting-description 'provider))
                   "Provider: First, Driver"))
    (setq hermes-tool-setup--name "web"
          hermes-tool-setup--config '((active_provider . "Do not infer from this")
                                     (active_search_backend . "search-backend")
                                     (active_extract_backend . "extract-backend")))
    (let ((label (hermes-tool-setup--setting-description 'provider)))
      (should (<= (string-width label) 38))
      (should (equal (get-text-property (length "Provider: ") 'face label) 'keymap-popup-value))
      (should (equal (get-text-property (length "Provider: ") 'help-echo label)
                     "search search-backend / extract extract-backend")))))


(ert-deftest hermes-tool-setup-real-model-prompt-cancel-keeps-reported-state ()
  "A real model prompt identifies the queried provider and current model."
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (hermes-tool-setup-mode)
      (setq hermes-tool-setup--name "image_gen"
            hermes-tool-setup--config '((providers . (((name . "Active") (is_active . t)))))
            tabulated-list-entries (hermes-tool-setup--rows hermes-tool-setup--config))
      (tabulated-list-print)
      (goto-char (point-min))
      (let ((keymap-popup-backend #'keymap-popup-backend-side-window)
            (keymap-popup--buffer-name " *tool model prompt test*")
            (before (copy-tree hermes-tool-setup--config)) prompt)
        (cl-letf (((symbol-function 'hermes-browser--run-on-client)
                   (lambda (_make success &optional _failure)
                     (funcall success '((has_models . t) (current . "model-one")
                                        (models . (((id . "model-one") (display . "Model One"))))))))
                  ((symbol-function 'hermes-tool-setup--change)
                   (lambda (&rest _) (ert-fail "Cancelled model prompt attempted a write"))))
          (unwind-protect
              (let ((noninteractive nil))
                (minibuffer-with-setup-hook
                    (lambda () (setq prompt (minibuffer-prompt)))
                  (condition-case nil
                      (execute-kbd-macro (kbd "? m C-g"))
                    (quit nil)))
                (should (string-match-p "Tool model for Active (current model-one)" prompt))
                (should (equal hermes-tool-setup--config before))
                (should-not hermes-tool-setup--busy))
            (keymap-popup-dismiss)))))))

(provide 'hermes-tool-setup-tests)
;;; hermes-tool-setup-tests.el ends here
