;;; hermes-groups-tests.el --- Hosted room read journeys -*- lexical-binding: t; -*-

;;; Code:
(require 'hermes-test-helpers)
(require 'hermes-groups)

(defconst hermes-groups-test--capabilities
  '((protocol_version . 2) (driver . :false) (persistent_process . :false)
    (authority_gateway_id . "gateway") (room_link . ((enabled . :false)))
    (features . ("authority_epoch" "room_identity" "monotonic_log" "typed_events"
                 "actor_identity" "replayable_disband"))
    (methods . ("groups.capabilities" "groups.list" "groups.state" "groups.log"))
    (max_log_limit . 500)))

(defun hermes-groups-test--room (&optional epoch disbanded)
  "Return a complete synthetic room at EPOCH with optional DISBANDED state."
  `((room_id . "room") (name . "Discussion")
    (members . (((member_id . "a") (display_name . "Athena") (profile . "test"))))
    (authority_gateway_id . ,(if (eql epoch 2) "successor" "gateway"))
    (authority_epoch . ,(or epoch 1)) (revision . 1)
    (created_at . 1.0) (updated_at . 2.0) (latest_seq . 3)
    ,@(and disbanded '((disbanded_at . 3.0)))))

(defun hermes-groups-test--event (seq &optional kind epoch)
  "Return synthetic SEQ event with optional KIND and EPOCH."
  `((room_id . "room") (seq . ,seq) (event_id . ,(format "event-%s" seq))
    (kind . ,(or kind "message.member"))
    (actor . ((kind . "member") (id . "a") (display_name . "Athena")))
    (authority_epoch . ,(or epoch 1)) (created_at . ,(float seq)) (idempotent . :false)
    (payload . ((text . ,(format "Literal public message %s" seq)) (member_id . "a")
                (task_id . "task") (thread_id . "thread") (turn_id . "turn")
                (status . "failed") (error . "No inference in this fixture")))))

(defun hermes-groups-test--page (events cursor latest &optional epoch)
  "Return EVENTS page with CURSOR, LATEST and optional EPOCH."
  `((events . ,events) (cursor . ,cursor) (latest_seq . ,latest)
    (has_more . ,(if (< cursor latest) t :false))
    (authority . ((gateway_id . ,(if (eql epoch 2) "successor" "gateway"))
                  (epoch . ,(or epoch 1))))))

(defmacro hermes-groups-test--wire (&rest body)
  "Run BODY with native acquisition/request ownership and controlled wire replies."
  (declare (indent 0) (debug t))
  `(let* ((instance (cons "groups-test" "http://groups.invalid"))
          (hermes-instances (list instance))
          (hermes-instance nil)
          (client (make-hermes-dashboard-transport-client
                   :base-url "http://groups.invalid" :websocket 'test-socket :ready-p t))
          (json-false :false)
          (before (buffer-list)) (released 0) frames all-methods
          (hermes-dashboard-transport-websocket-send-function
           (lambda (_socket text)
             (let ((frame (hermes-dashboard-transport--decode-frame text)))
               (push (alist-get 'method frame) all-methods)
               (setq frames (append frames (list frame)))))))
     (cl-letf (((symbol-function 'hermes-dashboard-transport-acquire)
                (lambda (&rest _) client))
               ((symbol-function 'hermes-dashboard-transport-release)
                (lambda (_) (cl-incf released)))
               ((symbol-function 'hermes-browser--existing-client) (lambda () nil))
               ((symbol-function 'websocket-close) #'ignore))
       (cl-labels ((answer (method result &optional errorp)
                     (let ((frame (pop frames)))
                       (should (equal (alist-get 'method frame) method))
                       (hermes-dashboard-transport--handle-frame
                        client (json-encode
                                `((jsonrpc . "2.0") (id . ,(alist-get 'id frame))
                                  (,(if errorp 'error 'result) . ,result))))))
                   (state (&optional epoch disbanded)
                     (answer "groups.capabilities" hermes-groups-test--capabilities)
                     (answer "groups.state" `((room . ,(hermes-groups-test--room epoch disbanded)))))
                   (view ()
                     (hermes-groups--buffer instance "room")))
         (unwind-protect (progn ,@body)
           (dolist (buffer (seq-difference (buffer-list) before))
             (when (buffer-live-p buffer) (kill-buffer buffer)))
           (hermes-dashboard-transport-stop client))))))

(ert-deftest hermes-groups-public-read-only-entry ()
  (should (commandp 'hermes-list-groups))
  (hermes-groups-test--wire
    (save-window-excursion
      (let ((listing (hermes-list-groups)))
        (should (eq (window-buffer) listing))
        (answer "groups.capabilities" hermes-groups-test--capabilities)
        (answer "groups.list" `((rooms . (,(hermes-groups-test--room))) (next_offset . 713)))
        (with-current-buffer listing
          (should (string-match-p "unavailable (history readable)" (hermes-groups--header)))
          (call-interactively (key-binding (kbd "m"))))
        (answer "groups.capabilities" hermes-groups-test--capabilities)
        (should (= (alist-get 'offset (alist-get 'params (car frames))) 713))
        (answer "groups.list" `((rooms . (,(hermes-groups-test--room))) (next_offset)))
        (with-current-buffer listing
          (goto-char (point-min)) (forward-line 2)
          (call-interactively (key-binding (kbd "RET"))))
        (state)
        (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 1)) 1 3))
        (should (= (alist-get 'since_seq (alist-get 'params (car frames))) 1))
        (answer "groups.log" (hermes-groups-test--page
                              (list (hermes-groups-test--event 1)
                                    (hermes-groups-test--event 2 "turn.failed")
                                    (hermes-groups-test--event 3)) 3 3))
        (with-current-buffer (view)
          (should buffer-read-only)
          (should (= hermes-groups--cursor 3))
          (should (= (length hermes-groups--events) 3))
          (should (= (how-many "Literal public message 1" (point-min) (point-max)) 1))
          (should (string-match-p "Athena" (buffer-string)))
          (should (string-match-p "turn.failed" (buffer-string)))
          (should (string-match-p "Worker: unknown" (buffer-string)))
          (should-not (local-variable-p 'hermes-chat--state))
          (goto-char (point-min))
          (let ((line (line-number-at-pos)))
            (execute-kbd-macro (kbd "n"))
            (should (= (line-number-at-pos) (1+ line))))))
      (should-not frames)
      (should (= released 3))
      (should (seq-every-p (lambda (method) (member method '("groups.capabilities" "groups.list"
                                                            "groups.state" "groups.log")))
                          all-methods)))))

(ert-deftest hermes-groups-list-rejects-missing-pagination-envelope ()
  (hermes-groups-test--wire
    (with-current-buffer (hermes-groups--buffer instance nil)
      (hermes-groups-refresh)
      (answer "groups.capabilities" hermes-groups-test--capabilities)
      (answer "groups.list" `((rooms . (,(hermes-groups-test--room)))))
      (should-not hermes-groups--rooms)
      (should (string-match-p "failed" hermes-browser--status)))))

(ert-deftest hermes-groups-display-transfer-prevents-network ()
  (hermes-groups-test--wire
    (cl-letf (((symbol-function 'pop-to-buffer)
               (lambda (buffer &rest _)
                 (with-current-buffer buffer (fundamental-mode)))))
      (should-error (hermes-list-groups) :type 'user-error)
      (should-not frames))))

(ert-deftest hermes-groups-capability-gates-do-not-require-driver ()
  (dolist (change '((protocol_version . 1) (features . nil) (methods . ("groups.list"))))
    (hermes-groups-test--wire
      (with-current-buffer (view)
        (hermes-groups-refresh)
        (let ((caps (copy-tree hermes-groups-test--capabilities)))
          (setf (alist-get (car change) caps) (cdr change))
          (answer "groups.capabilities" caps))
        (should-not frames)
        (should (string-match-p "failed" hermes-browser--status))
        (should-not hermes-browser--owned-cleanup)))))

(ert-deftest hermes-groups-render-failure-preserves-text-and-cursor ()
  (hermes-groups-test--wire
    (with-current-buffer (view)
      (hermes-groups-refresh) (state)
      (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 1)) 1 1))
      (let ((text (buffer-string)) (target (current-buffer))
            (insert-fn (symbol-function 'hermes-groups--print-text)))
        (hermes-groups-refresh) (state)
        (cl-letf (((symbol-function 'hermes-groups--print-text)
                   (lambda (&rest args)
                     (apply insert-fn args)
                     (when (eq target (current-buffer)) (error "printer failed after insert")))))
          (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 2)) 2 2)))
        (should (= hermes-groups--cursor 1))
        (should (equal text (buffer-string)))
        (should-not hermes-browser--owned-cleanup))
      (hermes-groups-refresh) (state)
      (should (= (alist-get 'since_seq (alist-get 'params (car frames))) 1))
      (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 2)) 2 2))
      (should (= hermes-groups--cursor 2)))))

(ert-deftest hermes-groups-gap-reconciles-once-without-skipping ()
  (hermes-groups-test--wire
    (with-current-buffer (view)
      (hermes-groups-refresh) (state)
      (let ((gap (hermes-groups-test--page (list (hermes-groups-test--event 2)) 2 2)))
        (answer "groups.log" gap)
        (answer "groups.state" `((room . ,(hermes-groups-test--room))))
        (should (= (alist-get 'since_seq (alist-get 'params (car frames))) 0))
        (answer "groups.log" gap))
      (should-not frames)
      (should (= hermes-groups--cursor 0))
      (should (string-match-p "discontinuity" (buffer-string)))
      (should (string-match-p "failed" hermes-browser--status)))))

(ert-deftest hermes-groups-epoch-transition-explicitly-replays ()
  (hermes-groups-test--wire
    (with-current-buffer (view)
      (hermes-groups-refresh) (state)
      (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 1)) 1 1))
      (hermes-groups-refresh) (state)
      (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 2 nil 2)) 2 2 2))
      (answer "groups.state" `((room . ,(hermes-groups-test--room 2))))
      (should (= (alist-get 'since_seq (alist-get 'params (car frames))) 0))
      (answer "groups.log" (hermes-groups-test--page
                            (list (hermes-groups-test--event 1)
                                  (hermes-groups-test--event 2 nil 2)) 2 2 2))
      (should (= hermes-groups--cursor 2))
      (should (string-match-p "Authority changed" (buffer-string)))
      (should (equal (hermes-groups--authority hermes-groups--room) '("successor" . 2)))
      (hermes-groups-refresh) (state 1)
      (should-not frames)
      (should (equal (hermes-groups--authority hermes-groups--room) '("successor" . 2))))))

(ert-deftest hermes-groups-malformed-cursors-and-conflicting-replays-refused ()
  (let* ((room (hermes-groups-test--room)) (event (hermes-groups-test--event 1))
         (base (hermes-groups-test--page nil 1 1)))
    (dolist (change '((cursor) (cursor . 9) (latest_seq . 0) (has_more . t)
                      (has_more . "false") (authority . ((gateway_id . "other") (epoch . 1)))))
      (let ((page (copy-tree base)))
        (setf (alist-get (car change) page) (cdr change))
        (should-error (hermes-groups--page-events page room (list event) 1)
                      :type 'hermes-groups-reconcile)))
    (let ((conflict (hermes-groups-test--event 2)))
      (setf (alist-get 'event_id conflict) "event-1")
      (should-error (hermes-groups--page-events (hermes-groups-test--page (list conflict) 2 2)
                                               room (list event) 1)
                    :type 'hermes-groups-reconcile))
    (should (equal (hermes-groups--page-events (hermes-groups-test--page (list event) 1 1)
                                              room (list event) 1) nil))))

(ert-deftest hermes-groups-retirement-fences-delayed-wire-and-native-commands ()
  (dolist (retirement '(mode file detach kill stop backend))
    (hermes-groups-test--wire
      (let ((buffer (view)))
        (with-current-buffer buffer
          (hermes-groups-refresh) (state)
          (pcase retirement
            ('mode (fundamental-mode)
                   (let ((inhibit-read-only t)) (erase-buffer) (insert "user notes")))
            ('file (set-visited-file-name (expand-file-name "notes" temporary-file-directory) t)
                   (let ((inhibit-read-only t)) (erase-buffer) (insert "user notes")))
            ('detach (set-visited-file-name (expand-file-name "notes" temporary-file-directory) t)
                     (set-visited-file-name nil t)
                     (let ((inhibit-read-only t)) (erase-buffer) (insert "user notes")))
            ('kill (kill-buffer buffer))
            ('stop (hermes-dashboard-transport-stop client))
            ('backend (hermes-browser--own-instance (cons "other" "http://other.invalid"))))
          (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 1)) 1 1)))
        (should (= (hash-table-count (hermes-dashboard-transport-client-pending client)) 0))
        (should (= released 1))
        (when (buffer-live-p buffer)
          (with-current-buffer buffer
            (should-not (string-match-p "Literal public" (buffer-string)))
            (when (memq retirement '(file detach mode))
              (should (equal (buffer-string) "user notes"))
              (should-error (hermes-groups-refresh) :type 'user-error))))))))

(ert-deftest hermes-groups-disbanded-and-expired-never-resurrect ()
  (hermes-groups-test--wire
    (with-current-buffer (view)
      (hermes-groups-follow) (state 1 t)
      (should-not hermes-groups--follow)
      (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 1 "room.disbanded")) 1 1))
      (should (eq hermes-groups--terminal 'disbanded))
      (should-error (hermes-groups-follow) :type 'user-error)
      (hermes-groups-refresh) (state)
      (should-not frames)
      (should (eq hermes-groups--terminal 'disbanded))
      (hermes-groups-refresh)
      (answer "groups.capabilities" hermes-groups-test--capabilities)
      (answer "groups.state" '((code . 4114) (message . "not diagnostic wording")
                                (data . ((reason . "room_history_expired")))) t)
      (should (eq hermes-groups--terminal 'expired))
      (should (string-match-p "History: expired" (buffer-string)))
      (should-error (hermes-groups-refresh) :type 'user-error)
      (should-not hermes-browser--owned-cleanup))))

(ert-deftest hermes-groups-driver-approval-blocked-failed-and-unknown-distinct ()
  (let ((text (hermes-groups--detail-text
               (hermes-groups-test--room)
               '((running . t) (working . :false) (blocked . t)
                 (counts . ((failed . 1) (unknown . 2)))
                 (pending_actions . (((kind . "approval") (member_id . "a") (task_id . "task")))))
               (list (hermes-groups-test--event 1 "turn.failed")) nil nil)))
    (should (string-match-p "Pending approval · Member: a · Task: task" text))
    (should (string-match-p "Blocked: yes" text))
    (should (string-match-p "(failed . 1)" text))
    (should (string-match-p "(unknown . 2)" text))
    (should (string-match-p "turn.failed" text))))

(ert-deftest hermes-groups-follow-timer-is-bounded-and-retired ()
  (hermes-groups-test--wire
    (let ((schedule (symbol-function 'run-at-time)) callback owned-timer)
      (cl-letf (((symbol-function 'run-at-time)
                 (lambda (time repeat fn &rest args)
                   (let ((timer (apply schedule time repeat fn args)))
                     (when (eql time 5) (setq callback fn owned-timer timer))
                     timer))))
        (with-current-buffer (view)
          (hermes-groups-follow) (state)
          (answer "groups.log" (hermes-groups-test--page nil 0 0))
          (should hermes-groups--timer-cleanup)
          (should (memq owned-timer timer-list))
          (funcall callback)
          (should-not (memq owned-timer timer-list))
          (dotimes (n 3)
            (answer "groups.capabilities" '((code . -32603) (message . "read failed")) t)
            (when (< n 2) (funcall callback)))
          (should-not hermes-groups--follow)
          (should-not hermes-groups--timer-cleanup)
          (hermes-groups-follow) (state)
          (answer "groups.log" (hermes-groups-test--page nil 0 0))
          (should hermes-groups--timer-cleanup)
          (hermes-dashboard-transport-stop client)
          (should-not hermes-groups--timer-cleanup)
          (should-not (memq owned-timer timer-list))
          (funcall callback)
          (should-not frames))))))

(ert-deftest hermes-groups-background-completion-keeps-follow-on-owner ()
  (hermes-groups-test--wire
    (let ((target (view)))
      (with-current-buffer target (hermes-groups-follow))
      (with-temp-buffer
        (state)
        (answer "groups.log" (hermes-groups-test--page nil 0 0))
        (should-not hermes-groups--timer-cleanup)
        (with-current-buffer target
          (should hermes-groups--timer-cleanup)
          (should hermes-groups--follow))
        (hermes-dashboard-transport-stop client))
      (with-current-buffer target
        (should-not hermes-groups--timer-cleanup)
        (should-not hermes-groups--follow)))))

(ert-deftest hermes-groups-readiness-retirement-cancels-queued-rpc ()
  (hermes-groups-test--wire
    (setf (hermes-dashboard-transport-client-ready-p client) nil
          (hermes-dashboard-transport-client-ready-promise client) (hermes--promise-make))
    (let ((ready (hermes-dashboard-transport-client-ready-promise client)))
      (with-current-buffer (view)
        (hermes-groups-refresh)
        (should-not frames)
        (should (= (hash-table-count (hermes-dashboard-transport-client-pending client)) 1))
        (set-visited-file-name (expand-file-name "notes" temporary-file-directory) t)
        (hermes--promise-resolve ready client)
        (should-not frames)
        (should (= released 1))
        (should (= (hash-table-count (hermes-dashboard-transport-client-pending client)) 0))))))

(ert-deftest hermes-groups-cold-acquisition-error-and-quit-settle-for-retry ()
  (dolist (condition '(error quit))
    (hermes-groups-test--wire
      (with-current-buffer (view)
        (cl-letf (((symbol-function 'hermes-dashboard-transport-acquire)
                   (lambda (&rest _) (signal condition '("acquisition cancelled")))))
          (condition-case nil (hermes-groups-refresh) ((error quit) nil)))
        (should (string-match-p "failed" hermes-browser--status))
        (should-not hermes-browser--owned-cleanup)
        (hermes-groups-refresh) (state)
        (answer "groups.log" (hermes-groups-test--page nil 0 0))
        (should (equal hermes-browser--status "Connected; history current"))))))

(ert-deftest hermes-groups-backend-qualified-constructors-preserve-foreign-buffers ()
  (let* ((a (cons "same" "http://a.invalid")) (b (cons "same" "http://b.invalid"))
         (foreign (generate-new-buffer "*Hermes Groups: same / room*"))
         first second)
    (unwind-protect
        (progn
          (with-current-buffer foreign (insert "unrelated text"))
          (setq first (hermes-groups--buffer a "room") second (hermes-groups--buffer b "room"))
          (should-not (eq first foreign)) (should-not (eq first second))
          (should (eq first (hermes-groups--buffer a "room")))
          (should (equal (with-current-buffer foreign (buffer-string)) "unrelated text")))
      (mapc #'kill-buffer (delq nil (list first second foreign))))))

(ert-deftest hermes-groups-refresh-budget-and-reconnect-retain-cursor ()
  (hermes-groups-test--wire
    (with-current-buffer (view)
      (hermes-groups-refresh) (state)
      (dotimes (index 20)
        (let ((seq (1+ index)))
          (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event seq)) seq 21))))
      (should-not frames)
      (should (= hermes-groups--cursor 20))
      (should (equal hermes-browser--status "Partial history; g continues"))
      (hermes-dashboard-transport-stop client)
      (setq client (make-hermes-dashboard-transport-client
                    :base-url "http://groups.invalid" :websocket 'replacement :ready-p t))
      (call-interactively (key-binding (kbd "g"))) (state)
      (should (= (alist-get 'since_seq (alist-get 'params (car frames))) 20))
      (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 21)) 21 21))
      (should (= hermes-groups--cursor 21))
      (should (= (length hermes-groups--events) 21)))))

(ert-deftest hermes-groups-native-render-transfer-preserves-user-notes ()
  (dolist (hook '(before-change-functions after-change-functions))
    (hermes-groups-test--wire
      (with-current-buffer (view)
        (hermes-groups-refresh) (state)
        (let ((transfer (lambda (&rest _)
                          (set-visited-file-name (expand-file-name "notes" temporary-file-directory) t)
                          (let ((inhibit-modification-hooks t) (inhibit-read-only t))
                            (erase-buffer) (insert "owned user notes")))))
          (add-hook hook transfer nil t)
          (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 1)) 1 1))
          (remove-hook hook transfer t))
        (should (= hermes-groups--cursor 0))
        (should (equal (buffer-string) "owned user notes"))
        (should-not hermes-browser--owned-cleanup)
        (should (= released 1))))))

(ert-deftest hermes-groups-native-hooks-retain-accepted-transaction ()
  (dolist (phase '(state log))
    (dolist (hook '(before-change-functions after-change-functions))
      (dolist (fault '(error quit edit))
        (hermes-groups-test--wire
          (with-current-buffer (view)
            (hermes-groups-refresh) (state)
            (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 1)) 1 1))
            (hermes-groups-refresh)
            (answer "groups.capabilities" hermes-groups-test--capabilities)
            (when (eq phase 'log)
              (answer "groups.state" `((room . ,(hermes-groups-test--room)))))
            (let ((text (buffer-string)) (room hermes-groups--room)
                  (events hermes-groups--events)
                  (fn (lambda (&rest _)
                        (if (eq fault 'edit)
                            (let ((inhibit-read-only t) (inhibit-modification-hooks t))
                              (erase-buffer) (insert "same-owner replacement"))
                          (signal fault '("native hook fault"))))))
              (add-hook hook fn nil t)
              (if (eq phase 'state)
                  (answer "groups.state" `((room . ,(hermes-groups-test--room 2))))
                (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 2)) 2 2)))
              (remove-hook hook fn t)
              (should (equal-including-properties text (buffer-string)))
              (should (eq room hermes-groups--room))
              (should (eq events hermes-groups--events))
              (should (= hermes-groups--cursor 1))
              (should-not frames)
              (should-not hermes-browser--owned-cleanup))
            (hermes-groups-refresh) (state 2)
            (answer "groups.log" (hermes-groups-test--page
                                  (list (hermes-groups-test--event 1 nil 2)
                                        (hermes-groups-test--event 2 nil 2)) 2 2 2))
            (should (= hermes-groups--cursor 2))
            (should (string-match-p "Literal public message 2" (buffer-string)))))))))

(ert-deftest hermes-groups-native-hooks-fence-original-read ()
  (dolist (phase '(state log))
    (dolist (hook '(before-change-functions after-change-functions))
      (dolist (retirement '(stop endpoint room))
        (hermes-groups-test--wire
          (with-current-buffer (view)
            (hermes-groups-refresh) (state)
            (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 1)) 1 1))
            (hermes-groups-refresh)
            (answer "groups.capabilities" hermes-groups-test--capabilities)
            (when (eq phase 'log)
              (answer "groups.state" `((room . ,(hermes-groups-test--room)))))
            (let ((text (buffer-string)) (room hermes-groups--room)
                  (fn (lambda (&rest _)
                        (pcase retirement
                          ('stop (hermes-dashboard-transport-stop client))
                          ('endpoint (setf (hermes-dashboard-transport-client-base-url client)
                                           "http://replacement.invalid"))
                          ('room (setq hermes-groups--room-id "replacement"))))))
              (add-hook hook fn nil t)
              (if (eq phase 'state)
                  (answer "groups.state" `((room . ,(hermes-groups-test--room 2))))
                (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 2)) 2 3)))
              (remove-hook hook fn t)
              (should (= hermes-groups--cursor 1))
              (should (eq room hermes-groups--room))
              (unless (eq retirement 'room)
                (should (equal-including-properties text (buffer-string))))
              (should-not frames)
              (should-not hermes-groups--timer-cleanup)
              (should-not hermes-browser--owned-cleanup)
              (should (zerop (hash-table-count (hermes-dashboard-transport-client-pending client)))))
            (setq client (make-hermes-dashboard-transport-client
                          :base-url "http://groups.invalid" :websocket 'test-socket :ready-p t)
                  hermes-groups--room-id "room")
            (hermes-groups-refresh) (state)
            (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 2)) 2 2))
            (should (= hermes-groups--cursor 2))))))))

(ert-deftest hermes-groups-follow-native-lease-survives-second-read ()
  ;; Restore both native lease functions inside the wire fixture.  Only startup
  ;; and socket writes are controlled; no hand-assigned reference counts.
  (let ((acquire (symbol-function 'hermes-dashboard-transport-acquire))
        (release (symbol-function 'hermes-dashboard-transport-release)))
    (dolist (shared '(nil t))
      (dolist (retirement '(off kill mode file backend stop reconnect terminal expired))
        (hermes-groups-test--wire
          (let ((hermes-dashboard-transport--clients (make-hash-table :test #'equal))
                (hermes-dashboard-transport-idle-close-delay nil)
                (schedule (symbol-function 'run-at-time)) callback owned-timer chat retained-cleanup)
            (cl-letf (((symbol-function 'hermes-dashboard-transport-acquire) acquire)
                      ((symbol-function 'hermes-dashboard-transport-release) release)
                      ((symbol-function 'hermes-dashboard-transport-start) (lambda (&rest _) client))
                      ((symbol-function 'hermes-dashboard-transport--reconnect-attempt) #'ignore)
                      ((symbol-function 'hermes-browser--existing-client) (lambda () chat))
                      ((symbol-function 'run-at-time)
                       (lambda (time repeat fn &rest args)
                         (let ((timer (apply schedule time repeat fn args)))
                           (when (eql time 5) (setq callback fn owned-timer timer))
                           timer))))
              (when shared
                (let ((hermes-dashboard-transport-url (cdr instance)))
                  (setq chat (hermes-dashboard-transport-acquire))))
              (with-current-buffer (view)
                (hermes-groups-follow) (state)
                (answer "groups.log" (hermes-groups-test--page nil 0 0))
                (should hermes-groups--follow)
                (should (memq owned-timer timer-list))
                (should (= (hermes-dashboard-transport-client-refcount client) (if shared 2 1)))
                ;; Advance the owned native timer, then yield to its real
                ;; delivery rather than invoking the continuation ourselves.
                (cancel-timer owned-timer)
                (timer-set-time owned-timer (current-time))
                (timer-activate owned-timer)
                (hermes-test--wait-until (lambda () frames) 2 "second Follow read")
                (should-not (memq owned-timer timer-list))
                (state)
                (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 1)) 1 1))
                (should (= hermes-groups--cursor 1))
                (should hermes-groups--follow)
                (should (= (hermes-dashboard-transport-client-refcount client) (if shared 2 1)))
                (setq retained-cleanup hermes-groups--follow-cleanup)
                (pcase retirement
                  ('off (hermes-groups-follow))
                  ('kill (kill-buffer (current-buffer)))
                  ('mode (fundamental-mode))
                  ('file (set-visited-file-name (expand-file-name "notes" temporary-file-directory) t))
                  ('backend (hermes-browser--own-instance (cons "other" "http://other.invalid")))
                  ('stop (hermes-dashboard-transport-stop client))
                  ('reconnect (hermes-dashboard-transport-reconnect client))
                  ('expired (funcall callback)
                            (answer "groups.capabilities" hermes-groups-test--capabilities)
                            (answer "groups.state"
                                    '((code . 4114) (data . ((reason . "room_history_expired")))) t))
                  ('terminal (funcall callback) (state 1 t)
                             (answer "groups.log" (hermes-groups-test--page nil 1 1))))
                (should-not (memq owned-timer timer-list))
                (funcall callback)
                (funcall retained-cleanup)
                (funcall retained-cleanup)
                (should-not frames)
                (should (= (hermes-dashboard-transport-client-refcount client)
                           (if (and shared (not (eq retirement 'stop))) 1 0)))
                (should (zerop (hash-table-count (hermes-dashboard-transport-client-pending client)))))
              (when chat (hermes-dashboard-transport-release chat)))))))))

(ert-deftest hermes-groups-native-hook-successor-survives-unwind ()
  (dolist (hook '(before-change-functions after-change-functions))
    (dolist (transfer '(file generation mode))
      (dolist (fault '(error quit))
        (hermes-groups-test--wire
          (with-current-buffer (view)
            (hermes-groups-refresh) (state)
            (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 1)) 1 1))
            (hermes-groups-refresh) (state)
            (let ((fn (lambda (&rest _)
                        (pcase transfer
                          ('file (set-visited-file-name (expand-file-name "notes" temporary-file-directory) t))
                          ('generation (hermes-browser--next-request-generation))
                          ('mode (fundamental-mode)))
                        (let ((inhibit-modification-hooks t) (inhibit-read-only t))
                          (erase-buffer) (insert "successor's unsaved draft"))
                        (buffer-enable-undo)
                        (setq buffer-undo-list nil)
                        (signal fault '("successor hook")))))
              (add-hook hook fn nil t)
              (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 2)) 2 3))
              (remove-hook hook fn t))
            (should (equal (buffer-string) "successor's unsaved draft"))
            (should (listp buffer-undo-list))
            (should-not frames)
            (should-not hermes-browser--owned-cleanup)
            (unless (eq transfer 'mode) (should (= hermes-groups--cursor 1)))))))))

(ert-deftest hermes-groups-native-reconnect-during-notification ()
  (let ((acquire (symbol-function 'hermes-dashboard-transport-acquire))
        (release (symbol-function 'hermes-dashboard-transport-release)))
    (dolist (hook '(before-change-functions after-change-functions))
      (dolist (phase '(state log))
        (hermes-groups-test--wire
          (let ((hermes-dashboard-transport--clients (make-hash-table :test #'equal))
                (hermes-dashboard-transport-idle-close-delay nil))
            (cl-letf (((symbol-function 'hermes-dashboard-transport-acquire) acquire)
                      ((symbol-function 'hermes-dashboard-transport-release) release)
                      ((symbol-function 'hermes-dashboard-transport-start)
                       (lambda (&rest _)
                         (setq client (make-hermes-dashboard-transport-client
                                       :base-url "http://groups.invalid" :websocket 'test-socket :ready-p t)))))
              (with-current-buffer (view)
                (hermes-groups-follow) (state)
                (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 1)) 1 1))
                (hermes-groups-refresh)
                (answer "groups.capabilities" hermes-groups-test--capabilities)
                (when (eq phase 'log)
                  (answer "groups.state" `((room . ,(hermes-groups-test--room)))))
                (let ((text (buffer-string)) (room hermes-groups--room)
                      (fn (lambda (&rest _) (hermes-dashboard-transport-reconnect client))))
                  (add-hook hook fn nil t)
                  (if (eq phase 'state)
                      (answer "groups.state" `((room . ,(hermes-groups-test--room 2))))
                    (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 2)) 2 3)))
                  (remove-hook hook fn t)
                  (should (equal-including-properties text (buffer-string)))
                  (should (eq room hermes-groups--room))
                  (should (= hermes-groups--cursor 1))
                  (should-not frames)
                  (should-not hermes-groups--follow)
                  (should-not hermes-groups--timer-cleanup)
                  (should-not hermes-groups--follow-cleanup)
                  (should-not hermes-browser--owned-cleanup)
                  (should (= (hermes-dashboard-transport-client-refcount client) 0))
                  (should (zerop (hash-table-count (hermes-dashboard-transport-client-pending client)))))
                (hermes-groups-refresh) (state)
                (answer "groups.log" (hermes-groups-test--page (list (hermes-groups-test--event 2)) 2 2))
                (should (= hermes-groups--cursor 2))))))))))

(provide 'hermes-groups-tests)
;;; hermes-groups-tests.el ends here
