;;; hermes-chat-wire-tests.el --- Chat topic tests -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'delsel)
(require 'hermes-test-helpers)

(ert-deftest hermes-chat-reader-windows-survive-stream-and-settlement ()
  "Both readers retain their lines, while the literal draft remains undoable."
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (delete-other-windows)
      (hermes-chat-mode)
      (let* ((text (mapconcat (lambda (n) (format "Reader line %03d" n))
                             (number-sequence 1 160) "\n"))
             (entry (hermes-chat--make-entry 'assistant text 'streaming))
             (id (plist-get entry :id)))
        (hermes-chat--insert-entry entry)
        (goto-char (point-max))
        (undo-boundary)
        (insert "  literal draft\nλ  ")
        (undo-boundary)
        (let* ((first (selected-window))
               (second (split-window-right))
               (positions (mapcar (lambda (line)
                                    (save-excursion
                                      (goto-char (point-min))
                                      (forward-line line) (point)))
                                  '(60 65 100 105))))
          (set-window-start first (nth 0 positions) t)
          (set-window-point first (nth 1 positions))
          (set-window-start second (nth 2 positions) t)
          (set-window-point second (nth 3 positions))
          (redisplay t)
          (dolist (phase '(delta settlement))
            (if (eq phase 'delta)
                (hermes-chat--append-assistant-content id "\nNew output" 'streaming)
              (hermes-chat--mark-assistant id 'done))
            (redisplay t)
            (should (eq (selected-window) first))
            (should (equal (list (window-start first) (window-point first)
                                 (window-start second) (window-point second))
                           positions))
            (should (equal (hermes-chat-input-string) "  literal draft\nλ  ")))
          (goto-char (point-max))
          (let ((inhibit-message t)) (undo 1))
          (should (equal (hermes-chat-input-string) "")))))))

(ert-deftest hermes-chat-reader-tail-and-shortened-anchors ()
  "Only the tail follows output; shortening and removal bound the old reader."
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (delete-other-windows)
      (hermes-chat-mode)
      (let* ((text (mapconcat (lambda (n) (format "Line %03d" n))
                             (number-sequence 1 100) "\n"))
             (entry (hermes-chat--make-entry 'assistant text 'streaming))
             (id (plist-get entry :id)))
        (hermes-chat--insert-entry entry)
        (goto-char (point-max)) (insert "draft")
        (let* ((first (selected-window)) (second (split-window-right))
               (start (save-excursion (goto-char (point-min))
                                      (forward-line 30) (point)))
               (reader (+ start 9)))
          (set-window-start second start t)
          (set-window-point second reader)
          (redisplay t)
          (hermes-chat--append-assistant-content id (concat "\n" text) 'streaming)
          (redisplay t)
          (should (= (window-point first) (point-max)))
          (unless noninteractive
            (should (pos-visible-in-window-p (window-point first) first)))
          (should (= (window-start second) start))
          (should (= (window-point second) reader))
          (hermes-chat--mark-assistant id 'done "Short")
          (redisplay t)
          (should (< (window-point second) (hermes-chat--input-position)))
          (should (<= (point-min) (window-start second) (window-point second)))
          (hermes-chat--remove-entry id)
          (redisplay t)
          (should (<= (point-min) (window-start second)
                      (hermes-chat--input-position)))
          (should (<= (point-min) (window-point second)
                      (hermes-chat--input-position)))
          (should (= (window-point first) (point-max)))
          (should (eq first (selected-window)))
          (should (equal (hermes-chat-input-string) "draft")))))))

(defun hermes-test--reader-window-positions (windows)
  "Return each of WINDOWS' start and point."
  (mapcar (lambda (window)
            (list (window-start window) (window-point window)))
          windows))

(defun hermes-test--wire-readers (role)
  "Exercise two readers of ROLE through real decoded terminal events."
  (save-window-excursion
    (hermes-test-with-dashboard-prompt-session (client)
      (switch-to-buffer (current-buffer))
      (delete-other-windows)
      (let ((text (mapconcat (lambda (n) (format "Reader %03d" n))
                             (number-sequence 1 160) "\n\n"))
            (draft "  literal draft\nλ  "))
        (hermes-test--emit-dashboard-prompt
         client (pcase role ('commentary "reasoning.delta")
                       ('tool "tool.start") (_ "message.delta"))
         `((text . ,text) (tool_id . "reader-tool") (name . "terminal")))
        (let* ((entry (cl-find role (hermes-chat--entries)
                               :key (lambda (item) (plist-get item :role))))
               (id (plist-get entry :id))
               (content (plist-get entry :content)))
          (should entry)
          (unless (eq role 'assistant)
            (let ((button (next-button (ewoc-location (gethash id hermes-chat--nodes)))))
              (should button)
              (should (equal (button-get button 'hermes-chat-entry-id) id))
              (button-activate button)))
          (should (save-excursion (goto-char (point-min))
                                 (search-forward "Reader 160" nil t)))
          (goto-char (point-max))
          (undo-boundary) (insert draft) (undo-boundary)
          (let* ((windows (list (selected-window) (split-window-right)))
                 (first (car windows))
                 (second (cadr windows))
                 (position (lambda (label)
                             (save-excursion
                               (goto-char (point-min))
                               (search-forward label)
                               (line-beginning-position)))))
            (set-window-start first (funcall position "Reader 025") t)
            (set-window-point first (+ 3 (funcall position "Reader 028")))
            (set-window-start second (funcall position "Reader 065") t)
            (set-window-point second (+ 4 (funcall position "Reader 068")))
            (redisplay t)
            (let ((before (hermes-test--reader-window-positions windows)))
              (when (eq role 'tool)
                ;; Interim output renames the live tool row's owner and ID.
                (hermes-test--emit-dashboard-prompt
                 client "message.interim" '((text . "Interim answer")))
                (redisplay t)
                (should-not (gethash id hermes-chat--nodes))
                (setq entry (cl-find 'tool (hermes-chat--entries)
                                     :key (lambda (item) (plist-get item :role)))
                      id (plist-get entry :id))
                (should (equal (hermes-chat--entry-assistant-id entry)
                               hermes-chat--pending-assistant-id))
                (should (equal before (hermes-test--reader-window-positions windows))))
              (when (eq role 'assistant)
                (hermes-test--emit-dashboard-prompt
                 client "message.delta" '((text . "\nExtra output")))
                (redisplay t)
                (should (equal before (hermes-test--reader-window-positions windows))))
              (hermes-test--emit-dashboard-prompt
               client "message.complete"
               (if (eq role 'assistant) '((status . "done"))
                 '((text . "Final answer") (status . "done"))))
              (redisplay t)
              (should (equal before (hermes-test--reader-window-positions windows)))
              (should (eq first (selected-window)))
              (should-not hermes-chat--pending-assistant-id)
              (should (save-excursion (goto-char (point-min))
                                     (search-forward "Reader 160" nil t)))
              (setq entry (ewoc-data (gethash id hermes-chat--nodes)))
              (should (eq (plist-get entry :status) 'done))
              (unless (eq role 'assistant)
                (should (equal content (plist-get entry :content)))
                (should (hermes-chat--entry-expanded-p entry)))
              (should (equal (hermes-chat-input-string) draft)))
            (goto-char (point-max))
            (let ((inhibit-message t)) (undo 1))
            (should (equal (hermes-chat-input-string) ""))))))))

(ert-deftest hermes-chat-reader-wire-reasoning-settlement ()
  "Public Send and decoded completion preserve two expanded reasoning readers."
  (hermes-test--wire-readers 'commentary))

(ert-deftest hermes-chat-reader-wire-tool-rotation-and-settlement ()
  "Expanded tool readers survive interim ID rotation and terminal settlement."
  (hermes-test--wire-readers 'tool))

(ert-deftest hermes-chat-reader-wire-assistant-control ()
  "Ordinary assistant deltas and terminal settlement retain both readers."
  (hermes-test--wire-readers 'assistant))

(ert-deftest hermes-chat-reader-wire-draft-tail-control ()
  "Decoded output follows only the draft window, preserving narrowed input."
  (save-window-excursion
    (hermes-test-with-dashboard-prompt-session (client)
      (switch-to-buffer (current-buffer))
      (delete-other-windows)
      (let ((text (mapconcat (lambda (n) (format "Line %03d" n))
                             (number-sequence 1 160) "\n")))
        (hermes-test--emit-dashboard-prompt client "message.delta" `((text . ,text)))
        (goto-char (point-max))
        (undo-boundary) (insert " literal λ draft ") (undo-boundary)
        (let* ((first (selected-window)) (second (split-window-right))
               (start (save-excursion (goto-char (point-min))
                                      (forward-line 30) (point))))
          (set-window-start second start t)
          (set-window-point second (+ 3 start))
          (redisplay t)
          (hermes-test--emit-dashboard-prompt client "message.delta" `((text . ,text)))
          (redisplay t)
          (should (= (window-point first) (point-max)))
          (unless noninteractive
            (should (pos-visible-in-window-p (window-point first) first)))
          (save-restriction
            (narrow-to-region (+ 2 (hermes-chat--input-position)) (- (point-max) 2))
            (goto-char (+ 3 (point-min)))
            (hermes-test--emit-dashboard-prompt
             client "message.complete" '((status . "done")))
            (should (= (- (point-min) (hermes-chat--input-position)) 2))
            (should (= (- (point) (hermes-chat--input-position)) 5))
            (should (= (- (point-max) (hermes-chat--input-position)) 15)))
          (goto-char (point-max))
          (redisplay t)
          (should (eq first (selected-window)))
          (should (= (window-start second) start))
          (should (= (window-point second) (+ 3 start)))
          (should (equal (hermes-chat-input-string) " literal λ draft "))
          (let ((inhibit-message t)) (undo 1))
          (should (equal (hermes-chat-input-string) "")))))))

(provide 'hermes-chat-wire-tests)
;;; hermes-chat-wire-tests.el ends here
