;;; jabber-test-contact-owners.el --- Contact ownership tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'jabber-presence)
(require 'jabber-roster)
(require 'jabber-receipts)
(require 'jabber-info)
(require 'jabber-vcard-avatars)
(require 'jabber-notifications)
(require 'jabber-core)
(require 'jabber-openpgp-legacy)
(require 'jabber-modeline)
(require 'jabber-compose)
(require 'jabber-widget)
(require 'jabber-chatstates)

(defun jabber-test-contact--owner (name)
  "Return a disposable connection named NAME."
  (let ((jc (make-symbol name)))
    (put jc :state :session-established)
    (put jc :state-data (list :username name :server "example.test" :resource "test"
                             :roster nil :roster-hash nil :roster-groups nil))
    jc))

(defun jabber-test-contact--roster (jc name subscription &optional initial)
  "Deliver JC's roster with NAME and SUBSCRIPTION; INITIAL resets the item."
  (jabber-process-roster
   jc `(iq ((type . "result"))
           (query ((xmlns . "jabber:iq:roster"))
                  (item ((jid . "peer@example.test") (name . ,name)
                         (subscription . ,subscription)) (group () ,name))))
   (and initial 'initial)))

(defmacro jabber-test-contact--with-owners (&rest body)
  "Evaluate BODY with disposable owners A and B and isolated hooks."
  (declare (indent 0) (debug t))
  `(let* ((a (jabber-test-contact--owner "A"))
          (b (jabber-test-contact--owner "B"))
          (jabber-connections (list a b))
          (jabber-jid-obarray (make-vector 127 0))
          (jabber-db-path nil)
          (jabber-post-connect-hooks nil)
          (jabber-presence-roster-update-functions '(jabber-roster-update))
          (jabber-presence-contact-functions nil)
          (jabber-presence-hooks nil)
          (jabber-alert-presence-hooks nil))
     (cl-letf (((symbol-function 'fsm-send) #'ignore)
               ((symbol-function 'jabber-send-sexp) (lambda (&rest _) (error "Unexpected wire")))
               ((symbol-function 'jabber-send-iq) (lambda (&rest _) (error "Unexpected IQ"))))
       ,@body)))

(ert-deftest jabber-test-contact-owners-roster-presence ()
  (dolist (reverse '(nil t))
    (jabber-test-contact--with-owners
      (dolist (owner (if reverse (list b a) (list a b)))
        (jabber-test-contact--roster owner (symbol-name owner)
                                     (if (eq owner a) "both" "none") t))
      (let ((pa (car (plist-get (fsm-get-state-data a) :roster)))
            (pb (car (plist-get (fsm-get-state-data b) :roster))))
        (should-not (eq pa pb))
        (should (eq (jabber-jid-symbol pa b) pb))
        (should (eq (jabber-jid-symbol pa) pa))
        (should (eq (jabber-jid-owner pa) a))
        (should (equal (get pa 'name) "A"))
        (should (equal (get pb 'groups) '("B")))
        (jabber-process-presence a '(presence ((from . "peer@example.test/Phone"))
                                            (priority () "10") (status () "A status")))
        (jabber-process-presence b '(presence ((from . "peer@example.test/Phone"))
                                            (show () "away") (status () "B status")))
        (should (equal (get pa 'status) "A status"))
        (should (equal (get pb 'status) "B status"))
        (jabber-process-presence b '(presence ((from . "peer@example.test") (type . "unavailable"))))
        (should (get pa 'connected))
        (should-not (get pb 'connected))
        (jabber-test-contact--roster b "B reset" "none" t)
        (should (eq (jabber-jid-owner pb) b))
        (should (get pa 'connected))))))

(ert-deftest jabber-test-contact-owners-receipt-permissions ()
  (dolist (reverse '(nil t))
    (jabber-test-contact--with-owners
      (dolist (owner (if reverse (list b a) (list a b)))
        (jabber-test-contact--roster owner (symbol-name owner)
                                     (if (eq owner a) "both" "none") t))
      (let ((jabber-chat-send-receipts t)
            (xml '(message ((id . "owned")) (body () "fixture")
                           (request ((xmlns . "urn:xmpp:receipts")))
                           (markable ((xmlns . "urn:xmpp:chat-markers:0")))))
            sent)
        (with-temp-buffer
          (let ((buffer (current-buffer)))
            (cl-letf (((symbol-function 'jabber-send-sexp-if-connected)
                       (lambda (jc stanza) (push (list jc stanza) sent)))
                      ((symbol-function 'jabber-receipts--display-buffer)
                       (lambda (&rest _) buffer))
                      ((symbol-function 'get-buffer-window) (lambda (&rest _) t)))
              (dolist (owner (list b a))
                (jabber-receipts--maybe-send-receipt owner xml "peer@example.test/Phone" nil)
                (jabber-receipts--track-displayed owner xml "peer@example.test/Phone" nil)))
            (should (= (length sent) 2))
            (should (cl-every (lambda (entry) (eq (car entry) a)) sent))))))))

(ert-deftest jabber-test-contact-owners-groups-completion-resources ()
  (jabber-test-contact--with-owners
    (jabber-test-contact--roster a "Alice" "both" t)
    (jabber-test-contact--roster b "Bob" "none" t)
    (dolist (entry (list (cons a "Phone/A") (cons b "Phone/B")))
      (jabber-process-presence (car entry)
                              `(presence ((from . ,(concat "peer@example.test/" (cdr entry)))))))
    (let* ((pa (jabber-jid-symbol "peer@example.test" a))
           (pb (jabber-jid-symbol "peer@example.test" b))
           (table (jabber--jid-completion-table (list pa)))
           (metadata (completion-metadata "" (jabber--jid-completion-with-metadata table) nil)))
      (should (eq pa (car (gethash "Alice" (plist-get (fsm-get-state-data a) :roster-hash)))))
      (should (eq pb (car (gethash "Bob" (plist-get (fsm-get-state-data b) :roster-hash)))))
      (should (string-match-p "Alice" (funcall (completion-metadata-get metadata 'annotation-function)
                                               "peer@example.test")))
      (should (equal (jabber-info--connected-resources "peer@example.test" a)
                     '("peer@example.test/Phone/A")))
      (should (equal (jabber-info--connected-resources "peer@example.test" b)
                     '("peer@example.test/Phone/B")))
      (let ((jabber-jid-completion-display 'name))
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (_prompt collection &rest _)
                     (should (equal (all-completions "" collection) '("Bob")))
                     "Bob")))
          (should (equal (jabber-read-jid-completing "Peer: " nil t nil 'full nil b)
                         "peer@example.test/Phone/B"))))
      (let ((full (jabber--roster-full-jids (list pb))))
        (should (equal (mapcar #'symbol-name full) '("peer@example.test/Phone/B")))
        (should (eq (jabber-jid-owner (car full)) b)))
      (let ((jabber-jid-completion-display 'jid))
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (_prompt collection &rest _)
                     (should (equal (all-completions "" collection)
                                    '("peer@example.test/Exact/Case")))
                     "peer@example.test/Exact/Case")))
          (should (equal (jabber-read-jid-completing
                          "Peer: " (list (make-symbol "peer@example.test/Exact/Case"))
                          t nil nil nil b)
                         "peer@example.test/Exact/Case"))))
      (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "peer@example.test")))
        ;; Ambiguous aggregate completion must not borrow the first resource.
        (should (equal (jabber-read-jid-completing "Peer: " nil nil nil 'full)
                       "peer@example.test")))
      (let ((empty (jabber-test-contact--owner "empty")))
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (_prompt collection &rest _)
                     (should-not (all-completions "" collection)) "")))
          (should-not (jabber-read-jid-completing "Peer: " nil nil nil nil nil empty)))))))

(ert-deftest jabber-test-contact-owners-priority-caps-extension ()
  (jabber-test-contact--with-owners
    (jabber-test-contact--roster a "A" "both" t)
    (jabber-test-contact--roster b "B" "none" t)
    (let ((pa (jabber-jid-symbol "peer@example.test" a))
          (pb (jabber-jid-symbol "peer@example.test" b)))
      (jabber-caps--store-hash "peer@example.test/Phone" '("sha-1" . "A") a)
      (jabber-caps--store-hash "peer@example.test/Phone" '("sha-1" . "B") b)
      (dolist (owner (list a b))
        (jabber-process-presence owner '(presence ((from . "peer@example.test/Phone"))
                                                 (priority () "10"))))
      (should (equal (plist-get (cdr (assoc "Phone" (get pa 'resources))) 'caps)
                     '("sha-1" . "A")))
      (should (equal (plist-get (cdr (assoc "Phone" (get pb 'resources))) 'caps)
                     '("sha-1" . "B")))
      (jabber-process-presence a '(presence ((from . "peer@example.test/Desktop"))
                                            (priority () "10")))
      ;; Existing equal-priority rule: first resource in the stored alist wins.
      (should (equal (get pa 'resource) "Desktop"))
      (jabber-process-presence a '(presence ((from . "peer@example.test/Desktop")
                                            (type . "error"))
                                           (error ((code . "500")) (text nil "bad"))))
      (should (equal (get pa 'resource) "Phone"))
      (should (get pb 'connected)))))

(ert-deftest jabber-test-contact-owners-lifetime-and-cleanup ()
  (jabber-test-contact--with-owners
    (jabber-test-contact--roster a "A" "both" t)
    (jabber-test-contact--roster b "B" "none" t)
    (let ((pa (jabber-jid-symbol "peer@example.test" a))
          (pb (jabber-jid-symbol "peer@example.test" b)))
      (put a :state-data (jabber-sm--prepare-drain-state (fsm-get-state-data a)))
      (should (eq (jabber-jid-symbol "PEER@EXAMPLE.TEST/Resource" a) pa))
      (should-not (get (jabber-jid-symbol "peer@example.test"
                                        (jabber-test-contact--owner "A")) 'name))
      (let ((jabber-pre-disconnect-hook nil)
            (jabber-post-disconnect-hook nil))
        (cl-letf (((symbol-function 'fsm-send-sync)
                   (lambda (jc _event) (setq jabber-connections (delq jc jabber-connections)))))
          (jabber-disconnect-one a)
          (should-not (get pa 'name))
          (should (eq (jabber-jid-owner pa) a))
          (should (equal (get pb 'name) "B"))
          (jabber-disconnect)
          (should-not (get pb 'name))
          (should-not jabber-connections))))))

(ert-deftest jabber-test-contact-owners-avatar-delayed-vcard ()
  (jabber-test-contact--with-owners
    (let* ((pa (jabber-jid-symbol "peer@example.test" a))
           (pb (jabber-jid-symbol "peer@example.test" b))
           (jabber-vcard-avatars-retrieve t)
           callbacks)
      (cl-letf (((symbol-function 'jabber-avatar-find-cached) (lambda (_) nil))
                ((symbol-function 'jabber-vcard-avatars-fetch)
                 (lambda (jc from hash) (push (list jc from hash) callbacks))))
        (dolist (owner (list a b))
          (jabber-vcard-avatars-presence
           owner `(presence ((from . "peer@example.test/Phone"))
                            (x ((xmlns . "vcard-temp:x:update"))
                               (photo nil ,(symbol-name owner)))))))
      (should (= (length callbacks) 2))
      (cl-letf (((symbol-function 'jabber-vcard-parse) (lambda (_) '((PHOTO "image/png" "bytes"))))
                ((symbol-function 'jabber-avatar-from-base64-string) (lambda (&rest _) (make-jabber-avatar :sha1-sum "A")))
                ((symbol-function 'jabber-avatar-image) (lambda (_) 'image-A))
                ((symbol-function 'jabber-avatar-cache) #'ignore))
        (put pb 'avatar-hash "B")
        (put pb 'avatar 'image-B)
        (with-temp-buffer
          (setq-local jabber-buffer-connection b)
          (jabber-vcard-avatars-vcard a '(iq nil (vCard nil)) '("peer@example.test" . "A")))
        (should (equal (get pa 'avatar-hash) "A"))
        (should (eq (get pa 'avatar) 'image-A))
        (should (equal (get pb 'avatar-hash) "B"))
        (jabber-vcard-avatars-presence a '(presence ((from . "peer@example.test/Phone"))))
        (should-not (get pa 'avatar-hash))
        (should (eq (get pb 'avatar) 'image-B))))))

(ert-deftest jabber-test-contact-owners-pgp-observation ()
  (jabber-test-contact--with-owners
    (cl-letf (((symbol-function 'epg-verify-string)
               (lambda (context &rest _)
                 (let ((signature (epg-make-signature 'good)))
                   (setf (epg-signature-fingerprint signature) "fingerprint-A"
                         (epg-context-result context) (list (cons 'verify (list signature))))))))
      (jabber-openpgp-legacy--process-presence
       a '(presence ((from . "peer@example.test/Phone"))
                    (x ((xmlns . "jabber:x:signed")) "signature"))))
    (should (equal (get (jabber-jid-symbol "peer@example.test" a) 'pgp-key-id)
                   "fingerprint-A"))
    (should-not (get (jabber-jid-symbol "peer@example.test" b) 'pgp-key-id))))

(ert-deftest jabber-test-contact-owners-background-alert-notification ()
  (jabber-test-contact--with-owners
    (jabber-test-contact--roster a "Alice" "both" t)
    (jabber-test-contact--roster b "Bob" "none" t)
    (let ((target (generate-new-buffer " *contact-owner-B*")) captured)
      (unwind-protect
          (with-temp-buffer
            (setq-local jabber-buffer-connection a)
            (with-current-buffer target (setq-local jabber-buffer-connection b))
            (put (jabber-jid-symbol "peer@example.test" a) 'avatar-hash "A")
            (put (jabber-jid-symbol "peer@example.test" b) 'avatar-hash "B")
            (should (equal (jabber-message-default-message "peer@example.test" target "hello") "Bob:"))
            (cl-letf (((symbol-function 'jabber-avatar-find-cached) (lambda (hash) (concat "icon-" hash)))
                      ((symbol-function 'notifications-notify) (lambda (&rest args) (setq captured args))))
              (jabber-message-notifications "peer@example.test" target "hello" "title")
              (should (equal (plist-get captured :app-icon) "icon-B"))
              (jabber-message-notifications "peer@example.test" nil "hello" "title")
              (should (equal (plist-get captured :app-icon) jabber-notifications-icon))))
        (kill-buffer target)))))

(ert-deftest jabber-test-contact-owners-hook-reset-and-delayed-subscription ()
  (jabber-test-contact--with-owners
    (jabber-test-contact--roster a "Alice" "both" t)
    (jabber-test-contact--roster b "Bob" "none" t)
    (let* ((target (generate-new-buffer " *contact-hook-B*"))
           (jabber-presence-contact-functions nil)
           (jabber-alert-presence-message-function
            (lambda (who _old _new _status)
              (should (eq (jabber-jid-owner who) b)) "title"))
           (jabber-presence-hooks
            (list (lambda (who _old _new _status title)
                    (should (eq (jabber-jid-owner who) b))
                    (should (equal title "title")))))
           pending)
      (unwind-protect
          (progn
            (with-current-buffer target
              (setq-local major-mode 'jabber-chat-mode
                          jabber-buffer-connection b
                          jabber-chatting-with "peer@example.test")
              (setq-local jabber-chat-ewoc (ewoc-create #'ignore)))
            (jabber-test-contact--roster b "Bob reset" "none" t)
            (jabber-process-presence b '(presence ((from . "peer@example.test/Phone"))))
            (cl-letf (((symbol-function 'run-with-idle-timer)
                       (lambda (_seconds _repeat fn &rest args) (setq pending (cons fn args)))))
              (jabber-process-presence b '(presence ((from . "peer@example.test")
                                                      (type . "subscribe")))))
            (with-temp-buffer
              (setq-local jabber-buffer-connection a)
              (cl-letf (((symbol-function 'jabber-chat-create-buffer) (lambda (&rest _) target)))
                (apply (car pending) (cdr pending))))
            (should (equal (jabber-presence-only-chat-open-message
                            (jabber-jid-symbol "peer@example.test" b) nil "subscribe" nil)
                           "Bob reset requests subscription to your presence"))
            (should-not (jabber-presence-only-chat-open-message
                         (jabber-jid-symbol "peer@example.test" a) nil "subscribe" nil))
            (let* ((replacement (jabber-test-contact--owner "B"))
                   (jabber-connections (cons replacement jabber-connections)))
              (should-not (jabber-presence-only-chat-open-message
                           (jabber-jid-symbol "peer@example.test" replacement)
                           nil "subscribe" nil))))
        (kill-buffer target)))))

(ert-deftest jabber-test-contact-owners-renderers-and-bookmarks ()
  (jabber-test-contact--with-owners
    (jabber-test-contact--roster a "Alice" "both" t)
    (jabber-test-contact--roster b "Bob" "none" t)
    (let ((jabber-bookmarks (make-hash-table :test #'equal))
          (jabber-mode-line-compact t)
          (jabber-mode-line-contacts nil))
      (puthash "A@example.test" '((:jid "peer@example.test" :name "A room")) jabber-bookmarks)
      (puthash "B@example.test" '((:jid "peer@example.test" :name "B room")) jabber-bookmarks)
      (should (equal (jabber-jid-bookmarkname "peer@example.test" b) "B room"))
      (should (equal (jabber-jid-bookmarkname "peer@example.test") "peer@example.test"))
      (puthash "B@example.test" t jabber-bookmarks)
      (should (equal (jabber-jid-bookmarkname "peer@example.test" b) "Bob"))
      (put (jabber-jid-symbol "peer@example.test" a) 'show "chat")
      (jabber-mode-line--do-count-contacts)
      (should (equal jabber-mode-line-contacts "(1/0/1)")))
    (with-temp-buffer
      (setq-local jabber-buffer-connection b
                  jabber-chatting-with "peer@example.test"
                  jabber-message-thread-peer "peer@example.test")
      (should (string-match-p "Bob" (jabber-message-thread--header)))
      (should (equal (jabber-chat--reply-context-label
                      '(:reply-to-id "one" :reply-to-jid "peer@example.test")) "reply to Bob"))
      (should (equal (jabber-reactions--entry-help-echo
                      '(:reaction "+" :senders ("peer@example.test")) b) "+: Bob"))
      (let ((jabber-group "room@example.test"))
        (should (equal (jabber-message-reply--author-name "peer@example.test") "Bob")))
      (let ((jabber-chatstates--ewoc-node nil) entry)
        (cl-letf (((symbol-function 'jabber-chat-ewoc-enter) (lambda (data) (setq entry data))))
          (jabber-chatstates--update-ewoc 'composing))
        (should (equal (cadr entry) "Bob is typing...")))
      (let ((widget (widget-convert 'jabber-widget-jid :jabber-connection b)))
        (should (equal (widget-apply widget :value-to-internal "peer@example.test")
                       "Bob <peer@example.test>"))))
    (let (compose)
      (unwind-protect
          (with-temp-buffer
            (setq-local jabber-buffer-connection a)
            (cl-letf (((symbol-function 'pop-to-buffer) (lambda (buffer &rest _) (setq compose buffer))))
              (jabber-compose b "peer@example.test"))
            (should (string-match-p "Bob" (buffer-name compose)))
            (should (eq (buffer-local-value 'jabber-buffer-connection compose) b)))
        (when (buffer-live-p compose) (kill-buffer compose))))))

(ert-deftest jabber-test-contact-owners-observation-render-and-query ()
  (dolist (reverse '(nil t))
    (jabber-test-contact--with-owners
      (cl-letf (((symbol-function 'jabber-avatar-cache) #'ignore)
                ((symbol-function 'jabber-avatar-image)
                 (lambda (avatar) (jabber-avatar-sha1-sum avatar)))
                ((symbol-function 'jabber-vcard-parse) (lambda (_) '((PHOTO "image/png" "bytes")))))
        (dolist (owner (if reverse (list b a) (list a b)))
          (let* ((name (symbol-name owner))
                 (full (concat "peer@example.test/" name)))
            (jabber-test-contact--roster owner name "both" t)
            (jabber-caps--store-hash full (cons "sha-1" name) owner)
            (jabber-process-presence
             owner `(presence ((from . ,full)) (status () ,(concat name " status"))))
            (cl-letf (((symbol-function 'jabber-avatar-from-base64-string)
                       (lambda (&rest _) (make-jabber-avatar :sha1-sum name)))
                      ((symbol-function 'epg-verify-string)
                       (lambda (context &rest _)
                         (let ((signature (epg-make-signature 'good)))
                           (setf (epg-signature-fingerprint signature) name
                                 (epg-context-result context)
                                 (list (cons 'verify (list signature))))))))
              (jabber-vcard-avatars-vcard owner '(iq nil (vCard nil))
                                          (cons "peer@example.test" name))
              (jabber-openpgp-legacy--process-presence
               owner `(presence ((from . ,full))
                                (x ((xmlns . "jabber:x:signed")) "signature")))))))
      (dolist (owner (list a b))
        (let* ((name (symbol-name owner))
               (full (concat "peer@example.test/" name))
               (contact (jabber-jid-symbol "peer@example.test" owner))
               sent)
          (should (equal (get contact 'pgp-key-id) name))
          (should (equal (plist-get (cdr (assoc name (get contact 'resources))) 'caps)
                         (cons "sha-1" name)))
          (with-temp-buffer
            (setq-local jabber-buffer-connection owner
                        jabber-chatting-with "peer@example.test")
            ;; Evaluate the production header forms, not a parallel renderer.
            (let ((fields (mapcar (lambda (entry) (eval (cadr entry) t))
                                  (cl-remove-if-not
                                   (lambda (entry) (eq (car-safe entry) :eval))
                                   jabber-chat-header-line-format))))
              (should (equal (car fields) name))
              (should (equal (nth 2 fields) (concat name " status"))))
            (should (equal (get-text-property
                            0 'display
                            (eval (cadr (cadr (nth 1 jabber-chat-header-line-format))) t))
                           name))
            (jabber-muc-private-print-prompt '(:from "peer@example.test/Nick"))
            (should (string-match-p (concat name "/Nick") (buffer-string)))
            (erase-buffer)
            (let ((buffer (current-buffer)))
              (cl-letf (((symbol-function 'jabber-browse--buffer) (lambda (_) buffer))
                        ((symbol-function 'display-buffer) #'ignore)
                        ((symbol-function 'jabber-send-iq)
                         (lambda (jc to &rest _) (push (cons jc to) sent)))
                        ((symbol-function 'jabber-ping-send)
                         (lambda (jc to &rest _) (push (cons jc to) sent))))
                (jabber-get-info owner "peer@example.test")))
            (should (cl-some (lambda (entry) (equal (cdr entry) full)) sent))
            (should (cl-every (lambda (entry)
                                (and (eq (car entry) owner)
                                     (member (cdr entry) (list "peer@example.test" full))))
                              sent))))))))

(ert-deftest jabber-test-contact-owners-named-resource-completion ()
  "Select exact resources through the reader and interactive version command."
  (dolist (resources '((("Phone") ("DeskTOP"))
                       (("DeskTOP") ("Phone"))
                       (("Phone") ("phone"))
                       (("phone") ("Phone"))))
    (dolist (display '(name jid))
      (jabber-test-contact--with-owners
        (let* ((jabber-jid-completion-display display)
               (contact (jabber-jid-symbol "alice@example.test" b)))
          (put contact 'name "Alice")
          (put contact 'resources resources)
          (setf (plist-get (get b :state-data) :roster) (list contact))
          (dolist (resource resources)
            (let* ((expected (concat "alice@example.test/" (car resource)))
                   (fulls (jabber--roster-full-jids (list contact)))
                   (table (jabber--jid-completion-table fulls))
                   (label (car (cl-find expected table
                                       :key (lambda (entry) (symbol-name (cdr entry)))
                                       :test #'equal)))
                   sent)
              (should (= 2 (length (delete-dups (mapcar #'car table)))))
              (cl-letf (((symbol-function 'jabber-read-account) (lambda (&rest _) b))
                        ((symbol-function 'completing-read)
                         (lambda (_prompt collection &rest _)
                           (should (member label (all-completions "" collection)))
                           (should (= 2 (length (all-completions
                                                 "alice@example.test/" collection))))
                           (should (test-completion label collection))
                           label))
                        ((symbol-function 'jabber-send-iq)
                         (lambda (owner to &rest _) (setq sent (list owner to)))))
                (call-interactively #'jabber-get-version)
                (should (equal sent (list b expected)))
                ;; Explicit ownership must re-scope a foreign full-JID subset.
                (let ((foreign (mapcar (lambda (full)
                                         (let ((copy (make-symbol (symbol-name full))))
                                           (put copy 'jabber--jid-owner a)
                                           (put copy 'name "Foreign")
                                           copy))
                                       fulls)))
                  (should (equal (jabber-read-jid-completing
                                  "Resource: " foreign t nil 'full t b)
                                 expected))))
              ;; Accepting a full-JID default must retain its exact resource.
              (cl-letf (((symbol-function 'completing-read)
                         (lambda (_prompt collection _pred _match _initial _history default &rest _)
                           (should (member default (all-completions "" collection)))
                           default)))
                (should (equal (jabber-read-jid-completing
                                "Resource: " fulls t expected 'full t b)
                               expected))))))))))

(provide 'jabber-test-contact-owners)
;;; jabber-test-contact-owners.el ends here
