;;; jabber-test-muc-affiliations.el --- Owned MUC snapshots -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'jabber-core)
(require 'jabber-muc)
(require 'jabber-omemo)

(defun jabber-test-muc-aff--connection (user)
  "Return a disposable established connection for USER."
  (let ((jc (make-symbol user)))
    (put jc :name 'jabber-connection)
    (put jc :state :session-established)
    (put jc :state-data
         (jabber-sm--reset
          (list :username user :server "example.org"
                :connection (list 'transport) :session-id "stream")))
    jc))

(defmacro jabber-test-muc-aff--with-room (&rest body)
  "Run BODY with two isolated connections and a room."
  (declare (indent 0) (debug t))
  `(let* ((a (jabber-test-muc-aff--connection "a"))
          (b (jabber-test-muc-aff--connection "b"))
          (room "room@conference.example.org")
          (jabber-connections (list a b))
          (jabber-muc--rooms (make-hash-table :test #'equal))
          (jabber-muc--room-jids (make-hash-table :test #'equal))
          (jabber-muc--nonanonymous-rooms (make-hash-table :test #'equal))
          (jabber-muc--rooms-before-disconnect (make-hash-table :test #'equal))
          (jabber-muc--session-passwords (make-hash-table :test #'equal))
          (jabber-muc-participants nil)
          (jabber-open-info-queries nil)
          (jabber-muc--autojoin-queue nil)
          (jabber-muc--autojoin-pending nil)
          (jabber-muc--autojoin-disco-count nil)
          (jabber-muc--autojoin-timer nil)
          (jabber-presence-chain '(jabber-muc-process-presence))
          (jabber-iq-chain '(jabber-process-iq))
          sent)
     (jabber-muc-add-groupchat room "self-a" a)
     (jabber-muc-add-groupchat room "self-b" b)
     (cl-letf (((symbol-function 'jabber-send-sexp)
                (lambda (jc xml &rest _) (push (cons jc xml) sent))))
       ,@body)))

(defun jabber-test-muc-aff--requests (sent jc)
  "Return affiliation/ID pairs from SENT stanzas on JC."
  (cl-loop for (owner . xml) in sent when (eq owner jc)
           collect (cons (jabber-xml-get-attribute
                          (car (jabber-xml-get-children (jabber-iq-query xml) 'item))
                          'affiliation)
                         (jabber-xml-get-attribute xml 'id))))

(defun jabber-test-muc-aff--reply (jc room requests affiliation jids &optional from)
  "Deliver a native FSM IQ on JC for ROOM from REQUESTS.
AFFILIATION selects the request; JIDS become items.  FROM overrides issuer."
  (fsm-send-sync
   jc `(:stanza
        (iq ((type . "result") (id . ,(cdr (assoc affiliation requests)))
             (from . ,(or from room)))
            (query ((xmlns . ,jabber-muc-xmlns-admin))
                   ,@(mapcar (lambda (jid)
                               `(item ((jid . ,jid) (affiliation . ,affiliation))))
                             jids))))))

(defun jabber-test-muc-aff--recipients (jc room)
  "Collect ROOM recipients using JC's buffer context."
  (let ((jabber-buffer-connection jc))
    (sort (jabber-omemo--muc-participant-jids
           room (cdr (assoc room jabber-muc-participants))) #'string<)))

(defun jabber-test-muc-aff--presence (jc room nick jid &optional unavailable)
  "Dispatch native occupant presence on JC in ROOM for NICK and JID.
UNAVAILABLE removes the occupant."
  (fsm-send-sync
   jc `(:stanza
        (presence ((from . ,(concat room "/" nick))
                   ,@(when unavailable '((type . "unavailable"))))
                  (x ((xmlns . ,jabber-muc-xmlns-user))
                     (item ((jid . ,jid) (role . "participant")
                            (affiliation . "none"))))))))

(ert-deftest jabber-test-muc-aff-two-accounts-native-iq ()
  (jabber-test-muc-aff--with-room
    (jabber-muc--query-affiliations a room)
    (jabber-muc--query-affiliations b room)
    (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a)
                                "member" '("alice@example.org"))
    (jabber-test-muc-aff--reply b room (jabber-test-muc-aff--requests sent b)
                                "member" '("bob@example.org"))
    (should (equal (jabber-test-muc-aff--recipients a room) '("alice@example.org")))
    (should (equal (jabber-test-muc-aff--recipients b room) '("bob@example.org")))))

(ert-deftest jabber-test-muc-aff-empty-reduced-and-other-categories ()
  (jabber-test-muc-aff--with-room
    (jabber-muc--query-affiliations a room)
    (let ((first (jabber-test-muc-aff--requests sent a)))
      (jabber-test-muc-aff--reply a room first "member" '("old@example.org" "kept@example.org"))
      (jabber-test-muc-aff--reply a room first "admin" '("admin@example.org")))
    (jabber-muc--query-affiliations a room)
    (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a)
                                "member" '("kept@example.org"))
    (should (equal (jabber-test-muc-aff--recipients a room)
                   '("admin@example.org" "kept@example.org")))
    (jabber-muc--query-affiliations a room)
    (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a) "member" nil)
    (should (equal (jabber-test-muc-aff--recipients a room) '("admin@example.org")))))

(ert-deftest jabber-test-muc-aff-out-of-order-and-state-copy ()
  (jabber-test-muc-aff--with-room
    (jabber-muc--query-affiliations a room)
    (let ((old (jabber-test-muc-aff--requests sent a))
          (state (fsm-get-state-data a)))
      (jabber-sm--drain-pending a state)
      (should-not (eq state (fsm-get-state-data a)))
      (jabber-test-muc-aff--reply a room old "owner" '("owner@example.org"))
      (should (equal (jabber-test-muc-aff--recipients a room) '("owner@example.org")))
      (jabber-muc--query-affiliations a room)
      (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a) "owner" nil)
      (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a)
                                  "member" '("new@example.org"))
      (jabber-test-muc-aff--reply a room old "member" '("obsolete@example.org"))
      (should (equal (jabber-test-muc-aff--recipients a room) '("new@example.org"))))))

(ert-deftest jabber-test-muc-aff-foreign-response-keeps-native-request ()
  (jabber-test-muc-aff--with-room
    (jabber-muc--query-affiliations a room)
    (let* ((requests (jabber-test-muc-aff--requests sent a))
           (id (cdr (assoc "member" requests))))
      (jabber-test-muc-aff--reply b room requests "member" '("foreign@example.org"))
      (should (assoc id jabber-open-info-queries))
      (jabber-test-muc-aff--reply a room requests "member" '("foreign@example.org") "evil@example.org")
      (should (assoc id jabber-open-info-queries))
      (should-not (jabber-test-muc-aff--recipients a room))
      (fsm-send-sync a `(:stanza (iq ((type . "result") (from . ,room) (id . ,id))
                                    (query ((xmlns . "wrong-namespace"))))))
      (should (assoc id jabber-open-info-queries))
      (jabber-test-muc-aff--reply a room requests "member" '("valid@example.org"))
      (should-not (assoc id jabber-open-info-queries))
      (should (equal (jabber-test-muc-aff--recipients a room) '("valid@example.org"))))))

(ert-deftest jabber-test-muc-aff-leave-rejoin-late-result ()
  (jabber-test-muc-aff--with-room
    (jabber-muc--query-affiliations a room)
    (let ((old (jabber-test-muc-aff--requests sent a)))
      (jabber-muc-remove-groupchat room a)
      (jabber-test-muc-aff--reply a room old "member" '("retired@example.org"))
      (should-not (jabber-test-muc-aff--recipients a room))
      (jabber-muc-add-groupchat room "successor" a)
      (jabber-muc--query-affiliations a room)
      (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a) "member" nil)
      (jabber-test-muc-aff--reply a room old "admin" '("retired@example.org"))
      (should-not (jabber-test-muc-aff--recipients a room)))))

(ert-deftest jabber-test-muc-aff-reconnect-account-and-transport ()
  (dolist (change '((:connection . replacement) (:session-id . "new-stream")
                    (:username . "new-account")))
    (jabber-test-muc-aff--with-room
      (jabber-muc--query-affiliations a room)
      (let ((old (jabber-test-muc-aff--requests sent a)))
        (jabber-test-muc-aff--reply a room old "member" '("old@example.org"))
        (plist-put (fsm-get-state-data a) (car change) (cdr change))
        (should-not (jabber-test-muc-aff--recipients a room))
        (jabber-muc--query-affiliations a room)
        (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a) "member" nil)
        (jabber-test-muc-aff--reply a room old "admin" '("old@example.org"))
        (should-not (jabber-test-muc-aff--recipients a room))))))

(ert-deftest jabber-test-muc-aff-current-occupants-and-offline-members ()
  (jabber-test-muc-aff--with-room
    (jabber-test-muc-aff--presence a room "shared" "alice@example.org/a")
    (jabber-test-muc-aff--presence b room "shared" "bob@example.org/b")
    (jabber-muc--query-affiliations a room)
    (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a)
                                "member" '("offline@example.org"))
    (should (equal (jabber-test-muc-aff--recipients a room)
                   '("alice@example.org" "offline@example.org")))
    (should (equal (jabber-test-muc-aff--recipients b room) '("bob@example.org")))
    (jabber-test-muc-aff--presence a room "shared" "alice@example.org/a" t)
    (should (equal (jabber-test-muc-aff--recipients a room) '("offline@example.org")))
    (should (equal (jabber-test-muc-aff--recipients b room) '("bob@example.org")))))

(ert-deftest jabber-test-muc-aff-disconnect-reconnect-native-lifecycle ()
  (jabber-test-muc-aff--with-room
    (jabber-muc--query-affiliations a room)
    (jabber-muc--query-affiliations b room)
    (let ((old (jabber-test-muc-aff--requests sent a)))
      (jabber-test-muc-aff--reply b room (jabber-test-muc-aff--requests sent b)
                                  "member" '("bob@example.org"))
      (jabber-muc--session-reset a)
      (should-not (gethash (list a room) jabber-muc--room-jids))
      (jabber-test-muc-aff--reply a room old "member" '("retired@example.org"))
      (should-not (gethash (list a room) jabber-muc--room-jids))
      (should (equal (jabber-test-muc-aff--recipients b room) '("bob@example.org")))
      (plist-put (fsm-get-state-data a) :connection (list 'replacement))
      (plist-put (fsm-get-state-data a) :session-id "successor-stream")
      (jabber-muc-add-groupchat room "successor" a)
      (jabber-muc--query-affiliations a room)
      (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a)
                                  "member" '("new@example.org"))
      (jabber-test-muc-aff--reply a room old "admin" '("retired@example.org"))
      (should (equal (jabber-test-muc-aff--recipients a room) '("new@example.org"))))))

(ert-deftest jabber-test-muc-aff-sender-scope-and-revoked-inference ()
  (jabber-test-muc-aff--with-room
    (jabber-test-muc-aff--presence a room "shared" "alice@example.org/a")
    (jabber-test-muc-aff--presence b room "shared" "bob@example.org/b")
    (let ((xml `(message ((from . ,(concat room "/shared")) (type . "groupchat")))))
      (should (equal (jabber-omemo--resolve-sender-jid xml a) "alice@example.org"))
      (should (equal (jabber-omemo--resolve-sender-jid xml b) "bob@example.org"))
      (jabber-muc-remove-groupchat room a)
      (should-not (jabber-omemo--resolve-sender-jid xml a)))
    (jabber-test-muc-aff--presence b room "unknown" nil)
    (jabber-muc--query-affiliations b room)
    (jabber-test-muc-aff--reply b room (jabber-test-muc-aff--requests sent b)
                                "member" '("offline@example.org"))
    (let ((xml `(message ((from . ,(concat room "/unknown")) (type . "groupchat")))))
      (should (equal (jabber-omemo--resolve-sender-jid xml b) "offline@example.org"))
      (jabber-muc--query-affiliations b room)
      (jabber-test-muc-aff--reply b room (jabber-test-muc-aff--requests sent b) "member" nil)
      (should-not (jabber-omemo--resolve-sender-jid xml b)))))

(ert-deftest jabber-test-muc-aff-pending-occupants-survive-self-presence ()
  (jabber-test-muc-aff--with-room
    (jabber-muc-remove-groupchat room a)
    (let ((attempt (jabber-muc--start-attempt a room "self-a")))
      (unwind-protect
          (cl-letf (((symbol-function 'jabber-mam-muc-joined) #'ignore)
                    ((symbol-function 'jabber-bookmarks-auto-add-maybe) #'ignore))
            (jabber-test-muc-aff--presence a room "early" "early@example.org/device")
            (should-not (jabber-test-muc-aff--recipients a room))
            (jabber-test-muc-aff--presence a room "self-a" "a@example.org/device")
            (should (equal (jabber-test-muc-aff--recipients a room)
                           '("a@example.org" "early@example.org"))))
        (when (timerp (plist-get attempt :timer))
          (cancel-timer (plist-get attempt :timer)))))))

(ert-deftest jabber-test-muc-aff-callback-cannot-recreate-or-replay ()
  (jabber-test-muc-aff--with-room
    (jabber-muc--query-affiliations a room)
    (let* ((requests (jabber-test-muc-aff--requests sent a))
           (id (cdr (assoc "member" requests)))
           (callback (nth 1 (assoc id jabber-open-info-queries)))
           (xml `(iq ((from . ,room) (type . "result"))
                     (query ((xmlns . ,jabber-muc-xmlns-admin))
                            (item ((jid . "obsolete@example.org")
                                   (affiliation . "member")))))))
      (jabber-test-muc-aff--reply a room requests "member" nil)
      (funcall (car callback) a xml (cdr callback))
      (should-not (jabber-test-muc-aff--recipients a room))
      (jabber-muc-remove-groupchat room a)
      (funcall (car callback) a xml (cdr callback))
      (should-not (gethash (list a room) jabber-muc--room-jids)))))

(ert-deftest jabber-test-muc-aff-blocking-uses-owned-recipients ()
  (jabber-test-muc-aff--with-room
    (plist-put (fsm-get-state-data a) :blocking-list '("blocked@example.org"))
    (jabber-test-muc-aff--presence a room "shared" "blocked@example.org/device")
    (jabber-test-muc-aff--presence b room "shared" "allowed@example.org/device")
    (should-error (jabber-omemo--check-blocking a room t) :type 'user-error)
    (should-not (jabber-omemo--check-blocking b room t))
    (jabber-test-muc-aff--presence a room "shared" "blocked@example.org/device" t)
    (should-not (jabber-omemo--check-blocking a room t))))

(ert-deftest jabber-test-muc-aff-offline-nick-is-not-an-occupant ()
  (jabber-test-muc-aff--with-room
    (jabber-muc--query-affiliations a room)
    (fsm-send-sync
     a `(:stanza
         (iq ((type . "result") (from . ,room)
              (id . ,(cdr (assoc "member" (jabber-test-muc-aff--requests sent a)))))
             (query ((xmlns . ,jabber-muc-xmlns-admin))
                    (item ((jid . "offline@example.org") (nick . "absent")
                           (affiliation . "member")))))))
    (should (equal (jabber-test-muc-aff--recipients a room) '("offline@example.org")))
    (should-not (jabber-omemo--resolve-sender-jid
                 `(message ((from . ,(concat room "/absent")) (type . "groupchat"))) a))
    (jabber-muc--query-affiliations a room)
    (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a) "member" nil)
    (should-not (jabber-test-muc-aff--recipients a room))))

(ert-deftest jabber-test-muc-aff-inflight-send-rechecks-before-wrapping ()
  (dolist (retire '(nil snapshot membership))
    (jabber-test-muc-aff--with-room
      (jabber-muc--query-affiliations a room)
      (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a)
                                  "member" '("peer@example.org"))
      (let ((jabber-group room)
            (jabber-buffer-connection a)
            (jabber-omemo--pending-send-operations (make-hash-table :test #'eq))
            (wrapped 0) (failed 0) continuation)
        (cl-letf (((symbol-function 'jabber-chat--capture-input-owner)
                   (lambda () (lambda () t)))
                  ((symbol-function 'jabber-omemo--ensure-sessions-multi)
                   (lambda (_jc _jids callback) (setq continuation callback)))
                  ((symbol-function 'jabber-omemo--ensure-sessions)
                   (lambda (_jc _jid callback) (funcall callback nil)))
                  ((symbol-function 'jabber-omemo-encrypt-message)
                   (lambda (_) (cl-incf wrapped)
                     '(:iv "iv" :key "key" :payload "payload")))
                  ((symbol-function 'jabber-omemo--build-encrypted-xml)
                   (lambda (&rest _) '(encrypted nil))))
          (jabber-omemo--send-muc
           a "correction" '((replace ((id . "original")))) nil
           (lambda (_reason) (cl-incf failed)))
          (pcase retire
            ('snapshot
             (jabber-muc--query-affiliations a room)
             (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a)
                                         "member" nil))
            ('membership
             (jabber-muc-remove-groupchat room a)
             (jabber-muc-add-groupchat room "successor" a)
             (jabber-muc--query-affiliations a room)
             (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a)
                                         "member" '("peer@example.org"))))
          (funcall continuation '((7 "a@example.org" "peer@example.org" session)))
          (should (= wrapped (if retire 0 1)))
          (should (= failed (if retire 1 0))))))))

(defun jabber-test-muc-aff--resume (jc)
  "Deliver a successful native SM resume on a replacement transport for JC."
  (let ((jabber-post-resume-hooks nil))
    (plist-put (fsm-get-state-data jc) :sm-enabled t)
    (plist-put (fsm-get-state-data jc) :sm-id "resume-id")
    (plist-put (fsm-get-state-data jc) :sm-resuming t)
    (plist-put (fsm-get-state-data jc) :connection (list 'resumed-transport))
    ;; A real resumed connection receives a new stream header before <resumed>.
    (put jc :state :connected)
    (let ((jabber-use-sasl t))
      (fsm-send-sync jc '(:stream-start "replacement-stream" "1.0")))
    (should (equal (plist-get (fsm-get-state-data jc) :session-id) "replacement-stream"))
    (put jc :state :sm-resume)
    (cl-letf (((symbol-function 'jabber-sm--start-r-timer) (lambda (_jc data) data))
              ((symbol-function 'jabber-sm--schedule-drain) #'ignore))
      (fsm-send-sync jc '(:stanza (resumed ((xmlns . "urn:xmpp:sm:3")
                                           (h . "0") (previd . "resume-id"))))))
    (should (eq (get jc :state) :session-established))))

(defun jabber-test-muc-aff--sender (jc room nick)
  "Resolve NICK's native encrypted sender identity in ROOM on JC."
  (jabber-omemo--resolve-sender-jid
   `(message ((from . ,(concat room "/" nick)) (type . "groupchat"))) jc))

(ert-deftest jabber-test-muc-aff-resume-ready-identities ()
  "Resume retains current identities, not old query or membership authority."
  (jabber-test-muc-aff--with-room
    (jabber-muc--start-attempt a room "self-a")
    (jabber-test-muc-aff--presence a room "self-a" nil)
    (jabber-test-muc-aff--presence a room "online" "online@example.org/device")
    (jabber-test-muc-aff--presence b room "online" "other@example.org/device")
    (jabber-muc--query-affiliations a room)
    (jabber-muc--query-affiliations b room)
    (let ((old (jabber-test-muc-aff--requests sent a))
          (other (jabber-test-muc-aff--requests sent b))
          (membership (assq a (jabber-muc-room-entries room)))
          (record (jabber-muc--identity-record a room)))
      (jabber-test-muc-aff--reply a room old "member" '("offline@example.org"))
      (jabber-test-muc-aff--resume a)
      (should (eq membership (assq a (jabber-muc-room-entries room))))
      (should (jabber-sm--room-ready-p (fsm-get-state-data a) room))
      (should (equal (jabber-test-muc-aff--recipients a room)
                     '("offline@example.org" "online@example.org")))
      (should (equal (jabber-test-muc-aff--sender a room "online") "online@example.org"))
      (should-not (eq record (jabber-muc--identity-record a room)))
      (jabber-test-muc-aff--presence a room "new" "new@example.org/device")
      (jabber-test-muc-aff--reply a room old "admin" '("stale@example.org"))
      (should (equal (jabber-test-muc-aff--recipients a room)
                     '("new@example.org" "offline@example.org" "online@example.org")))
      ;; Another account's still-current query and occupant survive the transfer.
      (jabber-test-muc-aff--reply b room other "member" '("other-offline@example.org"))
      (should (equal (jabber-test-muc-aff--recipients b room)
                     '("other-offline@example.org" "other@example.org")))
      (jabber-muc--query-affiliations a room)
      (jabber-test-muc-aff--reply a room (jabber-test-muc-aff--requests sent a) "member" nil)
      (jabber-test-muc-aff--presence a room "online" "online@example.org/device" t)
      (jabber-test-muc-aff--presence a room "new" "new@example.org/device" t)
      (should-not (jabber-test-muc-aff--recipients a room))
      (should-not (jabber-test-muc-aff--sender a room "online"))
      (jabber-muc-remove-groupchat room a)
      (jabber-muc-add-groupchat room "successor" a)
      (jabber-test-muc-aff--reply a room old "owner" '("stale@example.org"))
      (should-not (jabber-test-muc-aff--recipients a room)))))

(ert-deftest jabber-test-muc-aff-resume-pending-identities ()
  "A pending join transfers early occupants but cannot send until confirmed."
  (jabber-test-muc-aff--with-room
    (jabber-muc-remove-groupchat room a)
    (jabber-muc--start-attempt a room "self-a")
    (unwind-protect
        (cl-letf (((symbol-function 'jabber-mam-muc-joined) #'ignore)
                  ((symbol-function 'jabber-bookmarks-auto-add-maybe) #'ignore))
          (jabber-test-muc-aff--presence a room "early" "early@example.org/device")
          (let ((old (jabber-sm--room-attempt (fsm-get-state-data a) room)))
            (jabber-test-muc-aff--resume a)
            (should-not (jabber-muc--attempt-current-p a room old t))
            (should-not (jabber-test-muc-aff--recipients a room))
            (jabber-test-muc-aff--presence a room "later" "later@example.org/device")
            (jabber-test-muc-aff--presence a room "self-a" nil)
            (should (equal (jabber-test-muc-aff--recipients a room)
                           '("early@example.org" "later@example.org")))
            (should (equal (jabber-test-muc-aff--sender a room "early") "early@example.org"))
            (jabber-test-muc-aff--presence a room "early" "early@example.org/device" t)
            (jabber-test-muc-aff--presence a room "later" "later@example.org/device" t)
            (should-not (jabber-test-muc-aff--recipients a room))))
      (let ((timer (plist-get (jabber-sm--room-attempt (fsm-get-state-data a) room) :timer)))
        (when (timerp timer) (cancel-timer timer))))))

(ert-deftest jabber-test-muc-aff-resume-rejects-retired-owners ()
  "Resume cannot bless another account, session, transport or room lifetime."
  (dolist (change '(account session transport membership))
    (jabber-test-muc-aff--with-room
      (jabber-muc--start-attempt a room "self-a")
      (jabber-test-muc-aff--presence a room "self-a" nil)
      (jabber-test-muc-aff--presence a room "old" "old@example.org/device")
      (jabber-muc--query-affiliations a room)
      (let ((old (jabber-test-muc-aff--requests sent a)))
        (jabber-test-muc-aff--reply a room old "member" '("offline@example.org"))
        (pcase change
          ('account (plist-put (fsm-get-state-data a) :username "replacement"))
          ('session (plist-put (jabber-muc--identity-record a room) :session "unowned"))
          ('transport (plist-put (jabber-muc--identity-record a room) :transport 'unowned))
          ('membership
           (jabber-muc-remove-groupchat room a)
           (jabber-muc-add-groupchat room "replacement" a)))
        (jabber-test-muc-aff--resume a)
        (jabber-test-muc-aff--reply a room old "admin" '("stale@example.org"))
        (should-not (jabber-test-muc-aff--recipients a room))
        (should-not (jabber-test-muc-aff--sender a room "old"))))))

(ert-deftest jabber-test-muc-aff-failed-resume-retires-identities ()
  "The native failed-resume fresh-bind path retires the old identity view."
  (jabber-test-muc-aff--with-room
    (let ((jabber-lifecycle-session-reset-functions '(jabber-muc--session-reset)))
      (jabber-muc--start-attempt a room "self-a")
      (jabber-test-muc-aff--presence a room "self-a" nil)
      (jabber-test-muc-aff--presence a room "old" "old@example.org/device")
      (jabber-test-muc-aff--presence b room "old" "other@example.org/device")
      (jabber-muc--query-affiliations a room)
      (let ((old (jabber-test-muc-aff--requests sent a)))
        (jabber-test-muc-aff--reply a room old "member" '("offline@example.org"))
        (put a :state :sm-resume)
        (plist-put (fsm-get-state-data a) :stream-features
                   '(features () (bind ((xmlns . "urn:ietf:params:xml:ns:xmpp-bind")))))
        (cl-letf (((symbol-function 'jabber--send-bind-request) #'ignore))
          (fsm-send-sync a '(:stanza (failed ((xmlns . "urn:xmpp:sm:3"))))))
        (should-not (gethash (list a room) jabber-muc--room-jids))
        (should-not (jabber-test-muc-aff--recipients a room))
        (should (equal (jabber-test-muc-aff--recipients b room) '("other@example.org")))
        (put a :state :session-established)
        (jabber-muc-add-groupchat room "successor" a)
        (jabber-test-muc-aff--reply a room old "admin" '("stale@example.org"))
        (should-not (jabber-test-muc-aff--recipients a room))))))

(ert-deftest jabber-test-muc-aff-concurrent-native-nick-retirement ()
  "Foreign 303 and self confirmation retire aliases without settling our lease."
  (let ((send (symbol-function 'jabber-send-sexp)))
    (dolist (pending '(nil t resume))
      (jabber-test-muc-aff--with-room
        (jabber-muc--start-attempt a room "self-a")
        (jabber-test-muc-aff--presence a room "self-a" "a@example.org/device")
        (jabber-test-muc-aff--presence a room "guest" "guest@example.org/device")
        (jabber-test-muc-aff--presence b room "guest" "other@example.org/device")
        (when pending
          (cl-letf (((symbol-function 'jabber-send-sexp) send)
                    ((symbol-function 'jabber-send-sexp--raw) (lambda (&rest _) t)))
            (jabber-muc-nick a room "new-self")))
        (when (eq pending 'resume) (jabber-test-muc-aff--resume a))
        (let ((attempt (jabber-sm--room-attempt (fsm-get-state-data a) room)))
          (unwind-protect
              (progn
                (fsm-send-sync
                 a `(:stanza (presence ((from . ,(concat room "/guest")) (type . "unavailable"))
                                       (x ((xmlns . ,jabber-muc-xmlns-user))
                                          (item ((nick . "guest-new") (affiliation . "none")))
                                          (status ((code . "303")))))))
                (should (eq attempt (jabber-sm--room-attempt (fsm-get-state-data a) room)))
                (should (eq (plist-get attempt :status) (if pending 'pending 'ready)))
                (should-not (jabber-test-muc-aff--sender a room "guest"))
                (jabber-test-muc-aff--presence a room "guest-new" "guest@example.org/device")
                (should (equal (jabber-test-muc-aff--sender a room "guest-new") "guest@example.org"))
                (jabber-test-muc-aff--presence a room "guest-new" "guest@example.org/device" t)
                (when pending
                  ;; Some servers confirm without a preceding self 303.
                  (jabber-test-muc-aff--presence a room "new-self" "a@example.org/device")
                  (should-not (jabber-test-muc-aff--sender a room "self-a"))
                  (should (equal (jabber-test-muc-aff--sender a room "new-self") "a@example.org")))
                (should (jabber-sm--room-ready-p (fsm-get-state-data a) room))
                (should-not (jabber-test-muc-aff--sender a room "guest-new"))
                (should (equal (jabber-test-muc-aff--recipients a room) '("a@example.org")))
                (should (equal (jabber-test-muc-aff--recipients b room) '("other@example.org")))
                (should (equal (jabber-test-muc-aff--sender b room "guest") "other@example.org")))
            (when (timerp (plist-get attempt :timer))
              (cancel-timer (plist-get attempt :timer)))))))))

(ert-deftest jabber-test-muc-aff-native-self-303-retires-only-alias ()
  "Self 303 retires its alias, never the lease or another account's occupant."
  (let ((send (symbol-function 'jabber-send-sexp)))
    (dolist (self-status '(nil t))
      (jabber-test-muc-aff--with-room
        (jabber-muc--start-attempt a room "self-a")
        (jabber-test-muc-aff--presence a room "self-a" "a@example.org/device")
        (jabber-test-muc-aff--presence b room "self-a" "other@example.org/device")
        (cl-letf (((symbol-function 'jabber-send-sexp) send)
                  ((symbol-function 'jabber-send-sexp--raw) (lambda (&rest _) t)))
          (jabber-muc-nick a room "new-self"))
        (let ((attempt (jabber-sm--room-attempt (fsm-get-state-data a) room))
              (membership (assq a (jabber-muc-room-entries room))))
          (unwind-protect
              (progn
                (fsm-send-sync
                 a `(:stanza (presence ((from . ,(concat room "/self-a")) (type . "unavailable"))
                                       (x ((xmlns . ,jabber-muc-xmlns-user))
                                          (item ((nick . "new-self")))
                                          ,@(when self-status '((status ((code . "110")))))
                                          (status ((code . "303")))))))
                (should (eq attempt (jabber-sm--room-attempt (fsm-get-state-data a) room)))
                (should (eq membership (assq a (jabber-muc-room-entries room))))
                (should (eq (plist-get attempt :status) 'pending))
                (should-not (jabber-test-muc-aff--sender a room "self-a"))
                (jabber-test-muc-aff--presence a room "new-self" "a@example.org/device")
                (should (jabber-sm--room-ready-p (fsm-get-state-data a) room))
                (should (equal (jabber-test-muc-aff--sender a room "new-self") "a@example.org"))
                (should (equal (jabber-test-muc-aff--sender b room "self-a") "other@example.org")))
            (when (timerp (plist-get attempt :timer))
              (cancel-timer (plist-get attempt :timer)))))))))

(provide 'jabber-test-muc-affiliations)
;;; jabber-test-muc-affiliations.el ends here
