Releasing VM

* NonGNU ELPA

Current package contents of GitLab vm/main will be at NonGNU-devel in
https://elpa.nongnu.org/nongnu-devel/vm.html.

You can test installing from here by add to package-archives:

(add-to-list 'package-archives 
             '("nongnu-devel" . "https://elpa.nongnu.org/nongnu-devel/"))

Note that it takes around 12 hours for an update to be available on
NonGNU-devel.

Once release is made with a release version number (1.2.3)
in vm.el, it will become available as a NonGNU ELPA
package at https://elpa.nongnu.org/nongnu/vm.html

* check for unexpected warnings
- make -j 32  # needs generated files
- make -j 32 lint

* use package-lint to check vm.el packages
requires package-lint
  make package-lint
or 
  M-x package-lint-current-buffer
note lint will not be clean, due to xemacs references

* release is built initial in fork
then merge to make official

* version update in these files:
- Add note about release to info/vm.texinfo @item Version ..
- NEWS
- version in configure.ac AC_INIT
- lisp/vm.el Version:
  
* test build
- make distclean
- autoconf
- ./configure
- make
- make install

* pre-release testing from repo:
changes must be committed

(package-vc-install 
  '(vm :url "file:////Users/markd/projs/emacs/vm/vm-markd"
       :lisp-dir "lisp"))

Note: as of emacs 30.2, package-vc-install doesn't generate
a correct description or commit.

* commit and tag
- tag is in the form '8.3.0'
- a branch are only made if changes are needed relative to a tag


* pre-release testing from fork:
(package-vc-install
  '(vm :url"https://gitlab.com/USER/vm.git"
       :lisp-dir "lisp"
       :branch "8.3.0"))
  
* post-release testing from main repo:
(package-vc-install
  '(vm :url"https://gitlab.com/emacs-vm/vm.git"
       :lisp-dir "lisp"
       :branch "8.3.0"))

* push and test install once available in nongnu ELPA

* tell the distribution packagers

Most distributions still ship 8.2.0b from 2011, because their automatic
new-version checks point at Launchpad, which VM left.  See issue #478 for what
each packager watches and how to correct it; until that is corrected they only
learn of a release by being told.

- Fedora: @goeran packages it and already builds from git.  Tell him the tag
  exists.
- Debian: reply on the open bug https://bugs.debian.org/1134674.  Debian is
  what Ubuntu, Devuan, Kali, Parrot, PureOS, Raspbian, Trisquel, Pardus and
  Deepin all rebuild, so it is the only one of these worth a conversation.
- Gentoo (gnu-emacs@gentoo.org), pkgsrc (pkgsrc-users@NetBSD.org), openSUSE
  (devel project =editors=, package =emacs-vm=): a version-bump bug each.
- Nix needs nothing.  It follows NonGNU ELPA.

Then check https://repology.org/project/emacs:vm/versions a couple of weeks
later.  It shows every distribution's version on one page, so it is both the
check that the release landed and the check that the watch-file corrections
took effect.

* update version to a snapshot of the next patch
e.g. 8.3.0 -> 8.3.1snapshot


