name: CI
permissions: {}
on:
  pull_request:
  push:
    paths-ignore:
    - '**.org'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 24.4
          - 24.5
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - snapshot
    steps:
    - name: Install Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Checkout xml-rpc-el
      uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Run tests
      run: 'make test'
