name: test-macos
on: push

jobs:
  runner-job:
    # using the PostgreSQL version pre-installed on GitHub's MacOS virtual images
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Set runner timezone
        uses: szenius/set-timezone@v2.0
        with:
           timezoneLinux: "UTC-01:00"
           timezoneMacos: "UTC-01:00"
           timezoneWindows: "UTC-01:00"

      - name: Set up pre-installed PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v7
        with:
           username: pgeltestuser
           password: pgeltest
           database: pgeltestdb
        id: postgres
        env:
           TZ: UTC-01:00

      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
           version: 29.4

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run tests over network
        run: make -C test test
        env:
           TZ: UTC-01:00
