name: test-pgv15b-docker
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Install Emacs
        run: |
          sudo apt-get update
          sudo apt-get install emacs podman

      - name: Start Docker/Podman image of PostgreSQL
        run: sudo docker run --detach \
             --name pgsql \
             --publish 5432:5432 \
             -e POSTGRES_DB=pgeltestdb \
             -e POSTGRES_USER=pgeltestuser \
             -e POSTGRES_PASSWORD=pgeltest \
             docker.io/library/postgres:15

             # -c ssl=on \
             # -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem \
             # -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key


             # --health-cmd pg_isready \
             # --health-interval 10s \
             # --health-timeout 5s \
             # --health-retries 5 \

      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Run connection tests from Emacs
        run: make -C test test test-tls
