name: test
on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version:
        - 25.1
        - 25.3
        - 26.1
        - 26.2
        - 26.3
        - 27.1
        - 27.2
        - 28.1
        - 28.2
        - snapshot

    steps:
    - name: Checkout mentor
      uses: actions/checkout@v2

    - name: Install emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Build mentor
      run: make all

    - name: Test mentor
      run: make test
