name: test
on: [ push, pull_request ]
permissions: {}
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs_version:
        - 25.1
        - 25.3
        - 26.1
        - 26.2
        - 26.3
        - 27.1
        - 27.2
        - 28.1
        - 28.2
        - snapshot

    steps:
    - name: Checkout async
      uses: actions/checkout@v3
      with:
        repository: jwiegley/emacs-async
        path: async

    - name: Checkout url-scgi
      uses: actions/checkout@v3
      with:
        repository: skangas/url-scgi
        path: url-scgi

    - name: Checkout xml-rpc
      uses: actions/checkout@v3
      with:
        repository: xml-rpc-el/xml-rpc-el
        path: xml-rpc

    - name: Checkout mentor
      uses: actions/checkout@v3
      with:
        repository: skangas/mentor
        path: mentor

    - name: Install emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: Build mentor
      run: make -C mentor all

    - name: Test mentor
      run: make -C mentor test
