name: test-windows
on: push

jobs:
  runner-job:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Set runner timezone
        uses: szenius/set-timezone@v2.0
        with:
           timezoneLinux: "UTC-01:00"
           timezoneMacos: "UTC-01:00"
           timezoneWindows: "UTC-01:00"

      - name: Set up pre-installed PostgreSQL
        uses: ikalnytskyi/action-setup-postgres@v7
        with:
           username: pgeltestuser
           password: pgeltest
           database: pgeltestdb
        id: postgres
        env:
           TZ: UTC-01:00

      - name: Install Emacs
        run: choco install --no-progress -y emacs

      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Run tests
        run: make -C test test
